### ISSUE TITLE
systemd 245 breaks cilium pod to out-of-node traffic

### ISSUE THREAD

**Issue by nberlee** [cilium/cilium#10645]
## Bug report

**General Information**
Updating systemd 244.2-2 on Arch to systemd 245.2-1 and 245-3 break pod to out-of-node ipv4 traffic. Reverting to 244.2-2 and rebooting fixes the problem. (ipv6 keeps working on all versions)

I did a sysctl -a diff with 244 vs 245 with cilium running (ready):
```
< net.ipv4.conf.all.promote_secondaries = 1
> net.ipv4.conf.all.promote_secondaries = 0
< net.ipv4.conf.cilium_host.accept_source_route = 1
> net.ipv4.conf.cilium_host.accept_source_route = 0
< net.ipv4.conf.cilium_host.promote_secondaries = 0
> net.ipv4.conf.cilium_host.promote_secondaries = 1
< net.ipv4.conf.cilium_host.rp_filter = 0
> net.ipv4.conf.cilium_host.rp_filter = 2
< net.ipv4.conf.cilium_net.accept_source_route = 1
> net.ipv4.conf.cilium_net.accept_source_route = 0
< net.ipv4.conf.cilium_net.promote_secondaries = 0
> net.ipv4.conf.cilium_net.promote_secondaries = 1
< net.ipv4.conf.default.accept_source_route = 1
> net.ipv4.conf.default.accept_source_route = 0
< net.ipv4.conf.default.promote_secondaries = 0
> net.ipv4.conf.default.promote_secondaries = 1
< net.ipv4.conf.default.rp_filter = 0
> net.ipv4.conf.default.rp_filter = 2
< net.ipv4.conf.ens192.accept_source_route = 1
> net.ipv4.conf.ens192.accept_source_route = 0
< net.ipv4.conf.ens192.promote_secondaries = 0
> net.ipv4.conf.ens192.promote_secondaries = 1
< net.ipv4.conf.ens192.rp_filter = 0
> net.ipv4.conf.ens192.rp_filter = 2
< net.ipv4.conf.lo.accept_source_route = 1
> net.ipv4.conf.lo.accept_source_route = 0
< net.ipv4.conf.lo.promote_secondaries = 0
> net.ipv4.conf.lo.promote_secondaries = 1
< net.ipv4.conf.lo.rp_filter = 0
> net.ipv4.conf.lo.rp_filter = 2
```

- Cilium version (run `cilium version`)
1.7.1
- Kernel version (run `uname -a`)
Linux k8s22 5.5.10-arch1-1 #1 SMP PREEMPT Wed, 18 Mar 2020 08:40:35 +0000 x86_64 GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
Kubernetes 1.17.4
- Upload a system dump (run `curl -sLO
https://github.com/cilium/cilium-sysdump/releases/latest/download/cilium-sysdump.zip &&
python cilium-sysdump.zip` and then attach the generated zip file)

[cilium-sysdump-20200319-221054.zip](https://github.com/cilium/cilium/files/4356947/cilium-sysdump-20200319-221054.zip)

**Comment by nberlee** [comment]
The breaking change is in /usr/lib/sysctl.d/50-default.conf
```
25c25,27
< net.ipv4.conf.all.rp_filter = 2
---
> net.ipv4.conf.default.rp_filter = 2
> net.ipv4.conf.*.rp_filter = 2
> -net.ipv4.conf.all.rp_filter
28c30,32
< net.ipv4.conf.all.accept_source_route = 0
---
> net.ipv4.conf.default.accept_source_route = 0
> net.ipv4.conf.*.accept_source_route = 0
> -net.ipv4.conf.all.accept_source_route
31c35,37
< net.ipv4.conf.all.promote_secondaries = 1
---
> net.ipv4.conf.default.promote_secondaries = 1
> net.ipv4.conf.*.promote_secondaries = 1
> -net.ipv4.conf.all.promote_secondaries
```
a minimal fix for 245 is:
```
echo 'net.ipv4.conf.lxc*.rp_filter = 0' | sudo tee -a /etc/sysctl.d/90-override.conf && sudo systemctl start systemd-sysctl
```

**Comment by aanm** [comment]
there was a systemd bug that we had in the past. Although it is completely unrelated it might help give some help to figure out the underlying issue https://github.com/cilium/cilium/pull/8351

**Comment by brb** [comment]
This is very annoying. We should warn users when systemd > 245 is detected.

**Comment by aanm** [comment]
Add log statement if user is running with systemd version

**Comment by joestringer** [comment]
I have an Ubuntu 20.04 development machine that I use, where I run microk8s.

I've installed Cilium v1.8.1:
```
$ cilium version
Client: 1.6.8 f534e98df 2020-03-25T13:32:35+01:00 go version go1.12.17 linux/amd64
Daemon: 1.8.1 5ce2bc7b3 2020-07-02T20:04:47+02:00 go version go1.14.4 linux/amd64
```

It's running systemd 245:
```
$ systemctl --version
systemd 245 (245.4-4ubuntu3.2)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

Here's the config (I don't recall whether I modified these, but they seem consistent with the case where connectivity was not working for you:

```
$ grep rp_filter /etc/sysctl.d/*
/etc/sysctl.d/10-network-security.conf:net.ipv4.conf.default.rp_filter=2
/etc/sysctl.d/10-network-security.conf:net.ipv4.conf.all.rp_filter=2
/etc/sysctl.d/99-sysctl.conf:#net.ipv4.conf.default.rp_filter=1
/etc/sysctl.d/99-sysctl.conf:#net.ipv4.conf.all.rp_filter=1
```

Interestingly it seems to be set to 0, although I've rebooted this machine recently:
```
$ sysctl net.ipv4.conf.all.rp_filter
net.ipv4.conf.all.rp_filter = 0
```

I note that parts of Cilium now disable rp_filter:

```
$ git grep rp_filter pkg/datapath
pkg/datapath/connector/add.go:  return sysctl.Disable(fmt.Sprintf("net.ipv4.conf.%s.rp_filter", ifName))
pkg/datapath/loader/base.go:            {"net.ipv4.conf.all.rp_filter", "0", false},
```

Deploying the single-node-connectivity YAML I see that external connectivity works:
https://github.com/cilium/cilium/blob/master/examples/kubernetes/connectivity-check/connectivity-check-single-node.yaml
```
$ k get po | grep external
pod-to-external-1111-75df4847d7-tjxpq                    1/1     Running   1          23m
pod-to-external-fqdn-allow-google-cnp-77d7586f58-9l5z6   1/1     Running   1          23m
```

So I think this issue is resolved as of the latest Cilium releases?

**Comment by nberlee** [comment]
I will try 1.8.2 tomorrow evening, but I just tested it on 1.7.6 and it is still broken.

Also 1.7.6 seems to have the same interface specific line:
```
$ grep -ri rp_filter
pkg/endpoint/connector/add.go:	return sysctl.Disable(fmt.Sprintf("net.ipv4.conf.%s.rp_filter", ifName))
pkg/datapath/loader/base.go:		{"net.ipv4.conf.all.rp_filter", "0", false},
```
my systemd version right now:
```
$ systemctl --version
systemd 245 (245.6-8-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid```

```
picking a random lxc interface:
```
$ sysctl net.ipv4.conf.lxc4d36398ebb25.rp_filter
net.ipv4.conf.lxc4d36398ebb25.rp_filter = 2
$ sysctl net.ipv4.conf.all.rp_filter
net.ipv4.conf.all.rp_filter = 0
$ sysctl net.ipv4.conf.cilium_host.rp_filter
net.ipv4.conf.cilium_host.rp_filter = 2
```
pinging an outside destination ip.
```
$ kubectl run  --restart=Never -it --rm --image=alpine  test2 ash
If you don't see a command prompt, try pressing enter.
/ # ping 9.9.9.9
PING 9.9.9.9 (9.9.9.9): 56 data bytes
^C
--- 9.9.9.9 ping statistics ---
19 packets transmitted, 0 packets received, 100% packet loss
/ # exit
pod "test2" deleted
```
(it works fine with my 90-override.conf described in the second post of this issue)


Maybe Ubuntu 20.04 has a different `/usr/lib/sysctl.d/50-default.conf`?
```
$ grep rp_filter /usr/lib/sysctl.d/50-default.conf
net.ipv4.conf.default.rp_filter = 2
net.ipv4.conf.*.rp_filter = 2
-net.ipv4.conf.all.rp_filter
```

**Comment by joestringer** [comment]
> Maybe Ubuntu 20.04 has a different /usr/lib/sysctl.d/50-default.conf

Good spotting. Ubuntu seems to carry a patch to systemd to explicitly remove those lines. I downloaded the tar from the ubuntu packages site and:

```
$ grep -R rp_filter systemd_245.4-4ubuntu3.2/debian/patches/*
systemd_245.4-4ubuntu3.2/debian/patches/debian/UBUNTU-drop-kernel.-settings-from-sysctl-defaults-shipped.patch:-net.ipv4.conf.default.rp_filter = 2
systemd_245.4-4ubuntu3.2/debian/patches/debian/UBUNTU-drop-kernel.-settings-from-sysctl-defaults-shipped.patch:-net.ipv4.conf.*.rp_filter = 2
systemd_245.4-4ubuntu3.2/debian/patches/debian/UBUNTU-drop-kernel.-settings-from-sysctl-defaults-shipped.patch:--net.ipv4.conf.all.rp_filter
```

Furthermore at least in my environment networkd doesn't seem to be enabled:

```
$ networkctl | grep lxc2cd6411
WARNING: systemd-networkd is not running, output will be incomplete.

357 lxc2cd6411832fb ether    n/a         unmanaged
```

**Comment by brb** [comment]
I have the same `WARNING: systemd-networkd is not running, output will be incomplete. [...] unmanaged` on Arch Linux. It seems that `rp_filter` is being set by `systemd-sysctl` service.

@joestringer What does `systemctl status systemd-sysctl` return on your machine?

**Comment by joestringer** [comment]
@brb it's `Active (exited)`, but per my last post I think the Ubuntu version of systemd-sysctl won't apply `rp_filter` by default. That seems like it explains the difference in behaviour to me.

**Comment by brb** [comment]
> per my last post I think the Ubuntu version of systemd-sysctl won't apply rp_filter by default

@joestringer Ah, damn, missed that comment. Yeah, that explains the difference.

**Comment by livelace** [comment]
Yep, caught the same problem during first cilium installation (found this bug right after).
Just overrided **rp_filter** settings in **/etc/sysctl.d/90-override.conf**
Gentoo, Systemd 245.5

**Comment by matoszz** [comment]
Can confirm this issue is still happening on Cilium 1.8.2 and using the latest 2605 flatcar release channel

**Comment by mmack** [comment]
I've hit the same problem Ubuntu 20.04. 

For future googlers on hetzner systems: Check /etc/sysctl.d/99-hetzner.conf, they set net.ipv4.conf.all.rp_filter=1 there.

**Comment by mvisonneau** [comment]
I am not sure if related but after attempting a 1.8.2 -> 1.8.3 upgrade on Ubuntu 20.04 / 5.4.0-1021-aws, agent pods end up crashing with the following logs. Rolling back to 1.8.2, pods are healthy and do not contain those errors. 🤷 

```json
{"error":"Failed to sysctl -w net.ipv4.conf.eth0.rp_filter=2: could not open the sysctl file /proc/sys/net/ipv4/conf/eth0/rp_filter: open /proc/sys/net/ipv4/conf/eth0/rp_filter: no such file or directory","level":"error","msg":"Error while initializing daemon","subsys":"daemon"}
{"error":"Failed to sysctl -w net.ipv4.conf.eth0.rp_filter=2: could not open the sysctl file /proc/sys/net/ipv4/conf/eth0/rp_filter: open /proc/sys/net/ipv4/conf/eth0/rp_filter: no such file or directory","level":"fatal","msg":"Error while creating daemon","subsys":"daemon"}
{"error":"Operation cannot be fulfilled on ciliumnodes.cilium.io \"ip-10-6-11-13.eu-west-1.compute.internal\": the object has been modified; please apply your changes to the latest version and try again","level":"warning","msg":"Unable to update CiliumNode custom resource","subsys":"ipam"}
{"level":"info","msg":"regenerating all endpoints","reason":"one or more identities created or deleted","subsys":"endpoint-manager"}
{"level":"info","msg":"regenerating all endpoints","reason":"one or more identities created or deleted","subsys":"endpoint-manager"}
```

**Comment by joestringer** [comment]
@mvisonneau That looks to me like that is a separate regression in v1.8.3 specific to Ubuntu in EKS environments, would you mind opening a new issue for this?

**Comment by joestringer** [comment]
@mvisonneau Is there an `eth0` interface on those nodes? If not, then I think this is a separate bug (regression) in v1.8.2 on Ubuntu in EKS environments. If there is an `eth0` then it may still be this issue.

**Comment by joestringer** [comment]
@mvisonneau OK great, would you mind filing a separate bug for that to help track fixing the regression? The output from your last couple of comments on this thread would be a great start for such a bug.

**Comment by schamane** [comment]
On Ubuntu hosted by Hetzner i dont have any config added by hetzner self anymore. But had same issue with systemd. So i added sysctrl configuration and got cilium 1.8.3 working.

ubuntu version 20.04.1
kernel 5.8.10-050810-generic
docker 19.3.13
kubernetes 1.19.2
systemd 245 (245.4-4ubuntu3.2)

```
net.ipv4.conf.lxc*.rp_filter = 0
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
```

**Comment by tgraf** [comment]
A good workaround for this is to enable endpoint-routes `--enable-endpoint-routes`. It enforces symmetric routing. https://github.com/cilium/cilium/pull/13346 is going to fix `endpoint-routes` in combination with tunneling.

**Comment by nberlee** [comment]
`  enable-endpoint-routes: "true"` with default systemd 2.45 (now 46) `rp_filter` works great using native routing.

Guess i've missed this setting as I set up Native routing in `1.6` initially.

**Comment by joestringer** [comment]
Followup items:
* Is there context from upstream systemd release around this change?
* Open issue upstream to discuss impact there

@errordeveloper mentioned he can share some systemd configuration he used to mitigate this issue.

If we want to enable endpoint routes mode by default, we will also need to resolve #13121.

**Comment by errordeveloper** [comment]
I have encountered this on OpenShift, with uses CoreOS. 
I can confirm that following two solutions work well:

Either write `/etc/sysctl.d/99-override_cilium_rp_filter.conf`  with the following contents:
```
net.ipv4.conf.lxc*.rp_filter = 0
net.ipv4.conf.cilium_*.rp_filter = 0
```

Or use `enable-endpoint-routes: "true"`, however if you are using tunnelling mode, you will require either Cilium 1.8.5 (not yet released due to be released soon), or 1.9.0 (also due to be released) (see https://github.com/cilium/cilium/pull/13346).

**Comment by nberlee** [comment]
@joestinger https://github.com/cilium/cilium/issues/10645#issuecomment-601451909

>Is there context from upstream systemd release around this change?

https://github.com/systemd/systemd/commit/5d4fc0e665a3639f92ac880896c56f9533441307#diff-7816eed8ca6324f23a690cc5f58e6bf7 whch solved issue https://github.com/systemd/systemd/issues/6282

**Comment by jaysiyani** [comment]
Using flatcar 2605 and above, the minimal fix: `echo 'net.ipv4.conf.lxc*.rp_filter = 0' | sudo tee -a /etc/sysctl.d/90-override.conf && sudo systemctl start systemd-sysctl` works. But if the node is rebooted and the pod get's a new IP address on the same node, it stops working.

**Comment by errordeveloper** [comment]
@jaysiyani that sounds like you need to find the correct way to persist configuration on Flatcar, I can have one very concrete [example in the docs](https://docs.flatcar-linux.org/os/other-settings/#tuning-sysctl-parameters) that you might want to try.

**Comment by errordeveloper** [comment]
Some additional information on this:

Systemd maintainer have introduced this configuration in attempt of fixing some kind of boot-time race condition, and _it seems_ to improve overall consistency of how the system behaves. 

Initially there was https://github.com/systemd/systemd/commit/1836bf9e1d70240c8079e4db4312309f4f1f91fd, which later was followed-up with a bug report https://github.com/systemd/systemd/issues/6282 an a subsequent PR https://github.com/systemd/systemd/pull/14589, which ultimately appears to be the cause of this issue for Cilium.

What I am not quite clear on is why what Cilium does is insufficient in overcoming this system configuration?
My understanding is that systemd only runs it's `systemd-sysctl` component once at boot, see [`systemd-sysctl.service`](https://www.freedesktop.org/software/systemd/man/systemd-sysctl.service.html).

What also makes this a little harder to understand is that there a multiple places in Cilium code where `rp_fileter` settings are manipulated:

https://github.com/cilium/cilium/blob/72949b4b49d43e6dbb4714929222acb688ce6dd2/bpf/init.sh#L78

https://github.com/cilium/cilium/blob/9e48678686e213b0b36d616d0bf20f5104eeca04/pkg/datapath/loader/netlink.go#L182

https://github.com/cilium/cilium/blob/72949b4b49d43e6dbb4714929222acb688ce6dd2/pkg/datapath/loader/base.go#L178

https://github.com/cilium/cilium/blob/28d9889795e41026bf5ecd29c069f7b73bdd20f5/pkg/datapath/connector/add.go#L68

https://github.com/cilium/cilium/blob/8078e12f3ad674e69586c15abc4e86156bbc5cdd/pkg/datapath/linux/datapath.go#L56

https://github.com/cilium/cilium/blob/28d9889795e41026bf5ecd29c069f7b73bdd20f5/pkg/datapath/connector/veth.go#L110

https://github.com/cilium/cilium/blob/b323ecadeecbdde0f91dc92dc8e494bcfba29dca/pkg/datapath/connector/ipvlan.go#L196

Let's take what `cilium/bpf/init.sh` does, what exactly happens after that that override the setting?

I'd like to work out a proper solution for this, as systemd is unlikely to change, or even if it will change in the future, releases that have this feature are going to be around for quite some time.

**Comment by errordeveloper** [comment]
It looks like network interface sysctls are applied to new interfaces.

From [the docs](https://github.com/systemd/systemd/blob/78dff3f3d72c62357543fe1716da3886cff54a10/man/sysctl.d.xml#L79-L83):

> The settings configured with `sysctl.d` files will be applied early on boot. The
>  network interface-specific options will also be applied individually for each network interface as it
> shows up in the system. (More specifically, `net.ipv4.conf.*`, `net.ipv6.conf.*`, `net.ipv4.neigh.*`
> and `net.ipv6.neigh.*`).

I had a look at the code also, but not quite sure how exactly configuration is applied to each new device, but per above it's clear that some part of systemd does it for sure (albeit not `systemd-sysctl` itself).

It looks like the best fix would be to make either node init or CNI plugin installer drop a config file, and in addition to that all attempt where Cilium tries to write sysctls should check the value after writing and at least log an error/warning in case the intended value doesn't persist.

Aside from that, another question to ask is - is there a way to enforce sysctls from an eBPF program?

**Comment by errordeveloper** [comment]
From talking to @qmonnet it sounds like an eBPF program cannot magically enforce sysctls, so I'll just scratch that idea 😉 

There is however [CNI tuning plugin](https://www.cni.dev/plugins/meta/tuning/). but it looks like it is just writing to `/proc/sys/net/*`, which is what Cilium does already so it won't be sufficient to overcome systemd's behaviour.

I am thinking perhaps `cilium-cni` could detect systemd version and write out configs for each interface, how would that sound  to people? I think this would most reliable defence. If we were to just write one file with wildcard as documented, there is a good chance it gets overwritten deleted or overridden with another file. But having a config file for each interface will reduce the chances of collision.

**Comment by joestringer** [comment]
> could detect systemd version and write out configs for each interface, how would that sound to people?

Long-term, everything will trend towards newer systemd so unless we expect a significant portion of users to be running non-systemd hosts, I don't think the "detect systemd version" piece makes any meaningful difference; I'd skip that to keep things simple.

Coordinating with systemd seems like the right solution, at the moment my understanding is that the initial lifecycle of the device from creation to configuration by {cilium,systemd} is not done in a coordinated manner, which means that we end up arguing with each other and the last one to perform configuration is the one that wins. Seems like that's systemd. Therefore, I think we either need to tell systemd how to configure the devices, or we need a mechanism to know when systemd will no longer mess with the configuration at which point we know it's safe for us to do so. The former approach seems more viable.

> If we were to just write one file with wildcard as documented, there is a good chance it can get overwritten, deleted or shadowed by another config file. But having a config file for each interface will reduce the chances of collision.

As long as we're happy with the notion of writing up to say ~100 of these on a given node, and re-writing them on the filesystem every time a new pod is deployed (perhaps dozens of times per minute). I suspect this is probably not noticeable from a performance perspective, given how small the configuration would be. Alternative is we write one configuration file and then just have some background monitor that double-checks that the configuration is still OK (for instance, by validating that a random endpoint's `sysctl` configuration matches what we expect). Just an idea, we do similar sorts of things via `pkg/controller` today.

**Comment by joestringer** [comment]
When I added this to 1.10 feature candidates, I was meaning #14955 should resolve this. It's actually clearer to track #14955 in the project so I've removed this one from 1.10. This doesn't change which release we intend to address this issue more generically.

**Comment by cmacrae** [comment]
Just to weigh in here for anyone else who might be searching for it, this affected my systems on NixOS 21.03 (and may indeed affect previous releases). The `sysctl` configuration mentioned above can be implemented using the [`boot.kernel.sysctl`](https://search.nixos.org/options?channel=20.09&show=boot.kernel.sysctl&from=0&size=50&sort=relevance&query=boot.kernel.sysctl) configuration option

**Comment by eyanulis** [comment]
It appears that this might still be a problem, even _with_ `--enable-endpoint-routes` on, for NodePort and LoadBalancer services when DSR is enabled.

Specifically:
* NodePort services where the request hits Node A, but the backend is on Node B (such that the DSR response from the pod on Node B has to get SNAT'd to Node A's IP on the way out)
* LoadBalancer services such as those provisioned by MetalLB, where in all cases the DSR response from the pod must get SNAT'd to the LoadBalancer VIP
* I suspect the same for manually defined ExternalIP services (effectively the same as the LoadBalancer case described above) 

As far as I can tell (not 100% sure, but maybe 85%), the egress SNAT occurring on DSR responses from the backend pod happens before RPF is evaluated, so an `rp_filter` value of 2 will drop the packet because the resulting source IP on the packet doesn't exist / may not be routable on the node.

The workaround as described above (setting `rp_filter=0` on all LXC veths) fixes this case as well. I just want to call out a possible use case where #14955 likely will _not_ fix this because Cilium (correctly, IMO) won't be installing routes for LoadBalancer VIPs or other nodes' IPs that would satisfy RPF.

**Comment by brb** [comment]
@eyanulis Your discovery looks correct to me.

I think we should create a controller which does a periodic scan of rp_filter's and at least logs a warning when it detects the rp_filter change.

**Comment by roobre** [comment]
In case it helps anyone, I can confirm this still happening with `systemd 249 (249.3-1-arch)`, `systemd-networkd` enabled, and `cilium 1.10.3`. The [sysctl override workaround](https://github.com/cilium/cilium/issues/10645#issuecomment-601451909) fixed the issue for me (after recreating all pods).
