### ISSUE TITLE
SNATed "need to frag" ICMP packet doesn't get forwarded to pod

### ISSUE THREAD

**Issue by qingkunl** [cilium/cilium#12968]
## Bug report

Assuming Pod A on Node A tries to send a packet of size 1450 to Node B and the network path is:

    Pod A (MTU 1500) -> Node A (MTU 1500) -> Switch X (MTU 1420) -> Node B (MTU 1500)

Switch X would drop this packet and send back an ICMP packet saying **"need to frag (mtu 1420)"**.

There are two issues with Cilium 1.8.2:

1. Cilium would drop the ICMP packet as invalid packet (https://github.com/cilium/cilium/issues/12854). Using `brb0/cilium:skb-pull-v0` image mentioned by https://github.com/cilium/cilium/issues/12854#issuecomment-675569188 could work around this issue.

2. With the above issue worked around, the ICMP packet can be sent to Node A, but Cilium still doesn't forward it to Pod A. As a result, Pod A doesn't know it needs to fragment the packet of size 1450 and keeps retransmitting it, while Switch X keeps dropping it.

**General Information**

- Cilium version (run `cilium version`)

The `brb0/cilium:skb-pull-v0` image mentioned by https://github.com/cilium/cilium/issues/12854#issuecomment-675569188

```
Client: 1.8.90 f0e584d92 2020-08-14T12:33:50+02:00 go version go1.15 linux/amd64
Daemon: 1.8.90 f0e584d92 2020-08-14T12:33:50+02:00 go version go1.15 linux/amd64
```

- Kernel version (run `uname -a`)

```
5.4.19
```

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)

```
v1.17.9
```

- Link to relevant artifacts (policies, deployments scripts, ...)

  - [deployment yaml](https://gist.github.com/qingkunl/43cbb61bc585c31e14fe9041640fbd6b)

**How to reproduce the issue**

Construct a network scenario described in the above problem description to reproduce.

**Comment by aditighag** [comment]
https://github.com/cilium/cilium/issues/12854#issuecomment-675088907

**Comment by qingkunl** [comment]
BTW, I'm using AWS VM.

```
# ethtool -i eth0
driver: ena
version: 2.1.0K
firmware-version:
expansion-rom-version:
bus-info: 0000:00:03.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
```

**Comment by aditighag** [comment]
Per the comment [1] in the issue you've called out, the reporter was using a certain NIC that led to drops. Also, the issue has been fixed in latest.
Did you run `cilium monitor` to see where exactly the drops were happening in your setup?

[1] https://github.com/cilium/cilium/issues/12854#issuecomment-675088907

**Comment by qingkunl** [comment]
> Per the comment [1] in the issue you've called out, the reporter was using a certain NIC that led to drops. Also, the issue has been fixed in latest.
> Did you run `cilium monitor` to see where exactly the drops were happening in your setup?
> 
> [1] [#12854 (comment)](https://github.com/cilium/cilium/issues/12854#issuecomment-675088907)

I'm already using the image with the fix mentioned in  #12854 .

Using Cilium 1.8.2, I can see the ICMP drop as invalid packet with `cilium monitor`. Using brb0/cilium:skb-pull-v0 image mentioned by https://github.com/cilium/cilium/issues/12854#issuecomment-675569188, I don't see any drop with `cilium monitor`, but the ICMP packet for "need to frag" still doesn't get forwarded to the Pod.

**Comment by brb** [comment]
@qingkunl Can you run `cilium monitor -t drop` to validate that cilium is actually dropping the "need to frag" ICMP messages?

**Comment by qingkunl** [comment]
> @qingkunl Can you run `cilium monitor -t drop` to validate that cilium is actually dropping the "need to frag" ICMP messages?

I don't see cilium drop anything, and I can confirm the "need to frag" ICMP messages received by the host with `tcpdump -i eth0 icmp -nn`. However, I don't see the "need to frag" ICMP messages in the Pod with `tcpdump -i any icmp -nn`. Any idea to check where it's dropped?

**Comment by brb** [comment]
Did the ICMP packet had the dest IP addr == pod IP?

**Comment by qingkunl** [comment]
> Did the ICMP packet had the dest IP addr == pod IP?

The dest IP is the node IP, which makes sense because the Pod packet is SNAT'ed when going out of the node. There should be some way to track the connection and forward the packet to Pod, like other SNAT Pod traffics.

**Comment by brb** [comment]
OK, I see. Unfortunately, such functionality is not implemented in Cilium, but we would happily consider a PR with such additions.

**Comment by qingkunl** [comment]
This is still an issue

**Comment by sahid** [comment]
> OK, I see. Unfortunately, such functionality is not implemented in Cilium, but we would happily consider a PR with such additions.

I will take the leads on it. Thanks.
