### ISSUE TITLE
Inconsistent view of nodes in cilium-agent (cilium node list returns deadline exceeded)

### ISSUE THREAD

**Issue by nr17** [cilium/cilium#14746]
**General Information**

- Cilium version (run `cilium version`)
Client: 1.7.12 56653039c 2020-12-03T16:11:41-08:00 go version go1.13.15 linux/amd64
Daemon: 1.7.12 56653039c 2020-12-03T16:11:41-08:00 go version go1.13.15 linux/amd64

- Kernel version (run `uname -a`)
Linux ip-10-xx-yy-zz 5.4.0-1032-aws #33-Ubuntu SMP Wed Dec 9 17:13:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.8", GitCommit:"ec6eb119b81be488b030e849b9e64fda4caaf33c", GitTreeState:"clean", BuildDate:"2020-03-12T20:52:22Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

- Link to relevant artifacts (policies, deployments scripts, ...)
- Generate and upload a system zip:

[cilium-142-244.tar.gz](https://github.com/cilium/cilium/files/5877807/cilium-142-244.tar.gz)

**How to reproduce the issue**
At this point steps are not manual. We use a in-house kubernetes rolling-update controller to recycle nodes older than a configured age. To reproduce this issue, we set the nodes' maxAge to 20 mins. 

The symptom showed up as one of the cilium etcd cluster node not coming up. The "check-dns" container inside it was unable to resolve its own dns entry, and hence the etcd pod was stuck in "Init" state.
On further debugging, it was found that the DNS Query packets were able to reach coredns pod from the originating node, and while the coredns pod was responding back with DNS Query response, it never made it back to the originating node.
The likely reason for this is that the cilium-agent on the coredns node had incorrect bpf tunnel entries and hence it was not able to route the response packet. The "cilium bpf tunnel list" showed no entry for the originating node.
"cilium monitor --drop" showed no dropped packets on originating or terminating node.
It was also found that "cilium node list" command was timing out on the terminating node, which is likely the cause of the inconsistent nodes state in the cilium-agent. Later it was found that few other nodes also had inconsistent view of k8s nodes and "cilium node list" was also timing out on those nodes.

Manual invocation of the following command also timed out on such nodes:
```
curl -v --unix-socket /var/run/cilium/cilium.sock http://localhost/v1/cluster/nodes
*   Trying /var/run/cilium/cilium.sock:0...
* Connected to localhost (/var/run/cilium/cilium.sock) port 80 (#0)
> GET /v1/cluster/nodes HTTP/1.1
> Host: localhost
> User-Agent: curl/7.68.0
> Accept: */*
>

```

Once we find a definite list of steps to reproduce it, the issue will be updated.

**Comment by nr17** [comment]
Seems like the goroutines handling the http://localhost/v1/cluster/nodes API are getting blocked on a node entry mutex which is already locked by some other routine.

The serving routine gets blocked on "entry.mutex.Lock()" in the code below:

// GetNodes returns a copy of all of the nodes as a map from Identity to Node.
func (m *Manager) GetNodes() map[node.Identity]node.Node {
	m.mutex.RLock()
	defer m.mutex.RUnlock()

	nodes := make(map[node.Identity]node.Node)
	for nodeIdentity, entry := range m.nodes {
		entry.mutex.Lock()
		nodes[nodeIdentity] = entry.node
		entry.mutex.Unlock()
	}

	return nodes
}

**Comment by nr17** [comment]
goroutines state:

```
  Goroutine 1 - User: /go/src/github.com/cilium/cilium/daemon/daemon_main.go:1392 main.runDaemon (0x1d0e6a6) [select 447248h42m12.434857384s]
  Goroutine 2 - User: /usr/local/go/src/runtime/proc.go:305 runtime.gopark (0x431300) [force gc (idle) 447215h19m43.878491598s]
  Goroutine 3 - User: /usr/local/go/src/runtime/proc.go:305 runtime.gopark (0x431300) [GC sweep wait]
  Goroutine 4 - User: /usr/local/go/src/runtime/proc.go:305 runtime.gopark (0x431300) [GC scavenge wait]
  Goroutine 6 - User: /usr/local/go/src/runtime/sys_linux_amd64.s:536 runtime.futex (0x461433) (thread 919483) [timer goroutine (idle)]
  Goroutine 7 - User: /usr/local/go/src/runtime/proc.go:305 runtime.gopark (0x431300) [GC worker (idle)]
  Goroutine 8 - User: /usr/local/go/src/runtime/proc.go:305 runtime.gopark (0x431300) [GC worker (idle)]
  Goroutine 9 - User: /usr/local/go/src/runtime/proc.go:305 runtime.gopark (0x431300) [GC worker (idle)]
  Goroutine 13 - User: /usr/local/go/src/runtime/proc.go:310 time.Sleep (0x44d9e7) [sleep 447215h19m43.878569388s]
  Goroutine 16 - User: /usr/local/go/src/runtime/proc.go:305 runtime.gopark (0x431300) [select 447248h42m45.444055448s]
  Goroutine 17 - User: /usr/local/go/src/runtime/proc.go:305 runtime.gopark (0x431300) [finalizer wait 447215h34m29.444115696s]
  Goroutine 19 - User: /usr/local/go/src/runtime/proc.go:305 runtime.gopark (0x431300) [GC worker (idle)]
  Goroutine 20 - User: /usr/local/go/src/runtime/proc.go:305 runtime.gopark (0x431300) [GC worker (idle)]
  Goroutine 21 - User: /usr/local/go/src/runtime/sys_linux_amd64.s:536 runtime.futex (0x461433) (thread 2664283) [timer goroutine (idle)]
  Goroutine 22 - User: /go/src/github.com/cilium/cilium/daemon/cleanup.go:74 main.(*daemonCleanup).registerSigHandler.func1 (0x1d3cd45) [chan receive 447248h42m45.44409013s]
  Goroutine 23 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447248h42m45.44409695s]
  Goroutine 33 - User: /usr/local/go/src/runtime/proc.go:305 runtime.gopark (0x431300) [GC worker (idle)]
  Goroutine 34 - User: /usr/local/go/src/runtime/proc.go:305 runtime.gopark (0x431300) [GC worker (idle)]
  Goroutine 35 - User: /usr/local/go/src/runtime/proc.go:305 runtime.gopark (0x431300) [GC worker (idle)]
  Goroutine 36 - User: /usr/local/go/src/runtime/sys_linux_amd64.s:536 runtime.futex (0x461433) (thread 2664441) [timer goroutine (idle)]
  Goroutine 38 - User: /usr/local/go/src/runtime/sigqueue.go:147 os/signal.signal_recv (0x445edc) (thread 2664266)
  Goroutine 39 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/klog/klog.go:1010 k8s.io/klog.(*loggingT).flushDaemon (0xc6ea8b) [chan receive]
  Goroutine 49 - User: /usr/local/go/src/runtime/sys_linux_amd64.s:536 runtime.futex (0x461433) (thread 2665313) [timer goroutine (idle)]
  Goroutine 65 - User: /usr/local/go/src/runtime/sys_linux_amd64.s:536 runtime.futex (0x461433) (thread 2664265) [timer goroutine (idle)]
  Goroutine 74 - User: /usr/local/go/src/syscall/asm_linux_amd64.s:53 syscall.Syscall6 (0x47b9fa) (thread 394068) [GC assist marking 447215h19m43.878694867s]
  Goroutine 81 - User: /usr/local/go/src/runtime/sys_linux_amd64.s:536 runtime.futex (0x461433) (thread 936149) [timer goroutine (idle)]
  Goroutine 89 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select]
  Goroutine 97 - User: /usr/local/go/src/runtime/sys_linux_amd64.s:536 runtime.futex (0x461433) (thread 2665368) [timer goroutine (idle)]
  Goroutine 99 - User: /usr/local/go/src/runtime/proc.go:310 sync.runtime_notifyListWait (0x442ea8) [sync.Cond.Wait 447215h22m47.744818334s]
  Goroutine 100 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:104 k8s.io/client-go/tools/cache.(*controller).Run.func1 (0x18a7df4) [chan receive 447248h42m13.444151565s]
  Goroutine 101 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/reflector.go:355 k8s.io/client-go/tools/cache.(*Reflector).watchHandler (0x18a2fcb) [select 447215h22m47.744839083s]
  Goroutine 168 - User: /go/src/github.com/cilium/cilium/pkg/cleanup/cleanup.go:30 github.com/cilium/cilium/pkg/cleanup.DeferTerminationCleanupFunction.func1 (0xb998e4) [chan receive 447248h42m45.128968211s]
  Goroutine 174 - User: /usr/local/go/src/syscall/asm_linux_amd64.s:53 syscall.Syscall6 (0x47b9fa) (thread 2665312) [select 447223h3m29.735484932s]
  Goroutine 175 - User: /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:250 github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run.func1 (0x1990bdd) [chan receive 447248h42m13.134285401s]
  Goroutine 176 - User: /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:250 github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run.func1 (0x1990bdd) [chan receive 447248h42m13.134296613s]
  Goroutine 179 - User: /go/src/github.com/cilium/cilium/pkg/trigger/trigger.go:218 github.com/cilium/cilium/pkg/trigger.(*Trigger).waiter (0x1a51825) [select]
  Goroutine 180 - User: /go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:536 github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).k8sServiceHandler (0x1c10e66) [chan receive 447215h22m47.744903027s]
  Goroutine 181 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447248h42m42.320867885s]
  Goroutine 182 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447248h42m42.320877233s]
  Goroutine 183 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select]
  Goroutine 186 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447215h19m43.878859758s]
  Goroutine 187 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447248h42m42.320905506s]
  Goroutine 194 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select 447215h19m43.878880728s]
  Goroutine 203 - User: /go/src/github.com/cilium/cilium/pkg/identity/cache/cache.go:152 github.com/cilium/cilium/pkg/identity/cache.(*identityWatcher).watch.func1 (0x19ac578) [select 447222h46m27.375123663s]
  Goroutine 206 - User: /go/src/github.com/cilium/cilium/pkg/datapath/loader/cache.go:308 github.com/cilium/cilium/pkg/datapath/loader.(*objectCache).watchTemplatesDirectory (0x1b9ac5f) [select 447248h42m11.634282065s]
  Goroutine 209 - User: /usr/local/go/src/runtime/sys_linux_amd64.s:536 runtime.futex (0x461433) (thread 2665367) [timer goroutine (idle)]
  Goroutine 214 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select]
  Goroutine 249 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select 447215h22m47.745015476s]
  Goroutine 360 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:104 k8s.io/client-go/tools/cache.(*controller).Run.func1 (0x18a7df4) [chan receive 447248h42m13.444347773s]
  Goroutine 361 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/reflector.go:355 k8s.io/client-go/tools/cache.(*Reflector).watchHandler (0x18a2fcb) [select]
  Goroutine 375 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:104 k8s.io/client-go/tools/cache.(*controller).Run.func1 (0x18a7df4) [chan receive 447248h42m13.444364123s]
  Goroutine 376 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/reflector.go:355 k8s.io/client-go/tools/cache.(*Reflector).watchHandler (0x18a2fcb) [select 447215h22m47.74505433s]
  Goroutine 380 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:104 k8s.io/client-go/tools/cache.(*controller).Run.func1 (0x18a7df4) [chan receive 447248h42m13.444388745s]
  Goroutine 381 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/reflector.go:355 k8s.io/client-go/tools/cache.(*Reflector).watchHandler (0x18a2fcb) [select]
  Goroutine 423 - User: /go/src/github.com/cilium/cilium/pkg/serializer/func_queue.go:58 github.com/cilium/cilium/pkg/serializer.(*FunctionQueue).run (0x1b901ef) [select 447248h42m13.444407028s]
  Goroutine 425 - User: /usr/local/go/src/runtime/proc.go:310 sync.runtime_notifyListWait (0x442ea8) [sync.Cond.Wait 447248h42m13.444414409s]
  Goroutine 426 - User: /go/src/github.com/cilium/cilium/pkg/serializer/func_queue.go:58 github.com/cilium/cilium/pkg/serializer.(*FunctionQueue).run (0x1b901ef) [select 447222h10m59.769179386s]
  Goroutine 428 - User: /usr/local/go/src/runtime/proc.go:310 sync.runtime_notifyListWait (0x442ea8) [sync.Cond.Wait 447222h10m59.769186065s]
  Goroutine 429 - User: /go/src/github.com/cilium/cilium/pkg/serializer/func_queue.go:58 github.com/cilium/cilium/pkg/serializer.(*FunctionQueue).run (0x1b901ef) [select 447215h22m47.745111384s]
  Goroutine 431 - User: /usr/local/go/src/runtime/proc.go:310 sync.runtime_notifyListWait (0x442ea8) [sync.Cond.Wait]
  Goroutine 432 - User: /go/src/github.com/cilium/cilium/pkg/serializer/func_queue.go:58 github.com/cilium/cilium/pkg/serializer.(*FunctionQueue).run (0x1b901ef) [select 447248h42m13.134540652s]
  Goroutine 504 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447248h42m13.444459396s]
  Goroutine 505 - User: /go/src/github.com/cilium/cilium/pkg/monitor/agent/agent.go:100 github.com/cilium/cilium/pkg/monitor/agent.(*Agent).eventDrainer (0x1c3f142) [chan receive]
  Goroutine 506 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select]
  Goroutine 507 - User: /go/src/github.com/cilium/cilium/pkg/ipcache/kvstore.go:218 github.com/cilium/cilium/pkg/ipcache.(*IPIdentityWatcher).Watch (0x19d2b88) [select 447215h37m44.13011641s]
  Goroutine 508 - User: /go/src/github.com/cilium/cilium/pkg/maps/ctmap/gc/gc.go:117 github.com/cilium/cilium/pkg/maps/ctmap/gc.Enable.func1 (0x1ce4e69) [select 447216h53m13.24410288s]
  Goroutine 509 - User: /usr/local/go/src/syscall/asm_linux_amd64.s:53 syscall.Syscall6 (0x47b9fa) (thread 2664264) [GC assist marking 447215h19m43.879108723s]
  Goroutine 511 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select 447215h22m47.745200577s]
  Goroutine 514 - User: /usr/local/go/src/runtime/proc.go:310 sync.runtime_notifyListWait (0x442ea8) [sync.Cond.Wait 447215h22m47.745210316s]
  Goroutine 515 - User: /go/src/github.com/cilium/cilium/pkg/serializer/func_queue.go:58 github.com/cilium/cilium/pkg/serializer.(*FunctionQueue).run (0x1b901ef) [select 447248h42m13.44454225s]
  Goroutine 517 - User: /usr/local/go/src/runtime/proc.go:310 sync.runtime_notifyListWait (0x442ea8) [sync.Cond.Wait 447248h42m13.444556949s]
  Goroutine 518 - User: /go/src/github.com/cilium/cilium/pkg/serializer/func_queue.go:58 github.com/cilium/cilium/pkg/serializer.(*FunctionQueue).run (0x1b901ef) [select 447248h42m12.938175486s]
  Goroutine 519 - User: /go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_node.go:133 github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumNodeInit (0x1c087a3) [chan receive 447248h42m12.938186984s]
  Goroutine 520 - User: /go/src/github.com/cilium/cilium/pkg/serializer/func_queue.go:58 github.com/cilium/cilium/pkg/serializer.(*FunctionQueue).run (0x1b901ef) [select 447248h42m13.134680631s]
  Goroutine 521 - User: /go/src/github.com/cilium/cilium/pkg/k8s/watchers/cilium_endpoint.go:130 github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).ciliumEndpointsInit (0x1c04863) [chan receive 447248h42m12.938211158s]
  Goroutine 522 - User: /go/src/github.com/cilium/cilium/pkg/serializer/func_queue.go:58 github.com/cilium/cilium/pkg/serializer.(*FunctionQueue).run (0x1b901ef) [select 447221h53m58.888006122s]
  Goroutine 524 - User: /go/src/github.com/cilium/cilium/pkg/serializer/func_queue.go:58 github.com/cilium/cilium/pkg/serializer.(*FunctionQueue).run (0x1b901ef) [select 447248h42m13.444624968s]
  Goroutine 525 - User: /usr/local/go/src/runtime/proc.go:310 sync.runtime_notifyListWait (0x442ea8) [sync.Cond.Wait 447222h34m28.84455631s]
  Goroutine 527 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:104 k8s.io/client-go/tools/cache.(*controller).Run.func1 (0x18a7df4) [chan receive 447248h42m13.444647263s]
  Goroutine 528 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/reflector.go:355 k8s.io/client-go/tools/cache.(*Reflector).watchHandler (0x18a2fcb) [select 447215h22m47.745335915s]
  Goroutine 529 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:104 k8s.io/client-go/tools/cache.(*controller).Run.func1 (0x18a7df4) [chan receive 447248h42m13.444665673s]
  Goroutine 530 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/reflector.go:355 k8s.io/client-go/tools/cache.(*Reflector).watchHandler (0x18a2fcb) [select 447215h22m47.745352343s]
  Goroutine 532 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/controller.go:104 k8s.io/client-go/tools/cache.(*controller).Run.func1 (0x18a7df4) [chan receive 447248h42m13.444682424s]
  Goroutine 533 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/reflector.go:355 k8s.io/client-go/tools/cache.(*Reflector).watchHandler (0x18a2fcb) [select 447215h22m47.745366379s]
  Goroutine 562 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/reflector.go:260 k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func2 (0x18a9498) [select 447248h42m13.134790139s]
  Goroutine 565 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select 447215h22m47.745382279s]
  Goroutine 567 - User: /go/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:115 google.golang.org/grpc.(*ccBalancerWrapper).watcher (0x16f10bc) [select 447222h52m15.284315733s]
  Goroutine 571 - User: /go/src/github.com/cilium/cilium/pkg/kvstore/etcd.go:780 github.com/cilium/cilium/pkg/kvstore.connectEtcdClient.func4 (0x1893289) [chan receive 447215h19m43.879315718s]
  Goroutine 572 - User: /go/src/github.com/cilium/cilium/pkg/kvstore/etcd.go:1173 github.com/cilium/cilium/pkg/kvstore.(*etcdClient).statusChecker (0x1882e21) [select]
  Goroutine 573 - User: /go/src/github.com/cilium/cilium/pkg/kvstore/etcd.go:557 github.com/cilium/cilium/pkg/kvstore.(*etcdClient).renewSession (0x187d292) [select 447248h42m12.938339701s]
  Goroutine 574 - User: /go/src/github.com/cilium/cilium/pkg/kvstore/etcd.go:620 github.com/cilium/cilium/pkg/kvstore.(*etcdClient).renewLockSession (0x187da72) [select]
  Goroutine 576 - User: /go/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/clientconn.go:1077 google.golang.org/grpc.(*addrConn).resetTransport (0x16f88fc) [chan receive 447222h52m15.284348461s]
  Goroutine 585 - User: /go/src/github.com/cilium/cilium/pkg/kvstore/allocator/allocator.go:556 github.com/cilium/cilium/pkg/kvstore/allocator.(*kvstoreBackend).ListAndWatch (0x19a6675) [select 447222h46m27.375579695s]
  Goroutine 587 - User: /go/src/github.com/cilium/cilium/pkg/kvstore/etcd.go:1020 github.com/cilium/cilium/pkg/kvstore.(*etcdClient).Watch (0x1881a04) [select 447222h46m27.37558626s]
  Goroutine 589 - User: /go/src/github.com/cilium/cilium/vendor/go.etcd.io/etcd/clientv3/lease.go:330 go.etcd.io/etcd/clientv3.(*lessor).keepAliveCtxCloser (0x18524cf) [select 447248h42m12.93837288s]
  Goroutine 590 - User: /go/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/internal/transport/transport.go:185 google.golang.org/grpc/internal/transport.(*recvBufferReader).readClient (0x16cf183) [select]
  Goroutine 591 - User: /go/src/github.com/cilium/cilium/vendor/go.etcd.io/etcd/clientv3/lease.go:539 go.etcd.io/etcd/clientv3.(*lessor).deadlineLoop (0x18542f7) [select]
  Goroutine 592 - User: /go/src/github.com/cilium/cilium/vendor/go.etcd.io/etcd/clientv3/concurrency/session.go:66 go.etcd.io/etcd/clientv3/concurrency.NewSession.func1 (0x18706ad) [chan receive]
  Goroutine 596 - User: /go/src/github.com/cilium/cilium/pkg/kvstore/etcd.go:1020 github.com/cilium/cilium/pkg/kvstore.(*etcdClient).Watch (0x1881a04) [select 447215h19m43.879396795s]
  Goroutine 598 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/reflector.go:260 k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func2 (0x18a9498) [select 447248h42m12.938415571s]
  Goroutine 599 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select 447215h22m47.745493615s]
  Goroutine 612 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select 447215h22m47.745519932s]
  Goroutine 627 - User: /go/src/github.com/cilium/cilium/pkg/kvstore/etcd.go:1020 github.com/cilium/cilium/pkg/kvstore.(*etcdClient).Watch (0x1881a04) [select 447215h37m44.13048004s]
  Goroutine 636 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select]
  Goroutine 641 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447223h1m29.637012653s]
  Goroutine 642 - User: /go/src/github.com/cilium/cilium/pkg/kvstore/etcd.go:1020 github.com/cilium/cilium/pkg/kvstore.(*etcdClient).Watch (0x1881a04) [select 447216h5m58.799874455s]
  Goroutine 651 - User: /go/src/github.com/cilium/cilium/pkg/allocator/allocator.go:856 github.com/cilium/cilium/pkg/allocator.(*Allocator).startLocalKeySync.func1 (0x199bbe0) [select 447215h22m47.745569527s]
  Goroutine 666 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select]
  Goroutine 670 - User: /usr/local/go/src/runtime/sema.go:56 sync.runtime_Semacquire (0x441af2) [semacquire 447248h42m12.435903374s]
  Goroutine 671 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select 447215h22m47.745596257s]
  Goroutine 679 - User: /usr/local/go/src/context/context.go:259 context.propagateCancel.func1 (0x617d48) [select 447248h42m12.93853799s]
  Goroutine 680 - User: /go/src/github.com/cilium/cilium/vendor/go.etcd.io/etcd/clientv3/watch.go:524 go.etcd.io/etcd/clientv3.(*watchGrpcStream).run (0x18603e1) [select 447215h19m43.879537111s]
  Goroutine 686 - User: /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:592 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).startRegenerationFailureHandler.func1 (0x1a8bd7b) [select 447248h42m12.938555501s]
  Goroutine 687 - User: /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:250 github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run.func1 (0x1990bdd) [chan receive 447222h46m27.375782559s]
  Goroutine 696 - User: /usr/local/go/src/runtime/proc.go:310 time.Sleep (0x44d9e7) [sleep]
  Goroutine 697 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select]
  Goroutine 698 - User: /go/src/github.com/cilium/cilium/pkg/cleanup/cleanup.go:30 github.com/cilium/cilium/pkg/cleanup.DeferTerminationCleanupFunction.func1 (0xb998e4) [chan receive 447248h42m12.645531952s]
  Goroutine 699 - User: /go/src/github.com/cilium/cilium/pkg/status/status.go:152 github.com/cilium/cilium/pkg/status.(*Collector).spawnProbe.func1 (0x1c7feae) [select]
  Goroutine 700 - User: /go/src/github.com/cilium/cilium/pkg/status/status.go:152 github.com/cilium/cilium/pkg/status.(*Collector).spawnProbe.func1 (0x1c7feae) [select]
  Goroutine 701 - User: /go/src/github.com/cilium/cilium/pkg/status/status.go:152 github.com/cilium/cilium/pkg/status.(*Collector).spawnProbe.func1 (0x1c7feae) [select]
  Goroutine 702 - User: /go/src/github.com/cilium/cilium/pkg/status/status.go:152 github.com/cilium/cilium/pkg/status.(*Collector).spawnProbe.func1 (0x1c7feae) [select]
  Goroutine 703 - User: /go/src/github.com/cilium/cilium/pkg/status/status.go:152 github.com/cilium/cilium/pkg/status.(*Collector).spawnProbe.func1 (0x1c7feae) [select]
  Goroutine 704 - User: /go/src/github.com/cilium/cilium/pkg/status/status.go:152 github.com/cilium/cilium/pkg/status.(*Collector).spawnProbe.func1 (0x1c7feae) [select]
  Goroutine 705 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select 447215h22m47.745736561s]
  Goroutine 706 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select 447215h22m47.745748594s]
  Goroutine 712 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447248h42m12.436070914s]
  Goroutine 713 - User: /usr/local/go/src/net/http/transport.go:2210 net/http.(*persistConn).writeLoop (0x78df93) [select 447248h42m12.436081571s]
  Goroutine 721 - User: /go/src/github.com/cilium/cilium/pkg/status/status.go:152 github.com/cilium/cilium/pkg/status.(*Collector).spawnProbe.func1 (0x1c7feae) [select]
  Goroutine 722 - User: /go/src/github.com/cilium/cilium/pkg/status/status.go:152 github.com/cilium/cilium/pkg/status.(*Collector).spawnProbe.func1 (0x1c7feae) [select]
  Goroutine 723 - User: /go/src/github.com/cilium/cilium/pkg/status/status.go:152 github.com/cilium/cilium/pkg/status.(*Collector).spawnProbe.func1 (0x1c7feae) [select]
  Goroutine 724 - User: /go/src/github.com/cilium/cilium/pkg/status/status.go:152 github.com/cilium/cilium/pkg/status.(*Collector).spawnProbe.func1 (0x1c7feae) [select]
  Goroutine 725 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447215h19m43.879737429s]
  Goroutine 726 - User: /go/src/github.com/cilium/cilium/api/v1/server/server.go:498 github.com/cilium/cilium/api/v1/server.handleInterrupt.func1 (0x1ca78f8) [chan receive 447248h42m12.436145396s]
  Goroutine 727 - User: /go/src/github.com/cilium/cilium/api/v1/server/server.go:422 github.com/cilium/cilium/api/v1/server.(*Server).handleShutdown (0x1ca44a3) [chan receive 447248h42m12.43615266s]
  Goroutine 728 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 730 - User: /go/src/github.com/cilium/cilium/pkg/health/server/server.go:284 github.com/cilium/cilium/pkg/health/server.(*Server).Serve (0x1ab0393) [chan receive 447248h42m12.43617005s]
  Goroutine 731 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447215h19m43.87978473s]
  Goroutine 732 - User: /usr/local/go/src/runtime/sema.go:56 sync.runtime_Semacquire (0x441af2) [semacquire 447248h41m28.921130869s]
  Goroutine 754 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447248h42m12.436198934s]
  Goroutine 765 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select]
  Goroutine 815 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select 447215h22m47.745905685s]
  Goroutine 1629 - User: /go/src/github.com/cilium/cilium/vendor/github.com/servak/go-fastping/fastping.go:439 github.com/servak/go-fastping.(*Pinger).run (0x1aa2f86) [select]
  Goroutine 1630 - User: /usr/local/go/src/net/http/transport.go:1239 net/http.(*Transport).getConn (0x787b23) [select]
  Goroutine 1631 - User: /go/src/github.com/cilium/cilium/api/v1/health/server/server.go:498 github.com/cilium/cilium/api/v1/health/server.handleInterrupt.func1 (0x1aaae48) [chan receive 447248h41m28.921194517s]
  Goroutine 1632 - User: /go/src/github.com/cilium/cilium/api/v1/health/server/server.go:422 github.com/cilium/cilium/api/v1/health/server.(*Server).handleShutdown (0x1aa9cc3) [chan receive 447248h41m28.921208744s]
  Goroutine 1634 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 1681 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 52286 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/reflector.go:260 k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func2 (0x18a9498) [select 447246h40m6.38766s]
  Goroutine 52512 - User: /go/src/github.com/cilium/cilium/pkg/k8s/client.go:152 github.com/cilium/cilium/pkg/k8s.runHeartbeat.func1 (0x19f6a49) [chan send 447246h40m6.387669882s]
  Goroutine 52856 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/reflector.go:260 k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func2 (0x18a9498) [select 447246h38m32.534631607s]
  Goroutine 52873 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/reflector.go:260 k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func2 (0x18a9498) [select 447246h40m6.387691698s]
  Goroutine 630600 - User: /go/src/github.com/cilium/cilium/vendor/go.etcd.io/etcd/clientv3/watch.go:762 go.etcd.io/etcd/clientv3.(*watchGrpcStream).serveSubstream (0x18620ce) [select 447222h46m27.376172092s]
  Goroutine 630601 - User: /go/src/github.com/cilium/cilium/vendor/go.etcd.io/etcd/clientv3/watch.go:762 go.etcd.io/etcd/clientv3.(*watchGrpcStream).serveSubstream (0x18620ce) [select 447215h37m44.130976885s]
  Goroutine 630602 - User: /go/src/github.com/cilium/cilium/vendor/go.etcd.io/etcd/clientv3/watch.go:762 go.etcd.io/etcd/clientv3.(*watchGrpcStream).serveSubstream (0x18620ce) [select 447215h19m43.879957741s]
  Goroutine 630603 - User: /go/src/github.com/cilium/cilium/vendor/go.etcd.io/etcd/clientv3/watch.go:762 go.etcd.io/etcd/clientv3.(*watchGrpcStream).serveSubstream (0x18620ce) [select 447216h5m58.800363713s]
  Goroutine 630604 - User: /go/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/internal/transport/transport.go:185 google.golang.org/grpc/internal/transport.(*recvBufferReader).readClient (0x16cf183) [select 447215h19m43.87998286s]
  Goroutine 630606 - User: /go/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/internal/transport/http2_client.go:1300 google.golang.org/grpc/internal/transport.(*http2Client).keepalive (0x16c0cd3) [select]
  Goroutine 630607 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 630608 - User: /go/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:395 google.golang.org/grpc/internal/transport.(*controlBuffer).get (0x16b00d2) [select]
  Goroutine 630614 - User: /go/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/stream.go:319 google.golang.org/grpc.newClientStream.func5 (0x1718237) [select 447222h52m15.285031908s]
  Goroutine 630615 - User: /go/src/github.com/cilium/cilium/vendor/go.etcd.io/etcd/clientv3/lease.go:579 go.etcd.io/etcd/clientv3.(*lessor).sendKeepAliveLoop (0x1854722) [select]
  Goroutine 630631 - User: /go/src/github.com/cilium/cilium/vendor/google.golang.org/grpc/stream.go:319 google.golang.org/grpc.newClientStream.func5 (0x1718237) [select 447222h52m15.285044911s]
  Goroutine 798911 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h53m58.489183652s]
  Goroutine 799746 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h51m58.470102087s]
  Goroutine 799939 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h51m58.470107958s]
  Goroutine 801075 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h45m36.091831967s]
  Goroutine 803001 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h38m30.833858956s]
  Goroutine 803031 - User: /go/src/github.com/cilium/cilium/pkg/k8s/client.go:152 github.com/cilium/cilium/pkg/k8s.runHeartbeat.func1 (0x19f6a49) [chan send 447215h38m30.833864873s]
  Goroutine 803308 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447215h22m47.746164191s]
  Goroutine 803309 - User: /usr/local/go/src/net/http/transport.go:2210 net/http.(*persistConn).writeLoop (0x78df93) [select 447215h22m47.746170652s]
  Goroutine 803359 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447215h22m47.74617706s]
  Goroutine 803598 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 803599 - User: /usr/local/go/src/net/http/transport.go:2210 net/http.(*persistConn).writeLoop (0x78df93) [select]
  Goroutine 803704 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 803710 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/reflector.go:260 k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func2 (0x18a9498) [select 447215h38m30.836682045s]
  Goroutine 803801 - User: /go/src/github.com/cilium/cilium/pkg/endpoint/policy.go:592 github.com/cilium/cilium/pkg/endpoint.(*Endpoint).startRegenerationFailureHandler.func1 (0x1a8bd7b) [select 447215h37m44.133948407s]
  Goroutine 803802 - User: /go/src/github.com/cilium/cilium/pkg/eventqueue/eventqueue.go:250 github.com/cilium/cilium/pkg/eventqueue.(*EventQueue).Run.func1 (0x1990bdd) [chan receive 447215h37m44.133995035s]
  Goroutine 803803 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select]
  Goroutine 803805 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select]
  Goroutine 803849 - User: /usr/local/go/src/syscall/asm_linux_amd64.s:53 syscall.Syscall6 (0x47b9fa) (thread 2664256)
  Goroutine 803977 - User: /go/src/github.com/cilium/cilium/pkg/controller/controller.go:262 github.com/cilium/cilium/pkg/controller.(*Controller).runController (0xbc1bb5) [select]
  Goroutine 804301 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h37m44.134369743s]
  Goroutine 804361 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h37m44.134380356s]
  Goroutine 804537 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h37m44.134391235s]
  Goroutine 804547 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h37m44.13440372s]
* Goroutine 804555 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h37m44.134418019s]
  Goroutine 804589 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h37m44.134428926s]
  Goroutine 804607 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h37m44.134438662s]
  Goroutine 804714 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h37m44.134448333s]
  Goroutine 805062 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h34m29.448954068s]
  Goroutine 806193 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h32m27.346232005s]
  Goroutine 807443 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h28m27.312376647s]
  Goroutine 807480 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h28m27.312386319s]
  Goroutine 807544 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h28m27.312398234s]
  Goroutine 807656 - User: /go/src/github.com/cilium/cilium/pkg/k8s/client.go:152 github.com/cilium/cilium/pkg/k8s.runHeartbeat.func1 (0x19f6a49) [chan send 447215h22m47.749560538s]
  Goroutine 807717 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire 447215h22m47.749571013s]
  Goroutine 807822 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 807899 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 807900 - User: /usr/local/go/src/net/http/transport.go:2210 net/http.(*persistConn).writeLoop (0x78df93) [select]
  Goroutine 808072 - User: /usr/local/go/src/runtime/proc.go:310 sync.runtime_notifyListWait (0x442ea8) [sync.Cond.Wait 447215h22m47.749609619s]
  Goroutine 808119 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 808123 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 808152 - User: /usr/local/go/src/runtime/proc.go:310 sync.runtime_notifyListWait (0x442ea8) [sync.Cond.Wait 447215h22m47.749643993s]
  Goroutine 808161 - User: /usr/local/go/src/runtime/proc.go:310 sync.runtime_notifyListWait (0x442ea8) [sync.Cond.Wait]
  Goroutine 808162 - User: /usr/local/go/src/runtime/proc.go:310 sync.runtime_notifyListWait (0x442ea8) [sync.Cond.Wait 447215h22m47.749663002s]
  Goroutine 808232 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447215h22m47.749672633s]
  Goroutine 808235 - User: /usr/local/go/src/runtime/proc.go:310 sync.runtime_notifyListWait (0x442ea8) [sync.Cond.Wait 447215h22m47.749682371s]
  Goroutine 808389 - User: /go/src/github.com/cilium/cilium/vendor/k8s.io/client-go/tools/cache/reflector.go:260 k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func2 (0x18a9498) [select 447215h22m47.74969274s]
  Goroutine 808435 - User: /usr/local/go/src/runtime/proc.go:310 sync.runtime_notifyListWait (0x442ea8) [sync.Cond.Wait 447215h22m47.749702439s]
  Goroutine 809572 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447215h19m43.883633435s]
  Goroutine 809679 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 810149 - User: /usr/local/go/src/runtime/sema.go:71 sync.runtime_SemacquireMutex (0x441c07) [semacquire]
  Goroutine 810150 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447215h19m43.883661949s]
  Goroutine 810180 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 810181 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 810197 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 810198 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447215h19m43.883697092s]
  Goroutine 810203 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 810204 - User: /usr/local/go/src/net/http/transport.go:2210 net/http.(*persistConn).writeLoop (0x78df93) [select]
  Goroutine 810205 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 810232 - User: /usr/local/go/src/net/http/client.go:321 net/http.setRequestCancel.func3 (0x790ecf) [select]
  Goroutine 810233 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait 447215h19m43.883739935s]
  Goroutine 810234 - User: /usr/local/go/src/net/fd_unix.go:129 net.(*netFD).connect.func2 (0x66676a) [select]
  Goroutine 810241 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 810242 - User: /usr/local/go/src/net/http/transport.go:2210 net/http.(*persistConn).writeLoop (0x78df93) [select]
  Goroutine 810258 - User: /usr/local/go/src/runtime/proc.go:310 sync.runtime_notifyListWait (0x442ea8) [sync.Cond.Wait]
  Goroutine 810280 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 810292 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 810293 - User: /usr/local/go/src/net/http/transport.go:2210 net/http.(*persistConn).writeLoop (0x78df93) [select]
  Goroutine 810321 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 810322 - User: /usr/local/go/src/net/http/transport.go:2210 net/http.(*persistConn).writeLoop (0x78df93) [select]
  Goroutine 810377 - User: /usr/local/go/src/runtime/netpoll.go:184 internal/poll.runtime_pollWait (0x42b695) [IO wait]
  Goroutine 810401 - User: /go/src/github.com/cilium/cilium/vendor/go.etcd.io/etcd/clientv3/lease.go:330 go.etcd.io/etcd/clientv3.(*lessor).keepAliveCtxCloser (0x18524cf) [select]
  Goroutine 810402 - User: /go/src/github.com/cilium/cilium/vendor/go.etcd.io/etcd/clientv3/concurrency/session.go:66 go.etcd.io/etcd/clientv3/concurrency.NewSession.func1 (0x18706ad) [chan receive]
[234 goroutines]
```

**Comment by nr17** [comment]
More updates:

The root cause is that there is a goroutine which have locked linuxNodeHandler.mutex while the second goroutine wants to acquire it:
```
Goroutine 98 - User: /usr/local/go/src/syscall/asm_linux_amd64.s:53 syscall.Syscall6 (0x47b9fa) (thread 21877) [select 447760h17m52.429242149s]
	 0  0x000000000047b9fa in syscall.Syscall6
	     at /usr/local/go/src/syscall/asm_linux_amd64.s:53
	 1  0x00000000007ea4b3 in golang.org/x/sys/unix.recvfrom
	     at /go/src/github.com/cilium/cilium/vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go:2291
	 2  0x00000000007e84b4 in golang.org/x/sys/unix.Recvfrom
	     at /go/src/github.com/cilium/cilium/vendor/golang.org/x/sys/unix/syscall_unix.go:307
	 3  0x0000000000b014db in github.com/vishvananda/netlink/nl.(*NetlinkSocket).Receive
	     at /go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:632
	 4  0x0000000000b009fc in github.com/vishvananda/netlink/nl.(*NetlinkRequest).Execute
	     at /go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/nl/nl_linux.go:425
	 5  0x0000000000b4c883 in github.com/vishvananda/netlink.neighHandle
	     at /go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/neigh_linux.go:185
	 6  0x0000000000b4c2d4 in github.com/vishvananda/netlink.(*Handle).neighAdd
	     at /go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/neigh_linux.go:120
	 7  0x0000000001cd6ef5 in github.com/vishvananda/netlink.(*Handle).NeighSet
	     at /go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/neigh_linux.go:95
	 8  0x0000000001cd6ef5 in github.com/vishvananda/netlink.NeighSet
	     at /go/src/github.com/cilium/cilium/vendor/github.com/vishvananda/netlink/neigh_linux.go:89
	 9  0x0000000001cd6ef5 in github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).insertNeighbor
	     at /go/src/github.com/cilium/cilium/pkg/datapath/linux/node.go:609
	10  0x0000000001cd872f in github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).nodeUpdate
	     at /go/src/github.com/cilium/cilium/pkg/datapath/linux/node.go:720
```
The above goroutine is blocked on receiving the response from the netlink socket after executing neighAdd logic.

Later the following goroutine tries to acquire the linuxNodeHandler.mutex and gets blocked after getting a node update event from the KV store:

```
(dlv) bt
 0  0x0000000000431300 in runtime.gopark
    at /usr/local/go/src/runtime/proc.go:305
 1  0x0000000000441ea0 in runtime.goparkunlock
    at /usr/local/go/src/runtime/proc.go:310
 2  0x0000000000441ea0 in runtime.semacquire1
    at /usr/local/go/src/runtime/sema.go:144
 3  0x0000000000441c07 in sync.runtime_SemacquireMutex
    at /usr/local/go/src/runtime/sema.go:71
 4  0x000000000046db5c in sync.(*Mutex).lockSlow
    at /usr/local/go/src/sync/mutex.go:138
 5  0x0000000001cd470d in sync.(*Mutex).Lock
    at /usr/local/go/src/sync/mutex.go:81
 6  0x0000000001cd470d in github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).NodeUpdate
    at /go/src/github.com/cilium/cilium/pkg/datapath/linux/node.go:429
 7  0x0000000001ac2dbe in github.com/cilium/cilium/pkg/node/manager.(*Manager).NodeUpdated.func1
    at /go/src/github.com/cilium/cilium/pkg/node/manager/manager.go:378
 8  0x0000000001abf8c7 in github.com/cilium/cilium/pkg/node/manager.(*Manager).Iter
    at /go/src/github.com/cilium/cilium/pkg/node/manager/manager.go:149
 9  0x0000000001ac0fae in github.com/cilium/cilium/pkg/node/manager.(*Manager).NodeUpdated
    at /go/src/github.com/cilium/cilium/pkg/node/manager/manager.go:377
10  0x0000000001ac3319 in github.com/cilium/cilium/pkg/node/store.(*NodeObserver).OnUpdate
    at /go/src/github.com/cilium/cilium/pkg/node/store/store.go:62
11  0x0000000001899792 in github.com/cilium/cilium/pkg/kvstore/store.(*SharedStore).onUpdate
    at /go/src/github.com/cilium/cilium/pkg/kvstore/store/store.go:236
12  0x0000000001899792 in github.com/cilium/cilium/pkg/kvstore/store.(*SharedStore).updateKey
    at /go/src/github.com/cilium/cilium/pkg/kvstore/store/store.go:447
13  0x000000000189a5b2 in github.com/cilium/cilium/pkg/kvstore/store.(*SharedStore).watcher
    at /go/src/github.com/cilium/cilium/pkg/kvstore/store/store.go:515
14  0x000000000045f501 in runtime.goexit
    at /usr/local/go/src/runtime/asm_amd64.s:1357
```

This locks the mutex for one of the nodes entry in the pkg/node/manager/manager.go map for nodes. This leads to the condition described at https://github.com/cilium/cilium/issues/14746#issuecomment-768117930

**Comment by nr17** [comment]
NetLink Request contents for netlink.(*Handle).neighAdd:
(dlv) print req
*github.com/vishvananda/netlink/nl.NetlinkRequest {
	NlMsghdr: golang.org/x/sys/unix.NlMsghdr {Len: 48, Type: 28, Flags: 1285, Seq: 2599, Pid: 0},
	Data: []github.com/vishvananda/netlink/nl.NetlinkRequestData len: 3, cap: 4, [
		...,
		...,
		...,
	],
	RawData: []uint8 len: 0, cap: 0, nil,
	Sockets: map[int]*github.com/vishvananda/netlink/nl.SocketHandle nil,}
(dlv) p req.Data
[]github.com/vishvananda/netlink/nl.NetlinkRequestData len: 3, cap: 4, [
	*github.com/vishvananda/netlink.Ndmsg {Family: 2, Index: 2, State: 128, Flags: 0, Type: 0},
	*github.com/vishvananda/netlink/nl.RtAttr {
		RtAttr: (*"golang.org/x/sys/unix.RtAttr")(0xc0022ddb40),
		Data: []uint8 len: 4, cap: 4, [10,93,161,188],
		children: []github.com/vishvananda/netlink/nl.NetlinkRequestData len: 0, cap: 0, [],},
	*github.com/vishvananda/netlink/nl.RtAttr {
		RtAttr: (*"golang.org/x/sys/unix.RtAttr")(0xc0022ddb80),
		Data: []uint8 len: 6, cap: 106, [18,144,211,109,214,137],
		children: []github.com/vishvananda/netlink/nl.NetlinkRequestData len: 0, cap: 0, [],},
]
(dlv) p req.RawData
[]uint8 len: 0, cap: 0, nil

**Comment by nr17** [comment]
Looks like disabling node-port disables NeighDiscovery, and avoids this condition to happen.

So possible work-arounds are:
1. Disable node-port
2. Install cilium in kube-proxy replacement mode (requires us to use kops 1.18+)

Can somebody confirm?

**Comment by nr17** [comment]
These issues are related and might provide a work-arround:
https://github.com/vishvananda/netlink/issues/613
https://github.com/cilium/cilium/issues/14710
https://github.com/vishvananda/netlink/pull/614/files

**Comment by johngmyers** [comment]
Even with using a version of netlink with a default timeout, we're seeing Cilium agent block on a linuxNodeHandler.mutex with the holder of the mutex waiting on input from the netlink socket.

We're currently working on extending the Cilium agent's liveness probe so that it fails when one of those mutexes is held for a long time.

**Comment by brb** [comment]
This issue should be resolved by https://github.com/cilium/cilium/issues/14710.

> Even with using a version of netlink with a default timeout

@johngmyers Are you refering to https://github.com/vishvananda/netlink/pull/614? Could you provide a stacktrace of the goroutine? /cc @ArthurChiao

**Comment by Ewocker** [comment]
@brb Here is the stacktrace of the goroutine that got stuck using a forked cilium 1.7.13 with the patch vishvananda/netlink#614 applied 
```
  Goroutine 138 - User: /usr/local/go/src/syscall/asm_linux_amd64.s:53 syscall.Syscall6 (0x47b9fa) (thread 137468) [select 448062h10m14.804349352s]
	 0  0x000000000047b9fa in syscall.Syscall6
	     at /usr/local/go/src/syscall/asm_linux_amd64.s:53
	 1  0x000000000047b1e3 in syscall.recvfrom
	     at /usr/local/go/src/syscall/zsyscall_linux_amd64.go:1618
	 2  0x00000000004774ef in syscall.Recvfrom
	     at /usr/local/go/src/syscall/syscall_unix.go:273
	 3  0x0000000000473b6c in syscall.NetlinkRIB
	     at /usr/local/go/src/syscall/netlink_linux.go:71
	 4  0x0000000000642aa8 in net.interfaceTable
	     at /usr/local/go/src/net/interface_linux.go:17
	 5  0x0000000000641c24 in net.InterfaceByName
	     at /usr/local/go/src/net/interface.go:157
	 6  0x0000000001cda652 in github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).insertNeighbor
	     at /go/src/github.com/cilium/cilium/pkg/datapath/linux/node.go:601
	 7  0x0000000001cdc300 in github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).nodeUpdate
	     at /go/src/github.com/cilium/cilium/pkg/datapath/linux/node.go:741
	 8  0x0000000001ce0b96 in github.com/cilium/cilium/pkg/datapath/linux.(*linuxNodeHandler).NodeValidateImplementation
	     at /go/src/github.com/cilium/cilium/pkg/datapath/linux/node.go:1204
	 9  0x0000000001ac9b4a in github.com/cilium/cilium/pkg/node/manager.(*Manager).backgroundSync.func1
	     at /go/src/github.com/cilium/cilium/pkg/node/manager/manager.go:282
	10  0x0000000001ac6787 in github.com/cilium/cilium/pkg/node/manager.(*Manager).Iter
	     at /go/src/github.com/cilium/cilium/pkg/node/manager/manager.go:149
	(truncated)
```
The lock call happens in NodeValidateImplementation and never returns. I believe vishvananda/netlink#614 do not solve issue such as above where func not returning is not using vishvananda's netlink package.

**Comment by ArthurChiao** [comment]
https://github.com/cilium/cilium/blob/v1.7.13/pkg/datapath/linux/node.go#L591, as pointed out by @Ewocker and shown in the above stack strace, Cilium **`1.7.13`** is using vanilla `net` package instead of `vishvananda/netlink`, so https://github.com/vishvananda/netlink/pull/614 doesn't solve the above case.

**Comment by brb** [comment]
This has been fixed in 1.{8,9,10}. Closing the issue.
