### ISSUE TITLE
Service/backend ID pool is not scaling with bpf lb map size

### ISSUE THREAD

**Issue by Weil0ng** [cilium/cilium#16121]
## Bug report

In large scale use cases (>64k k8s endpoints), Cilium would complain the following first when backend number grows over 64k:
```
level=error msg="Error while inserting service in LB map" error="Unable to acquire backend ID for {\"10.74.184.36\" {\"TCP\" 'P'} '\\x00'}: no service ID available" k8sNamespace=test-zqygrq-14 k8sSvcName=small-service-9 subsys=k8s-watcher
```

then later if the same backend is touched, it'll crash with the following stacktrace:
```
"panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x20892d2]
goroutine 143 [running]:
github.com/cilium/cilium/pkg/service.(*Service).updateBackendsCacheLocked(0xc0001e1980, 0xc0017947e0, 0xc02b778c80, 0x3, 0x4, 0xc02b778c80, 0x2, 0x4, 0x0, 0x5577bfe1634237c4, ...)
	/go/src/github.com/cilium/cilium/pkg/service/service.go:943 +0x912
github.com/cilium/cilium/pkg/service.(*Service).UpsertService(0xc0001e1980, 0xc025cca840, 0x0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/service/service.go:305 +0xb16
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).addK8sSVCs(0xc0009ef040, 0xc02797b120, 0x10, 0xc02797b100, 0xe, 0x0, 0xc00aa4c3f0, 0xc01b9243f0, 0x0, 0x0)
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:769 +0x47b
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).k8sServiceHandler.func1(0x0, 0xc02797b120, 0x10, 0xc02797b100, 0xe, 0xc00aa4c3f0, 0x0, 0xc01b9243f0, 0xc000b39fb0)
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:473 +0xa76
github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).k8sServiceHandler(0xc0009ef040)
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:516 +0x95
created by github.com/cilium/cilium/pkg/k8s/watchers.(*K8sWatcher).RunK8sServiceHandler
	/go/src/github.com/cilium/cilium/pkg/k8s/watchers/watcher.go:521 +0x3f
```

Discussed offline with @aanm and @brb , issue seems to be the MaxID const defined in https://github.com/cilium/cilium/blob/ffe0d11b398e85d7860fefd71c2a38a252405059/pkg/service/const.go limits how many services/backends can be stored regardless of `bpf-lb-map-size`.

Reason for this hard limit in control plane is that datapath is using `u16` as type for backend ID, there's proposal that relaxes this limit (https://github.com/cilium/cilium/issues/16110).

**General Information**

- Cilium version (run `cilium version`): 1.9.5
- Orchestration system version in use (e.g. `kubectl version`, ...): 1.20.6

**How to reproduce the issue**

1. Install Cilium with `bpf-lb-map-size` set to >64k.
2. Create services that total the number of backends to be >64k.

**Comment by aanm** [comment]
Still, the panic should be fixed as the code clearly has a bug:
```golang
if found := svc.backendByHash[hash]; !found {
	if s.backendRefCount.Add(hash) {
		id, err := AcquireBackendID(backend.L3n4Addr)
		if err != nil {
			return nil, nil, nil, fmt.Errorf("Unable to acquire backend ID for %q: %s",
				backend.L3n4Addr, err)
		}
		backends[i].ID = id
		newBackends = append(newBackends, backends[i])
		// TODO make backendByHash by value not by ref
		s.backendByHash[hash] = &backends[i]
	} else {
// ----> we are in the !found branch, so 's.backendByHash[hash]' is nil
		backends[i].ID = s.backendByHash[hash].ID
	}
}
```

**Comment by Weil0ng** [comment]
Discussed with @aanm offline, using this [patch](https://gist.github.com/Weil0ng/398f7067a2c2886d580fcf66e84dd069), along with setting `bpf-lb-max-size` to >64k, it seems like the panic is gone, but in the pod deletion phase, agent is full of the following error:
```
level=warning msg="Failed to remove backend from maps" backendID=4019 error="Unable to delete backend 4019 (false): unable to delete element 4019 from map cilium_lb4_backends: no such file or directory" subsys=service
```

Checking in the node, it seems like `cilium_lb4_backends` is somehow empty, see [screenshot](https://files.slack.com/files-pri/T1MATJ4SZ-F021T7V7TJ9/screen_shot_2021-05-13_at_5.28.45_pm.png).

Clearly there's still some gap, trying to reproduce this in a smaller setup by reducing `bpf-lb-max-size` and the const `MaxID` in `pkg/service/const.go`...

**Comment by brb** [comment]
@Weil0ng Thanks for the issue. Are you going to work on the fix pointed by @aanm ?

**Comment by Weil0ng** [comment]
> @Weil0ng Thanks for the issue. Are you going to work on the fix pointed by @aanm ?

The patch that I shared (adopted from your PR, changes the data type from u16 to u32) doesn't really solve the issue (see my previous comment), I am looking at reproduce the above "Failed to remove backend" issue with a smaller setup to debug it, but have no success now, might need some help on this...If you have an idea why that might happen, I'm all ears :)
