### ISSUE TITLE
bpf: cilium-map-migrate might unpin in-use tailcall map

### ISSUE THREAD

**Issue by brb** [cilium/cilium#16561]
After adding a new taill call to e.g. `CILIUM_MAP_CALL` (as it's been done in https://github.com/cilium/cilium/pull/14138/files) and then upgrading Cilium, there will be a small window when packets will be dropped due to `DROP_MISSED_TAIL_CALL`.

When we load e.g. bpf_host on a native device (e.g. eth0), the following is executed by the cilium-agent:
```
$ cilium-map-migrate -s 42/bpf_netdev_eth0.o
$ tc filter replace dev eth0 ingress prio 1 handle 1 bpf da obj 42/bpf_netdev_eth0.o sec from-netdev
$ cilium-map-migrate -e 42/bpf_netdev_eth0.o -r 0

$ cilium-map-migrate -s 42/bpf_netdev_eth0.o
# renames /sys/fs/bpf/tc/globals/cilium_calls_netdev_00666{,:pending} <-- it's being used by bpf_netdev_eth0[from-netdev]@eth0[ingress]
$ tc filter replace dev eth0 egress prio 1 handle 1 bpf da obj 42/bpf_netdev_eth0.o sec to-netdev
# creates /sys/fs/bpf/tc/globals/cilium_calls_netdev_00666 <-- it's being used by bpf_netdev_eth0[to-netdev]@eth0[egress]
$ cilium-map-migrate -e 42/bpf_netdev_eth0.o -r 0
# deletes /sys/fs/bpf/tc/globals/cilium_calls_netdev_00666:pending (used by bpf_netdev_eth0[from-netdev])
```

Because BPF maps of the `BPF_MAP_TYPE_PROG_ARRAY` type are removed immediately once they are unpinned (regardless of the refcount), we get the missed tail calls on the ingress of eth0.

This became obvious after analyzing test failures in the PR https://github.com/cilium/cilium/pull/13032#issuecomment-861531511.

**Comment by ti-mo** [comment]
Thanks for the issue! This is definitely something that should stay on the radar. As far as I understand, prog arrays that can no longer be referenced from user space (or get close()d) are _cleared_, not deleted, resulting in missed tail calls. Unpinning a map won't necessarily clear it as long as it still has any open fds, but within the context of upgrading Cilium, that's more or less the same thing, as userspace exits anyway.

It's not explicitly mentioned in the issue description, but in conclusion, we should never unpin prog arrays during migrations if the new version of a prog_array has a different flags or max_entries (since k/v size for prog arrays is fixed).

How should we handle cleanup, though? With moving more and more BPF stuff to Go, we'll have more flexibility for executing loader logic in between prog attaches, etc. For `bpf_host` we'd simply unpin the old prog array after loading and attaching the new `bpf_host`.

But what about bpf_lxc, aren't there tail calls there too? We If we move prog arrays out of the way during upgrades as necessary, e.g. by suffixing a random identifier to the pin path, they could theoretically pile up if the agent is continually up/downgraded. I don't know if there's a  way to obtain a map's refcount, so we lack a cleanup heuristic. This might be something we'd have to live with, though. Prog arrays are among the smallest we have, so no big deal.

**Comment by brb** [comment]
> As far as I understand, prog arrays that can no longer be referenced from user space (or get close()d) are cleared, not deleted, resulting in missed tail calls.

The prog arrays are immediately deleted regardless of their refcount once they have been unpinned. This complicates the issue a lot.

> How should we handle cleanup, though? 

My thinking was to defer to removal (i.e., calling `cilium-map-migrate -r`) once we are done with the datapath reloading. But...

> But what about bpf_lxc, aren't there tail calls there too?

^^ won't work with bpf_lxc, as they might be reloaded on the fly. So maybe we should keep a refcount in the agent, and once it's =0, remove the map?

**Comment by ti-mo** [comment]
As discussed this morning:

- no stateful refcounting is necessary, this would also be kinda fragile
- prog info contains a list of map ids referenced in the program (as seen in `bpftool prog` output: `map_ids 121,135,118,129,119`), or at least it can be obtained from a prog's xlated instructions
- during map migration start, prog arrays can be renamed `:pending` like all other maps (no danger)
- during map migration finish, before `Unpin()`ing any `:pending` prog arrays:  scan all progs in the kernel for references to the prog array
- if any references are found in progs, move the prog array pin out of the way by affixing a random identifier

We should probably ignore the map pin from then on out, because:
- Scanning all progs for references is expensive, at least one syscall per prog in the kernel. We don't want to repeat this scan on every pod start..
- Prog array entries don't count as real prog references, so no risk of leaking progs
- Tail call maps are relatively small (and their size is bounded), so negligible memory overhead
- Prog array migration only happens on Cilium up/downgrade, which is not supposed to happen all too frequently

**Comment by brb** [comment]
No v1.11 feature depends on this, so no longer the blocker.

**Comment by pchaigno** [comment]
Reopening given https://github.com/cilium/cilium/pull/17744 didn't fix it.
