### ISSUE TITLE
bpf.lbExternalClusterIP=true doesn't work with Maglev when requested from outside cluster

### ISSUE THREAD

**Issue by gpl** [cilium/cilium#16966]
## Bug report

**General Information**

- Cilium version (run `cilium version`)
1.10.3
- Kernel version (run `uname -a`)
5.10.40
- Orchestration system version in use (e.g. `kubectl version`, ...)
kubeadm
- Link to relevant artifacts (policies, deployments scripts, ...)
```
    --set k8sServiceHost="<>" \
    --set k8sServicePort=6443 \
    --set hostServices.enabled=true \
    --set hubble.listenAddress=":4244" \
    --set hubble.relay.enabled=true \
    --set hubble.ui.enabled=true \
    --set externalIPs.enabled=true \
    --set ipam.operator.clusterPoolIPv4PodCIDR="10.192.0.0/12" \
    --set ipam.operator.clusterPoolIPv4MaskSize="22" \
    --set ipam.operator.clusterPoolIPv6PodCIDR="<>" \
    --set ipam.operator.clusterPoolIPv6MaskSize="64" \
    --set ipMasqAgent.enabled=true \
    --set ipv6.enabled=true \
    --set kubeProxyReplacement=strict \
    --set kubeProxyReplacementHealthzBindAddr="[::]:10256" \
    --set maglev.tableSize=65521 \
    --set maglev.hashSeed="<>"  \
    --set nativeRoutingCIDR="10.192.0.0/12" \
    --set loadBalancer.algorithm=maglev \
    --set loadBalancer.mode=hybrid \
    --set nodePort.enabled=true \
    --set prometheus.enabled=true \
    --set tunnel=disabled \
    --set autoDirectNodeRoutes=false \
    --set externalWorkloads.enabled=true \
    --set containerRuntime.integration=containerd \
    --set cni.exclusive=false \
    --set bpf.lbExternalClusterIP=true \
    --set bpf.masquerade=true \
    --set egressGateway.enabled=true \
    --set bpf.mapDynamicSizeRatio=.0050 \
    --set prometheus.enabled=true \
    --set prometheus.port=19380
```

- Generate and upload a system zip:
```
 available on request
```

**How to reproduce the issue**

1. Enable bpf.lb.ExternalClusterIP=true
2. Attempt to access a ServiceIP hosted by kubeproxyreplacement 
3. See the following messages when attempting to connect:
xx drop (Service backend not found) flow 0xf6c2b1f8 to endpoint 0, identity 16777249->unknown: <client-ip-here>:62561 -> 10.217.142.187:80 tcp SYN

cilium bpf lb list shows a backend

10.217.142.187:80                               10.192.21.46:8080 (65)                            
                                                0.0.0.0:0 (65) [ClusterIP] 

The externalIPs service seems to be identical, and is reachable&routable:
<>.  :80                                 10.192.21.46:8080 (66)                            
                                                0.0.0.0:0 (66) [ExternalIPs]

**Comment by brb** [comment]
@gpl Thanks for the issue. The problem is that the Maglev table is not populated for the ClusterIP service. If you disable the Maglev feature, then it should work. Anyway, we are going to fix it.

**Comment by gpl** [comment]
Just an update, we recently updated to Cilium 1.11 and are still experiencing this issue.

**Comment by adamcharnock** [comment]
I'm also encountering this issue. It presents slightly differently on both `0.10.6` and `0.11.0`:

<details>
  <summary>Configuration</summary>
  
  ```yaml
cilium:
  image:
    repository: cilium/cilium
    tag: v1.10.6   # Or v0.11.0, as per description
  operator:
    repository: cilium/operator
    tag: v1.10.6   # Or v0.11.0, as per description
  preflight:
    repository: cilium/cilium
    tag: v1.10.6   # Or v0.11.0, as per description

  #policyEnforcementMode: always
  policyEnforcementMode: never

  kubeProxyReplacement: "strict"
  k8sServiceHost: "{{ master_ipv6_address }}"
  k8sServicePort: 6443

  ipv6:
    enabled: true

  encryption:
    enabled: false

  l7Proxy: false

  # Native routing for us
  tunnel: disabled
  nativeRoutingCIDR: {{ internal_ipv4 }}
  # For cilium 1.11
  ipv4NativeRoutingCIDR: {{ internal_ipv4 }}

  # Provided by edge router for egress traffic to internet
  enableIPv4Masquerade: false
  enableIPv6Masquerade: false

  bpf:
    # We want to be able to access services from outside the cluster
    lbExternalClusterIP: true

  ipam:
    mode: cluster-pool
    clusterPoolIPv4PodCIDR:: "{{ cluster_cidr_ipv6 }}"
    clusterPoolIPv4MaskSize: 26
    clusterPoolIPv6PodCIDR: "{{ cluster_cidr_ipv6 }}"
    clusterPoolIPv6MaskSize: 82

  # Uncommenting causes the issue
  #loadBalancer:
  #  mode: dsr

  hostServices:
    enabled: true

  hubble:
    relay:
      enabled: yes
    ui:
      enabled: yes

  ```
</details>

## 0.10.6 with DSR enabled

* I can access Service CIDR IPs from the cluster nodes
* I cannot access Service CIDR IPs externally to the cluster. Disabling DSR resolves this issue

## 0.11.0 with DSR enabled

* I cannot access Service CIDR IPs from the cluster nodes. Disabling DSR resolves this issue
* I cannot access Service CIDR IPs externally to the cluster. Disabling DSR resolves this issue

**Comment by brb** [comment]
@adamcharnock Could you create a separate issue? This one is for Maglev, while your is when DSR is enabled (the root cause should be different). Also, please attach the sysdump.

**Comment by gpl** [comment]
just noting here, likely to be fixed by #18336

**Comment by gpl** [comment]
Re-opening as it looks like the issue still persists with quay.io/cilium/cilium-ci:v1.11

```
Client: 1.11.1 38d77d4 2022-02-11T14:36:28+00:00 go version go1.17.6 linux/amd64
Daemon: 1.11.1 38d77d4 2022-02-11T14:36:28+00:00 go version go1.17.6 linux/amd64
```

**Comment by brb** [comment]
@gpl This got fixed by https://github.com/cilium/cilium/pull/18336 which hasn't been released yet.

**Comment by gpl** [comment]
> @gpl This got fixed by #18336 which hasn't been released yet.

We pulled the latest image from quay.io/cilium/cilium-ci:v1.11 a few days ago, which had commit # 38d77d4 -- would the patch #18336 not be included there?

**Comment by brb** [comment]
The PR wasn't backported to the v1.11, so it should not have the fix. You could try `:latest` instead.

**Comment by gpl** [comment]
Thank you for your reply -- we just attempted quay.io/cilium/cilium-ci:latest (I think cilium-ci:f08dda3df84f) but we are still seeing the same issue, `Service backend not found`.

**Comment by brb** [comment]
It works. Tried running the latest master image (built with `make dev-docker-image`). Also, we have the CI suite which checks that too - https://github.com/cilium/cilium/blob/master/test/k8sT/Services.go#L746. Please check whether the service has backends.

**Comment by gpl** [comment]
Thank you for the clarification -- it looks like locally building the image did the trick.
