### ISSUE TITLE
Getting Started with Vagrant is not working

### ISSUE THREAD

**Issue by gianarb** [cilium/cilium#174]
Hello 

I am following the getting started with Vagrant 

``` bash
21:04 $ vagrant -v
Vagrant 1.8.5
```

``` bash
21:06 $ VBoxManage --version
4.3.38r106717
```

With the command

``` bash
git clone git@github.com:cilium/cilium.git ~/cilium-test
cd cilium-test
NUM_NODES=1 ./contrib/vagrant/staht.sh
```

The master is good but the node is failing 

``` bash
==> cilium-node-2: ls -d ./* | grep -vE Makefile | xargs rm -rf
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/docker'
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-node-2: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-node-2: go build -ldflags "-X "github.com/cilium/cilium/common".Version=0.1.0.dev" -o cilium-docker
==> cilium-node-2: # github.com/cilium/cilium/plugins/cilium-docker
==> cilium-node-2: compile: reading input: EOF
==> cilium-node-2: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-node-2: make[2]: *** [cilium-docker] Error 2
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-node-2: make[1]: *** [cilium-docker] Error 2
==> cilium-node-2: make: *** [plugins] Error 2
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

What am I doing wrong?
Thanks

**Comment by mchalla** [comment]
Could you pl run vagrant with VAGRANT_LOG=debug and paste the output.

**Comment by mchalla** [comment]
Actually never mind. I thought it was an ssh issue. Looks like a compile issue. I will look at it in some time.

**Comment by mchalla** [comment]
A quick thing you can do is vagrant ssh to each node and compare the /home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker directory. May be the download failed for some reason. 

Do you see the issue each time consistently ? you can do a vagrant destroy and run the start.sh command again.

**Comment by gianarb** [comment]
Hello @mchalla yes I can see that error every time . Anyway I notified but I hope to have time to deep on it more

**Comment by tgraf** [comment]
@gianarb It looks like a file in your directory is corrupted. Either from the git clone directly or during the rsync when copying into the VM. I'd try by destroying the vagrant box and set up again and in case that doesn't work, clone a fresh copy of the git tree.

**Comment by aanm** [comment]
Yep, @tgraf is probably right. Please try it again, I've try it and it works fine. This is the full log:

```
[aanm@aanm-MBP cilium-issue]$ git clone https://www.github.com/cilium/cilium.git
Cloning into 'cilium'...
remote: Counting objects: 17734, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 17734 (delta 9), reused 0 (delta 0), pack-reused 17707
Receiving objects: 100% (17734/17734), 14.21 MiB | 1.45 MiB/s, done.
Resolving deltas: 100% (10120/10120), done.
Checking connectivity... done.
[aanm@aanm-MBP cilium]$ NUM_NODES=1 ./contrib/vagrant/start.sh
Bringing machine 'cilium-master' up with 'virtualbox' provider...
Bringing machine 'cilium-node-2' up with 'virtualbox' provider...
==> cilium-master: Importing base box 'noironetworks/net-next'...
==> cilium-master: Matching MAC address for NAT networking...
==> cilium-master: Setting the name of the VM: cilium_cilium-master_1477001293770_87290
==> cilium-master: Clearing any previously set network interfaces...
==> cilium-master: Preparing network interfaces based on configuration...
    cilium-master: Adapter 1: nat
    cilium-master: Adapter 2: intnet
==> cilium-master: Forwarding ports...
    cilium-master: 22 (guest) => 2222 (host) (adapter 1)
==> cilium-master: Running 'pre-boot' VM customizations...
==> cilium-master: Booting VM...
==> cilium-master: Waiting for machine to boot. This may take a few minutes...
    cilium-master: SSH address: 127.0.0.1:2222
    cilium-master: SSH username: vagrant
    cilium-master: SSH auth method: private key
    cilium-master: 
    cilium-master: Vagrant insecure key detected. Vagrant will automatically replace
    cilium-master: this with a newly generated keypair for better security.
    cilium-master: 
    cilium-master: Inserting generated public key within guest...
    cilium-master: Removing insecure key from the guest if it's present...
    cilium-master: Key inserted! Disconnecting and reconnecting using new SSH key...
==> cilium-master: Machine booted and ready!
==> cilium-master: Checking for guest additions in VM...
    cilium-master: No guest additions were detected on the base box for this VM! Guest
    cilium-master: additions are required for forwarded ports, shared folders, host only
    cilium-master: networking, and more. If SSH fails on this machine, please install
    cilium-master: the guest additions and repackage the box to continue.
    cilium-master: 
    cilium-master: This is not an error message; everything may continue to work properly,
    cilium-master: in which case you may ignore this message.
==> cilium-master: Setting hostname...
==> cilium-master: Configuring and enabling network interfaces...
==> cilium-master: Rsyncing folder: /home/aanm/temp/cilium-issue/cilium/ => /home/vagrant/go/src/github.com/cilium/cilium
==> cilium-master: Running provisioner: bootstrap (shell)...
    cilium-master: Running: inline script
==> cilium-master: stdin: is not a tty
==> cilium-master: Reading package lists...
==> cilium-master: Building dependency tree...
==> cilium-master: 
==> cilium-master: Reading state information...
==> cilium-master: The following extra packages will be installed:
==> cilium-master:   libcurl3 libevent-2.0-5
==> cilium-master: Suggested packages:
==> cilium-master:   doc-base
==> cilium-master: The following NEW packages will be installed:
==> cilium-master:   curl jq libcurl3 libevent-2.0-5 pv realpath socat tmux
==> cilium-master: 0 upgraded, 8 newly installed, 0 to remove and 77 not upgraded.
==> cilium-master: Need to get 1,118 kB of archives.
==> cilium-master: After this operation, 3,238 kB of additional disk space will be used.
==> cilium-master: Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main libcurl3 amd64 7.35.0-1ubuntu2.9 [173 kB]
==> cilium-master: Get:2 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main libevent-2.0-5 amd64 2.0.21-stable-1ubuntu1.14.04.1 [126 kB]
==> cilium-master: Get:3 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main curl amd64 7.35.0-1ubuntu2.9 [123 kB]
==> cilium-master: Get:4 http://us.archive.ubuntu.com/ubuntu/ trusty/universe jq amd64 1.3-1.1ubuntu1 [97.8 kB]
==> cilium-master: Get:5 http://us.archive.ubuntu.com/ubuntu/ trusty/universe pv amd64 1.2.0-1 [33.7 kB]
==> cilium-master: Get:6 http://us.archive.ubuntu.com/ubuntu/ trusty/main realpath amd64 1.19 [14.5 kB]
==> cilium-master: Get:7 http://us.archive.ubuntu.com/ubuntu/ trusty/main tmux amd64 1.8-5 [247 kB]
==> cilium-master: Get:8 http://us.archive.ubuntu.com/ubuntu/ trusty/universe socat amd64 1.7.2.3-1 [302 kB]
==> cilium-master: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> cilium-master: Fetched 1,118 kB in 2s (413 kB/s)
==> cilium-master: Selecting previously unselected package libcurl3:amd64.
==> cilium-master: (Reading database ... 64974 files and directories currently installed.)
==> cilium-master: Preparing to unpack .../libcurl3_7.35.0-1ubuntu2.9_amd64.deb ...
==> cilium-master: Unpacking libcurl3:amd64 (7.35.0-1ubuntu2.9) ...
==> cilium-master: Selecting previously unselected package libevent-2.0-5:amd64.
==> cilium-master: Preparing to unpack .../libevent-2.0-5_2.0.21-stable-1ubuntu1.14.04.1_amd64.deb ...
==> cilium-master: Unpacking libevent-2.0-5:amd64 (2.0.21-stable-1ubuntu1.14.04.1) ...
==> cilium-master: Selecting previously unselected package curl.
==> cilium-master: Preparing to unpack .../curl_7.35.0-1ubuntu2.9_amd64.deb ...
==> cilium-master: Unpacking curl (7.35.0-1ubuntu2.9) ...
==> cilium-master: Selecting previously unselected package jq.
==> cilium-master: Preparing to unpack .../jq_1.3-1.1ubuntu1_amd64.deb ...
==> cilium-master: Unpacking jq (1.3-1.1ubuntu1) ...
==> cilium-master: Selecting previously unselected package pv.
==> cilium-master: Preparing to unpack .../archives/pv_1.2.0-1_amd64.deb ...
==> cilium-master: Unpacking pv (1.2.0-1) ...
==> cilium-master: Selecting previously unselected package realpath.
==> cilium-master: Preparing to unpack .../realpath_1.19_amd64.deb ...
==> cilium-master: Unpacking realpath (1.19) ...
==> cilium-master: Selecting previously unselected package tmux.
==> cilium-master: Preparing to unpack .../archives/tmux_1.8-5_amd64.deb ...
==> cilium-master: Unpacking tmux (1.8-5) ...
==> cilium-master: Selecting previously unselected package socat.
==> cilium-master: Preparing to unpack .../socat_1.7.2.3-1_amd64.deb ...
==> cilium-master: Unpacking socat (1.7.2.3-1) ...
==> cilium-master: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> cilium-master: Setting up libcurl3:amd64 (7.35.0-1ubuntu2.9) ...
==> cilium-master: Setting up libevent-2.0-5:amd64 (2.0.21-stable-1ubuntu1.14.04.1) ...
==> cilium-master: Setting up curl (7.35.0-1ubuntu2.9) ...
==> cilium-master: Setting up jq (1.3-1.1ubuntu1) ...
==> cilium-master: Setting up pv (1.2.0-1) ...
==> cilium-master: Setting up realpath (1.19) ...
==> cilium-master: Setting up tmux (1.8-5) ...
==> cilium-master: Setting up socat (1.7.2.3-1) ...
==> cilium-master: Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
==> cilium-master: Running provisioner: build (shell)...
    cilium-master: Running: inline script
==> cilium-master: for i in plugins cilium bpf; do make -C $i clean; done
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-master: for i in cilium-docker cilium-cni; do make -C $i clean; done
==> cilium-master: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-master: go clean
==> cilium-master: rm -f cilium-docker
==> cilium-master: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-master: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
==> cilium-master: go clean
==> cilium-master: rm -f cilium-cni
==> cilium-master: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-master: go clean
==> cilium-master: rm -f cilium
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-master: rm -fr *.o
==> cilium-master: make -C go clean
==> cilium-master: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-master: go clean
==> cilium-master: rm -f map_ctrl
==> cilium-master: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-master: for i in daemon integration; do make -C $i clean; done
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/daemon'
==> cilium-master: go clean
==> cilium-master: rm -f cilium-net-daemon
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/daemon'
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/integration'
==> cilium-master: go clean
==> cilium-master: rm -f integration
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/integration'
==> cilium-master: make -C ./contrib/packaging/deb clean
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/deb'
==> cilium-master: ls -d ./* | grep -vE Makefile\|cfg | xargs rm -rf
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/deb'
==> cilium-master: make -C ./contrib/packaging/rpm clean
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/rpm'
==> cilium-master: ls -d ./* | grep -vE Makefile\|cfg | xargs rm -rf
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/rpm'
==> cilium-master: make -C ./contrib/packaging/docker clean
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/docker'
==> cilium-master: ls -d ./* | grep -vE Makefile | xargs rm -rf
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/docker'
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-master: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-master: go build -ldflags "-X "github.com/cilium/cilium/common".Version=0.1.0.dev" -o cilium-docker
==> cilium-master: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-master: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
==> cilium-master: go build -o cilium-cni ./cilium-cni.go
==> cilium-master: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-master: go build -ldflags "-X "github.com/cilium/cilium/common".Version=0.1.0.dev" -o cilium ./main.go
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-master: clang -Iinclude -D__NR_CPUS__=8 -O2 -target bpf -I. -Wall -Werror -c bpf_lxc.c -o bpf_lxc.o
==> cilium-master: clang -Iinclude -D__NR_CPUS__=8 -O2 -target bpf -I. -Wall -Werror -c bpf_netdev.c -o bpf_netdev.o
==> cilium-master: clang -Iinclude -D__NR_CPUS__=8 -O2 -target bpf -I. -Wall -Werror -c bpf_overlay.c -o bpf_overlay.o
==> cilium-master: clang -DLB_L3 -Iinclude -D__NR_CPUS__=8 -O2 -target bpf -I. -Wall -Werror -c bpf_lb.c -o bpf_lb.o;  clang -DLB_L4 -Iinclude -D__NR_CPUS__=8 -O2 -target bpf -I. -Wall -Werror -c bpf_lb.c -o bpf_lb.o;  clang -DLB_L3 -Iinclude -D__NR_CPUS__=8 -O2 -target bpf -I. -Wall -Werror -c bpf_lb.c -o bpf_lb.o;  clang -DLB_L4 -Iinclude -D__NR_CPUS__=8 -O2 -target bpf -I. -Wall -Werror -c bpf_lb.c -o bpf_lb.o;
==> cilium-master: make -C go
==> cilium-master: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-master: go build -o map_ctrl
==> cilium-master: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-master: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-master: make[2]: Nothing to be done for `all'.
==> cilium-master: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-master: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
==> cilium-master: make[2]: Nothing to be done for `all'.
==> cilium-master: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-master: make[1]: Nothing to be done for `all'.
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-master: make -C go
==> cilium-master: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-master: make[2]: Nothing to be done for `all'.
==> cilium-master: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-master: Running provisioner: install (shell)...
    cilium-master: Running: inline script
==> cilium-master: make: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium'
==> cilium-master: install -m 0755 -d /usr/bin
==> cilium-master: install -m 0755 -d /usr/lib/cilium/lib
==> cilium-master: install -m 0755 -d /usr/lib/cilium/githooks
==> cilium-master: for i in plugins cilium bpf; do make -C $i install; done
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-master: for i in cilium-docker cilium-cni; do make -C $i install; done
==> cilium-master: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-master: install -m 0755 cilium-docker /usr/bin
==> cilium-master: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-master: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
==> cilium-master: install -m 0755 -d /etc/cni/net.d
==> cilium-master: install -m 0644 10-cilium-cni.conf /etc/cni/net.d
==> cilium-master: install -m 0755 -d /opt/cni/bin
==> cilium-master: install -m 0755 cilium-cni /opt/cni/bin
==> cilium-master: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-master: install -m 0755 cilium /usr/bin
==> cilium-master: install -m 0755 -d /etc/bash_completion.d
==> cilium-master: install -m 0644 -T ../contrib/autocomplete/bash_autocomplete /etc/bash_completion.d/cilium
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-master: install -m 0644 -t /usr/lib/cilium/ bpf_lxc.c bpf_netdev.c bpf_overlay.c bpf_lb.c
==> cilium-master: install -m 0755 -t /usr/lib/cilium/ init.sh join_ep.sh leave_ep.sh run_probes.sh
==> cilium-master: install -m 0644 -t /usr/lib/cilium/lib/ ./lib/utils.h ./lib/geneve.h ./lib/maps.h ./lib/policy.h ./lib/l4.h ./lib/conntrack.h ./lib/lxc.h ./lib/csum.h ./lib/common.h ./lib/events.h ./lib/l3.h ./lib/dbg.h ./lib/icmp6.h ./lib/eth.h ./lib/lb.h ./lib/policy_map.h ./lib/ipv4.h ./lib/arp.h ./lib/ipv6.h ./lib/nat46.h ./lib/drop.h
==> cilium-master: for dir in `find include probes -type d`; do \
==> cilium-master:              install -m 0755 -d /usr/lib/cilium/$dir; \
==> cilium-master:              for f in `find $dir -maxdepth 1 -type f`; do \
==> cilium-master:                      install -m 0644 -t /usr/lib/cilium/$dir $f; \
==> cilium-master:              done; \
==> cilium-master:      done
==> cilium-master: make -C go install
==> cilium-master: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-master: install -m 0755 -t /usr/lib/cilium/ map_ctrl
==> cilium-master: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-master: for i in daemon integration; do make -C $i install; done
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/daemon'
==> cilium-master: groupadd -f cilium
==> cilium-master: for dir in `find ui -type d`; do \
==> cilium-master:              install -m 0755 -o root -g cilium -d /usr/lib/cilium/$dir; \
==> cilium-master:              for f in `find $dir -maxdepth 1 -type f`; do \
==> cilium-master:                      install -m 0644 -o root -g cilium -t /usr/lib/cilium/$dir $f; \
==> cilium-master:              done; \
==> cilium-master:      done
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/daemon'
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/integration'
==> cilium-master: make[1]: Nothing to be done for `install'.
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/integration'
==> cilium-master: make: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium'
==> cilium-master: Running provisioner: shell...
    cilium-master: Running: /tmp/vagrant-shell20161020-8922-buvk33.sh
==> cilium-master: stdin: is not a tty
==> cilium-master: stop: Unknown instance: 
==> cilium-master: cilium-net-daemon start/running, process 5783
==> cilium-master: Running provisioner: load-policy (shell)...
    cilium-master: Running: inline script
==> cilium-node-2: Importing base box 'noironetworks/net-next'...
==> cilium-node-2: Matching MAC address for NAT networking...
==> cilium-node-2: Setting the name of the VM: cilium_cilium-node-2_1477001470673_49265
==> cilium-node-2: Fixed port collision for 22 => 2222. Now on port 2200.
==> cilium-node-2: Clearing any previously set network interfaces...
==> cilium-node-2: Preparing network interfaces based on configuration...
    cilium-node-2: Adapter 1: nat
    cilium-node-2: Adapter 2: intnet
==> cilium-node-2: Forwarding ports...
    cilium-node-2: 22 (guest) => 2200 (host) (adapter 1)
==> cilium-node-2: Running 'pre-boot' VM customizations...
==> cilium-node-2: Booting VM...
==> cilium-node-2: Waiting for machine to boot. This may take a few minutes...
    cilium-node-2: SSH address: 127.0.0.1:2200
    cilium-node-2: SSH username: vagrant
    cilium-node-2: SSH auth method: private key
    cilium-node-2: 
    cilium-node-2: Vagrant insecure key detected. Vagrant will automatically replace
    cilium-node-2: this with a newly generated keypair for better security.
    cilium-node-2: 
    cilium-node-2: Inserting generated public key within guest...
    cilium-node-2: Removing insecure key from the guest if it's present...
    cilium-node-2: Key inserted! Disconnecting and reconnecting using new SSH key...
==> cilium-node-2: Machine booted and ready!
==> cilium-node-2: Checking for guest additions in VM...
    cilium-node-2: No guest additions were detected on the base box for this VM! Guest
    cilium-node-2: additions are required for forwarded ports, shared folders, host only
    cilium-node-2: networking, and more. If SSH fails on this machine, please install
    cilium-node-2: the guest additions and repackage the box to continue.
    cilium-node-2: 
    cilium-node-2: This is not an error message; everything may continue to work properly,
    cilium-node-2: in which case you may ignore this message.
==> cilium-node-2: Configuring and enabling network interfaces...
==> cilium-node-2: Rsyncing folder: /home/aanm/temp/cilium-issue/cilium/ => /home/vagrant/go/src/github.com/cilium/cilium
==> cilium-node-2: Running provisioner: bootstrap (shell)...
    cilium-node-2: Running: inline script
==> cilium-node-2: stdin: is not a tty
==> cilium-node-2: Reading package lists...
==> cilium-node-2: Building dependency tree...
==> cilium-node-2: 
==> cilium-node-2: Reading state information...
==> cilium-node-2: The following extra packages will be installed:
==> cilium-node-2:   libcurl3 libevent-2.0-5
==> cilium-node-2: Suggested packages:
==> cilium-node-2:   doc-base
==> cilium-node-2: The following NEW packages will be installed:
==> cilium-node-2:   curl jq libcurl3 libevent-2.0-5 pv realpath socat tmux
==> cilium-node-2: 0 upgraded, 8 newly installed, 0 to remove and 77 not upgraded.
==> cilium-node-2: Need to get 1,118 kB of archives.
==> cilium-node-2: After this operation, 3,238 kB of additional disk space will be used.
==> cilium-node-2: Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main libcurl3 amd64 7.35.0-1ubuntu2.9 [173 kB]
==> cilium-node-2: Get:2 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main libevent-2.0-5 amd64 2.0.21-stable-1ubuntu1.14.04.1 [126 kB]
==> cilium-node-2: Get:3 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main curl amd64 7.35.0-1ubuntu2.9 [123 kB]
==> cilium-node-2: Get:4 http://us.archive.ubuntu.com/ubuntu/ trusty/universe jq amd64 1.3-1.1ubuntu1 [97.8 kB]
==> cilium-node-2: Get:5 http://us.archive.ubuntu.com/ubuntu/ trusty/universe pv amd64 1.2.0-1 [33.7 kB]
==> cilium-node-2: Get:6 http://us.archive.ubuntu.com/ubuntu/ trusty/main realpath amd64 1.19 [14.5 kB]
==> cilium-node-2: Get:7 http://us.archive.ubuntu.com/ubuntu/ trusty/main tmux amd64 1.8-5 [247 kB]
==> cilium-node-2: Get:8 http://us.archive.ubuntu.com/ubuntu/ trusty/universe socat amd64 1.7.2.3-1 [302 kB]
==> cilium-node-2: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> cilium-node-2: Fetched 1,118 kB in 2s (483 kB/s)
==> cilium-node-2: Selecting previously unselected package libcurl3:amd64.
==> cilium-node-2: (Reading database ... 64974 files and directories currently installed.)
==> cilium-node-2: Preparing to unpack .../libcurl3_7.35.0-1ubuntu2.9_amd64.deb ...
==> cilium-node-2: Unpacking libcurl3:amd64 (7.35.0-1ubuntu2.9) ...
==> cilium-node-2: Selecting previously unselected package libevent-2.0-5:amd64.
==> cilium-node-2: Preparing to unpack .../libevent-2.0-5_2.0.21-stable-1ubuntu1.14.04.1_amd64.deb ...
==> cilium-node-2: Unpacking libevent-2.0-5:amd64 (2.0.21-stable-1ubuntu1.14.04.1) ...
==> cilium-node-2: Selecting previously unselected package curl.
==> cilium-node-2: Preparing to unpack .../curl_7.35.0-1ubuntu2.9_amd64.deb ...
==> cilium-node-2: Unpacking curl (7.35.0-1ubuntu2.9) ...
==> cilium-node-2: Selecting previously unselected package jq.
==> cilium-node-2: Preparing to unpack .../jq_1.3-1.1ubuntu1_amd64.deb ...
==> cilium-node-2: Unpacking jq (1.3-1.1ubuntu1) ...
==> cilium-node-2: Selecting previously unselected package pv.
==> cilium-node-2: Preparing to unpack .../archives/pv_1.2.0-1_amd64.deb ...
==> cilium-node-2: Unpacking pv (1.2.0-1) ...
==> cilium-node-2: Selecting previously unselected package realpath.
==> cilium-node-2: Preparing to unpack .../realpath_1.19_amd64.deb ...
==> cilium-node-2: Unpacking realpath (1.19) ...
==> cilium-node-2: Selecting previously unselected package tmux.
==> cilium-node-2: Preparing to unpack .../archives/tmux_1.8-5_amd64.deb ...
==> cilium-node-2: Unpacking tmux (1.8-5) ...
==> cilium-node-2: Selecting previously unselected package socat.
==> cilium-node-2: Preparing to unpack .../socat_1.7.2.3-1_amd64.deb ...
==> cilium-node-2: Unpacking socat (1.7.2.3-1) ...
==> cilium-node-2: Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
==> cilium-node-2: Setting up libcurl3:amd64 (7.35.0-1ubuntu2.9) ...
==> cilium-node-2: Setting up libevent-2.0-5:amd64 (2.0.21-stable-1ubuntu1.14.04.1) ...
==> cilium-node-2: Setting up curl (7.35.0-1ubuntu2.9) ...
==> cilium-node-2: Setting up jq (1.3-1.1ubuntu1) ...
==> cilium-node-2: Setting up pv (1.2.0-1) ...
==> cilium-node-2: Setting up realpath (1.19) ...
==> cilium-node-2: Setting up tmux (1.8-5) ...
==> cilium-node-2: Setting up socat (1.7.2.3-1) ...
==> cilium-node-2: Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
==> cilium-node-2: Running provisioner: build (shell)...
    cilium-node-2: Running: inline script
==> cilium-node-2: for i in plugins cilium bpf; do make -C $i clean; done
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-node-2: for i in cilium-docker cilium-cni; do make -C $i clean; done
==> cilium-node-2: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-node-2: go clean
==> cilium-node-2: rm -f cilium-docker
==> cilium-node-2: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-node-2: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
==> cilium-node-2: go clean
==> cilium-node-2: rm -f cilium-cni
==> cilium-node-2: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-node-2: go clean
==> cilium-node-2: rm -f cilium
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-node-2: rm -fr *.o
==> cilium-node-2: make -C go clean
==> cilium-node-2: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-node-2: go clean
==> cilium-node-2: rm -f map_ctrl
==> cilium-node-2: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-node-2: for i in daemon integration; do make -C $i clean; done
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/daemon'
==> cilium-node-2: go clean
==> cilium-node-2: rm -f cilium-net-daemon
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/daemon'
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/integration'
==> cilium-node-2: go clean
==> cilium-node-2: rm -f integration
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/integration'
==> cilium-node-2: make -C ./contrib/packaging/deb clean
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/deb'
==> cilium-node-2: ls -d ./* | grep -vE Makefile\|cfg | xargs rm -rf
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/deb'
==> cilium-node-2: make -C ./contrib/packaging/rpm clean
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/rpm'
==> cilium-node-2: ls -d ./* | grep -vE Makefile\|cfg | xargs rm -rf
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/rpm'
==> cilium-node-2: make -C ./contrib/packaging/docker clean
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/docker'
==> cilium-node-2: ls -d ./* | grep -vE Makefile | xargs rm -rf
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/contrib/packaging/docker'
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-node-2: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-node-2: go build -ldflags "-X "github.com/cilium/cilium/common".Version=0.1.0.dev" -o cilium-docker
==> cilium-node-2: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-node-2: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
==> cilium-node-2: go build -o cilium-cni ./cilium-cni.go
==> cilium-node-2: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-node-2: go build -ldflags "-X "github.com/cilium/cilium/common".Version=0.1.0.dev" -o cilium ./main.go
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-node-2: clang -Iinclude -D__NR_CPUS__=8 -O2 -target bpf -I. -Wall -Werror -c bpf_lxc.c -o bpf_lxc.o
==> cilium-node-2: clang -Iinclude -D__NR_CPUS__=8 -O2 -target bpf -I. -Wall -Werror -c bpf_netdev.c -o bpf_netdev.o
==> cilium-node-2: clang -Iinclude -D__NR_CPUS__=8 -O2 -target bpf -I. -Wall -Werror -c bpf_overlay.c -o bpf_overlay.o
==> cilium-node-2: clang -DLB_L3 -Iinclude -D__NR_CPUS__=8 -O2 -target bpf -I. -Wall -Werror -c bpf_lb.c -o bpf_lb.o;  clang -DLB_L4 -Iinclude -D__NR_CPUS__=8 -O2 -target bpf -I. -Wall -Werror -c bpf_lb.c -o bpf_lb.o;  clang -DLB_L3 -Iinclude -D__NR_CPUS__=8 -O2 -target bpf -I. -Wall -Werror -c bpf_lb.c -o bpf_lb.o;  clang -DLB_L4 -Iinclude -D__NR_CPUS__=8 -O2 -target bpf -I. -Wall -Werror -c bpf_lb.c -o bpf_lb.o;
==> cilium-node-2: make -C go
==> cilium-node-2: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-node-2: go build -o map_ctrl
==> cilium-node-2: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-node-2: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-node-2: make[2]: Nothing to be done for `all'.
==> cilium-node-2: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-node-2: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
==> cilium-node-2: make[2]: Nothing to be done for `all'.
==> cilium-node-2: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-node-2: make[1]: Nothing to be done for `all'.
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-node-2: make -C go
==> cilium-node-2: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-node-2: make[2]: Nothing to be done for `all'.
==> cilium-node-2: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-node-2: Running provisioner: install (shell)...
    cilium-node-2: Running: inline script
==> cilium-node-2: make: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium'
==> cilium-node-2: install -m 0755 -d /usr/bin
==> cilium-node-2: install -m 0755 -d /usr/lib/cilium/lib
==> cilium-node-2: install -m 0755 -d /usr/lib/cilium/githooks
==> cilium-node-2: for i in plugins cilium bpf; do make -C $i install; done
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-node-2: for i in cilium-docker cilium-cni; do make -C $i install; done
==> cilium-node-2: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-node-2: install -m 0755 cilium-docker /usr/bin
==> cilium-node-2: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-docker'
==> cilium-node-2: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
==> cilium-node-2: install -m 0755 -d /etc/cni/net.d
==> cilium-node-2: install -m 0644 10-cilium-cni.conf /etc/cni/net.d
==> cilium-node-2: install -m 0755 -d /opt/cni/bin
==> cilium-node-2: install -m 0755 cilium-cni /opt/cni/bin
==> cilium-node-2: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins/cilium-cni'
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-node-2: install -m 0755 cilium /usr/bin
==> cilium-node-2: install -m 0755 -d /etc/bash_completion.d
==> cilium-node-2: install -m 0644 -T ../contrib/autocomplete/bash_autocomplete /etc/bash_completion.d/cilium
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-node-2: install -m 0644 -t /usr/lib/cilium/ bpf_lxc.c bpf_netdev.c bpf_overlay.c bpf_lb.c
==> cilium-node-2: install -m 0755 -t /usr/lib/cilium/ init.sh join_ep.sh leave_ep.sh run_probes.sh
==> cilium-node-2: install -m 0644 -t /usr/lib/cilium/lib/ ./lib/utils.h ./lib/geneve.h ./lib/maps.h ./lib/policy.h ./lib/l4.h ./lib/conntrack.h ./lib/lxc.h ./lib/csum.h ./lib/common.h ./lib/events.h ./lib/l3.h ./lib/dbg.h ./lib/icmp6.h ./lib/eth.h ./lib/lb.h ./lib/policy_map.h ./lib/ipv4.h ./lib/arp.h ./lib/ipv6.h ./lib/nat46.h ./lib/drop.h
==> cilium-node-2: for dir in `find include probes -type d`; do \
==> cilium-node-2:              install -m 0755 -d /usr/lib/cilium/$dir; \
==> cilium-node-2:              for f in `find $dir -maxdepth 1 -type f`; do \
==> cilium-node-2:                      install -m 0644 -t /usr/lib/cilium/$dir $f; \
==> cilium-node-2:              done; \
==> cilium-node-2:      done
==> cilium-node-2: make -C go install
==> cilium-node-2: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-node-2: install -m 0755 -t /usr/lib/cilium/ map_ctrl
==> cilium-node-2: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-node-2: for i in daemon integration; do make -C $i install; done
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/daemon'
==> cilium-node-2: groupadd -f cilium
==> cilium-node-2: for dir in `find ui -type d`; do \
==> cilium-node-2:              install -m 0755 -o root -g cilium -d /usr/lib/cilium/$dir; \
==> cilium-node-2:              for f in `find $dir -maxdepth 1 -type f`; do \
==> cilium-node-2:                      install -m 0644 -o root -g cilium -t /usr/lib/cilium/$dir $f; \
==> cilium-node-2:              done; \
==> cilium-node-2:      done
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/daemon'
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/integration'
==> cilium-node-2: make[1]: Nothing to be done for `install'.
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/integration'
==> cilium-node-2: make: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium'
==> cilium-node-2: Running provisioner: shell...
    cilium-node-2: Running: /tmp/vagrant-shell20161020-8922-1i53dy.sh
==> cilium-node-2: stdin: is not a tty
==> cilium-node-2: stop: Unknown instance: 
==> cilium-node-2: cilium-net-daemon start/running, process 7502
[aanm@aanm-MBP cilium]$ 
[aanm@aanm-MBP cilium]$ NUM_NODES=1 vagrant ssh cilium-master
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 4.8.0-rc7-custom x86_64)

 * Documentation:  https://help.ubuntu.com/
New release '16.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

vagrant@cilium-master:~/go/src/github.com/cilium/cilium$ sudo service cilium-net-daemon status
cilium-net-daemon start/running, process 5783
vagrant@cilium-master:~/go/src/github.com/cilium/cilium$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                                NAMES
b9d0d6e63663        consul:v0.6.4       "docker-entrypoint.sh"   5 minutes ago       Up 5 minutes        8300-8302/tcp, 8400/tcp, 8301-8302/udp, 8600/tcp, 8600/udp, 0.0.0.0:8500->8500/tcp   cilium-consul
vagrant@cilium-master:~/go/src/github.com/cilium/cilium$ logout
Connection to 127.0.0.1 closed.
[aanm@aanm-MBP cilium]$ NUM_NODES=1 vagrant ssh cilium-node-2 
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 4.8.0-rc7-custom x86_64)

 * Documentation:  https://help.ubuntu.com/
New release '16.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

vagrant@ubuntu:~/go/src/github.com/cilium/cilium$ sudo service cilium-net-daemon status
cilium-net-daemon start/running, process 7502
vagrant@ubuntu:~/go/src/github.com/cilium/cilium$ logout
Connection to 127.0.0.1 closed.
[aanm@aanm-MBP cilium]$
[aanm@aanm-MBP cilium]$ git log -1 --stat
commit 7a3a048dd94d3056ea5544147dee96681cb787fd
Merge: 5408e78 53b733c
Author: André Martins <aanm@users.noreply.github.com>
Date:   Thu Oct 20 16:36:01 2016 +0100

    Merge pull request #171 from cilium/fixing-k8s-lb

    Fixing k8s lb
```

**Comment by gianarb** [comment]
It's my fault! During the clone I didn't figure our a connection trouble probably because after a new clone all it's working well.

Thanks for your work folks!! Now I can do some test :) :

**Comment by gianarb** [comment]
Ok yesterday was to late and I never wait the end of the provisioning but I tried know and I continue to have the same problem:

```
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/plugins'
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-node-2: go build -ldflags "-X "github.com/cilium/cilium/common".Version=0.1.0.dev" -o cilium ./main.go
==> cilium-node-2: # command-line-arguments
==> cilium-node-2: compile: reading input: EOF
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-node-2: make[1]: *** [cilium] Error 2
==> cilium-node-2: make: *** [cilium] Error 2
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
```

Also after a new clone:

```
14:54 $ git log
commit ab0df8288787cd0dffa01d5069e5922f8fa6b413
Merge: 0606242 226084c
Author: André Martins <aanm@users.noreply.github.com>
Date:   Thu Oct 20 23:23:43 2016 +0100

    Merge pull request #175 from cilium/adding-tomas

    AUTHORS: Adding Tomás to list of AUTHORS
```

I tried a provisioning with only the master it works fine.. The script ends well.

**Comment by tsenart** [comment]
Seemingly related issues: https://github.com/kubernetes/kubernetes/issues/27712 and https://github.com/golang/go/issues/14270

**Comment by aanm** [comment]
It seems that `rsync` causes some corruption in the files.

@gianarb Try putting the go build in verbose with the `-v` flag on the go build that is causing the issue and please paste the output again:
https://github.com/cilium/cilium/blob/master/cilium/Makefile#L17
`go build -v -ldflags "-X "github.com/cilium/cilium/common".Version=$(VERSION)" -o $(TARGET) ./main.go`

Note that you've to edit the file inside the VM.

**Comment by tsenart** [comment]
@aanm, @gianarb: Add the `-x` flag as well. It prints all the commands being executed by `go build`.

**Comment by tsenart** [comment]
@aanm: Also, if corruption seems to be the problem, can we compare hashes of the resulting files on different machines? SHA256 should do it.

**Comment by aanm** [comment]
@tsenart Yep let's find which file is it first, if it is a file. I believe it is an rsync problem since the is the same problem but on a different target.

**Comment by aanm** [comment]
@gianarb Can you try it with `NFS=1`?

**Comment by gianarb** [comment]
My macbook has a lot of problem with this provisioning.. It seems too weak.. I am doing my best :D

**Comment by mchalla** [comment]
I assume you changed num of cores and memory.

```
    vb.memory = "5120"
    vb.cpus = 8
```

I use 2048 and 2 on my 4GB macbook air. Its slow but works.

**Comment by gianarb** [comment]
@mchalla I looked into the conf last week but maybe in a really bad way.. :) Let me change the value and do some test with NFS and no NFS to see what's happen.
Thanks

**Comment by gianarb** [comment]
@mchalla  my 2048 are too bad! :) I am trying with 3GB

```
==> cilium-master: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-master: go build -ldflags "-X "github.com/cilium/cilium/common".Version=0.1.0.dev" -o cilium ./main.go
==> cilium-master: # command-line-arguments
==> cilium-master: /usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory
==> cilium-master: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-master: make[1]: *** [cilium] Error 2
==> cilium-master: make:
==> cilium-master: *** [cilium] Error 2
```

**Comment by gianarb** [comment]
With `NFS=1`. It's not working.. I try without

```
==> cilium-node-2: install -m 0755 -d /etc/bash_completion.d
==> cilium-node-2: install -m 0644 -T ../contrib/autocomplete/bash_autocomplete /etc/bash_completion.d/cilium
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/cilium'
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-node-2: install -m 0644 -t /usr/lib/cilium/ bpf_lxc.c bpf_netdev.c bpf_overlay.c bpf_lb.c
==> cilium-node-2: install -m 0755 -t /usr/lib/cilium/ init.sh join_ep.sh leave_ep.sh run_probes.sh
==> cilium-node-2: install -m 0644 -t /usr/lib/cilium/lib/ ./lib/arp.h ./lib/common.h ./lib/conntrack.h ./lib/csum.h ./lib/dbg.h ./lib/drop.h ./lib/eth.h ./lib/events.h ./lib/geneve.h ./lib/icmp6.h ./lib/ipv4.h ./lib/ipv6.h ./lib/l3.h ./l
ib/l4.h ./lib/lb.h ./lib/lxc.h ./lib/maps.h ./lib/nat46.h ./lib/policy.h ./lib/policy_map.h ./lib/utils.h
==> cilium-node-2: for dir in `find include probes -type d`; do \
==> cilium-node-2:              install -m 0755 -d /usr/lib/cilium/$dir; \
==> cilium-node-2:              for f in `find $dir -maxdepth 1 -type f`; do \
==> cilium-node-2:                      install -m 0644 -t /usr/lib/cilium/$dir $f; \
==> cilium-node-2:              done; \
==> cilium-node-2:      done
==> cilium-node-2: make -C go install
==> cilium-node-2: make[2]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-node-2: install -m 0755 -t /usr/lib/cilium/ map_ctrl
==> cilium-node-2: make[2]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf/go'
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/bpf'
==> cilium-node-2: for i in daemon integration; do make -C $i install; done
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/daemon'
==> cilium-node-2: groupadd -f cilium
==> cilium-node-2: for dir in `find ui -type d`; do \
==> cilium-node-2:              install -m 0755 -o root -g cilium -d /usr/lib/cilium/$dir; \
==> cilium-node-2:              for f in `find $dir -maxdepth 1 -type f`; do \
==> cilium-node-2:                      install -m 0644 -o root -g cilium -t /usr/lib/cilium/$dir $f; \
==> cilium-node-2:              done; \
==> cilium-node-2:      done
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/daemon'
==> cilium-node-2: make[1]: Entering directory `/home/vagrant/go/src/github.com/cilium/cilium/integration'
==> cilium-node-2: make[1]: Nothing to be done for `install'.
==> cilium-node-2: make[1]: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium/integration'
==> cilium-node-2: make: Leaving directory `/home/vagrant/go/src/github.com/cilium/cilium'
==> cilium-node-2: Running provisioner: shell...
    cilium-node-2: Running: /var/folders/15/r96rbkf92_zdnhfg2tk4wwm80000gn/T/vagrant-shell20161026-4056-f3neuc.sh
==> cilium-node-2: stdin: is not a tty
```

**Comment by mchalla** [comment]
Could you ssh to the box and see that Cilium is running. ps aux | grep cilium. If not try service cilium-net-daemon restart. 

I think "stdin: is not a tty" message is fine. 

https://github.com/mitchellh/vagrant/issues/1673

**Comment by gianarb** [comment]
Yep! Well done!! @mchalla why we have that kind of resources into the vagrant provisioning? usually it's for local env and it's quite hard fit that size..

**Comment by tgraf** [comment]
We should probably reduce the default number of cpus and memory in the Vagrantfile.

**Comment by gianarb** [comment]
I am doing a PR @tgraf

**Comment by gianarb** [comment]
I am just following the getting started with docker-compose, right know I can not start the `cilium` container. I run this command into the vagrant box (cilium-master).

```
$ IFACE=eth1 docker-compose up cilium
dockercompose_consul_1 is up-to-date
Starting dockercompose_cilium_1
Attaching to dockercompose_cilium_1
cilium_1         | 2016-10-26T21:58:55.958Z cilium-master CRIT 001 run > Error while creating daemon: empty configuration provided
dockercompose_cilium_1 exited with code 1
```

**Comment by mchalla** [comment]
Can you try starting the daemon manually and see why it fails. 

cat /etc/init/cilium-net-daemon.conf

sudo bash
export PATH=/usr/local/clang/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
and run the next command from the file.
cilium -D daemon run -n ...

**Comment by mchalla** [comment]
May be it has to do with docker-compose.  I will take a look at it later.

**Comment by aanm** [comment]
@gianarb sorry about that, fixed here: https://github.com/cilium/cilium/pull/182

**Comment by mchalla** [comment]
I think it has to something to do with the etcd config file since thats the only place we throw this error. By giving a dummy file I am able to get past that error.

docker-compose.yml

**Comment by aanm** [comment]
@gianarb you only need to add `-c 127.0.0.1:8500` at the end of the 5th line in `docker-compose.yml`

**Comment by aanm** [comment]
@gianarb or pull the master branch since the PR was merged ;-)

**Comment by gianarb** [comment]
I will try this evening @aanm ! thanks!

**Comment by tgraf** [comment]
@gianarb Did you have a chance to try again? The bug should have been fixed via #182.

**Comment by gianarb** [comment]
Sure I think that this evening I can do some tests @tgraf

**Comment by tgraf** [comment]
Awesome, thanks @gianarb

**Comment by gianarb** [comment]
I am back! Still having some trouble but I am opening another PR. I can confirm now that I have a better laptop that a lot of problem was related my laptop performance probably.
Which the new one all is better.
