### ISSUE TITLE
NetworkPolicy of fluxcd notification-controller causes constant failing cilium pod on a node in v1.11.[1-3]

### ISSUE THREAD

**Issue by DirkTheDaring** [cilium/cilium#19279]
this bug blocks a complete node from running its pods properly - please find a fix or suggest a workaround.
You can see effect of this by noticing hanging pods which do not get an IP Address assigned, e.g. the notification-controller of fluxcd hanging in "ContainerCreating".

Environment: Kubernetes cluster v1.23.5  with 14 nodes created with kubespray and cilium setting (1.11.[1-3])

What happens? When fluxcd v0.28.0  is rolled out in a cluster with cilium v1.11.[1-3] whenever the Networkpolicy of fluxcd for notification controller is applied, the cilium pod goes crazy and spits out a lot of similar messages (see below)
It restarts the a specific cilium pod every minute  - the cilium pod  runs  on the same node where pod notification-controller of fluxcd is running - which in turn has this NetworkPolicy (see below)

By trial and error I have found out when I delete NetworkPolicy the cilium  pod starts working again 
`kubectl -n flux-system delete NetworkPolicy allow-webhooks`

Messages in the cilium log (usually 30-50 of them.. only a sample here)
```
level=error msg="Failed to add PolicyMap key" bpfMapKey="{19103 0 0 0}" containerID=b7762c7eb5 datapathPolicyRevision=12 desiredPolicyRevision=16 endpointID=419 error="Unable to update element for cilium_policy_00419 map with file descriptor 152: the map is full, please consider resizing it. argument list too long" identity=47140 ipv4=192.168.67.184 ipv6= k8sPodName=flux-system/notification-controller-7dd8bdf67-kdrc6 port=0 subsys=endpoint
level=error msg="Failed to add PolicyMap key" bpfMapKey="{54803 0 0 0}" containerID=b7762c7eb5 datapathPolicyRevision=12 desiredPolicyRevision=16 endpointID=419 error="Unable to update element for cilium_policy_00419 map with file descriptor 152: the map is full, please consider resizing it. argument list too long" identity=47140 ipv4=192.168.67.184 ipv6= k8sPodName=flux-system/notification-controller-7dd8bdf67-kdrc6 port=0 subsys=endpoint
```
NetworkPolicy which causes this issue. Hint when i replace the  namespaceSelector line with another selector ,e.g. ipBlock then cilium has no problems at all.

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v0.28.0
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: allow-webhooks
  namespace: flux-system
spec:
  ingress:
  - from:
    - namespaceSelector: {}
  podSelector:
    matchLabels:
      app: notification-controller
  policyTypes:
  - Ingress
```

**Comment by aanm** [comment]
You need to increment the bpf policy map size. Try `--set bpf.policyMapMax=32768`. Also make sure you don't have a lot of CiliumIdentities. If you have consider limiting the identity-relevant labels as mentioned [here](https://docs.cilium.io/en/v1.11/operations/performance/scalability/identity-relevant-labels/).

**Comment by DirkTheDaring** [comment]
bpf.policyMapMax=32768 already set, forget to report that.

Will check out the ciliumidenties

**Comment by DirkTheDaring** [comment]
Applied this line to cilium config. Then restarted all cilium pods

line added:
`  labels:  "k8s:io.kubernetes\\.pod\\.namespace k8s:k8s-app k8s:app k8s:name"`

**Did not help** :( 
```
level=error msg="Failed to add PolicyMap key" bpfMapKey="{40592 0 0 0}" containerID=676d266ba7 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=2913 error="Unable to update element for cilium_policy_02913 map with file descriptor 245: the map is full, please consider resizing it. argument list too long" identity=21047 ipv4=192.168.72.92 ipv6= k8sPodName=flux-system/notification-controller-7dd8bdf67-n6j2x port=0 subsys=endpoint
level=error msg="Failed to add PolicyMap key" bpfMapKey="{7307 0 0 0}" containerID=676d266ba7 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=2913 error="Unable to update element for cilium_policy_02913 map with file descriptor 245: the map is full, please consider resizing it. argument list too long" identity=21047 ipv4=192.168.72.92 ipv6= k8sPodName=flux-system/notification-controller-7dd8bdf67-n6j2x port=0 subsys=endpoint
level=error msg="Failed to add PolicyMap key" bpfMapKey="{29343 0 0 0}" containerID=676d266ba7 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=2913 error="Unable to update element for cilium_policy_02913 map with file descriptor 245: the map is full, please consider resizing it. argument list too long" identity=21047 ipv4=192.168.72.92 ipv6= k8sPodName=flux-system/notification-controller-7dd8bdf67-n6j2x port=0 subsys=endpoint
level=error msg="Failed to add PolicyMap key" bpfMapKey="{809 0 0 0}" containerID=676d266ba7 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=2913 error="Unable to update element for cilium_policy_02913 map with file descriptor 245: the map is full, please consider resizing it. argument list too long" identity=21047 ipv4=192.168.72.92 ipv6= k8sPodName=flux-system/notification-controller-7dd8bdf67-n6j2x port=0 subsys=endpoint
level=error msg="Failed to add PolicyMap key" bpfMapKey="{27599 0 0 0}" containerID=676d266ba7 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=2913 error="Unable to update element for cilium_policy_02913 map with file descriptor 245: the map is full, please consider resizing it. argument list too long" identity=21047 ipv4=192.168.72.92 ipv6= k8sPodName=flux-system/notification-controller-7dd8bdf67-n6j2x port=0 subsys=endpoint
level=error msg="Failed to add PolicyMap key" bpfMapKey="{50007 0 0 0}" containerID=676d266ba7 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=2913 error="Unable to update element for cilium_policy_02913 map with file descriptor 245: the map is full, please consider resizing it. argument list too long" identity=21047 ipv4=192.168.72.92 ipv6= k8sPodName=flux-system/notification-controller-7dd8bdf67-n6j2x port=0 subsys=endpoint
level=error msg="Failed to add PolicyMap key" bpfMapKey="{37893 0 0 0}" containerID=676d266ba7 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=2913 error="Unable to update element for cilium_policy_02913 map with file descriptor 245: the map is full, please consider resizing it. argument list too long" identity=21047 ipv4=192.168.72.92 ipv6= k8sPodName=flux-system/notification-controller-7dd8bdf67-n6j2x port=0 subsys=endpoint
level=warning msg="generating BPF for endpoint failed, keeping stale directory." containerID=676d266ba7 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=2913 file-path=2913_next_fail identity=21047 ipv4=192.168.72.92 ipv6= k8sPodName=flux-system/notification-controller-7dd8bdf67-n6j2x subsys=endpoint
level=warning msg="Regeneration of endpoint failed" bpfCompilation=0s bpfLoadProg=0s bpfWaitForELF=0s bpfWriteELF=0s containerID=676d266ba7 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=2913 error="unable to regenerate policy because PolicyMap synchronization failed: syncPolicyMap failed" identity=21047 ipv4=192.168.72.92 ipv6= k8sPodName=flux-system/notification-controller-7dd8bdf67-n6j2x mapSync=4.26976112s policyCalculation="11.264µs" prepareBuild="58.997µs" proxyConfiguration="9.489µs" proxyPolicyCalculation=22.714755ms proxyWaitForAck=0s reason="retrying regeneration" subsys=endpoint total=4.292828166s waitingForCTClean=0s waitingForLock="1.476µs"
level=error msg="endpoint regeneration failed" containerID=676d266ba7 datapathPolicyRevision=0 desiredPolicyRevision=4 endpointID=2913 error="unable to regenerate policy because PolicyMap synchronization failed: syncPolicyMap failed" identity=21047 ipv4=192.168.72.92 ipv6= k8sPodName=flux-system/notification-controller-7dd8bdf67-n6j2x subsys=endpoint
```

**Comment by DirkTheDaring** [comment]
bpf-policy-map-max         65536      does also not make the problem go away.

**Comment by aanm** [comment]
can you provide a sysdump?

**Comment by DirkTheDaring** [comment]
Sure. I have restricted  the sysdump  to the node where the pod fails:
`cilium sysdump --node-list prod1-node2`
[cilium-sysdump-20220331-050823.zip](https://github.com/cilium/cilium/files/8385677/cilium-sysdump-20220331-050823.zip)

**Comment by DirkTheDaring** [comment]
because it seems that kuberhealthy is in the report, this is how kuberhealthy pods look like after some hours runtime.  
```
kuberhealthy           daemonset-1648717661                                             0/1     Completed                    0                54m
kuberhealthy           daemonset-1648718560                                             0/1     Completed                    0                39m
kuberhealthy           daemonset-1648719460                                             0/1     Completed                    0                24m
kuberhealthy           daemonset-1648720360                                             0/1     Completed                    0                9m18s
kuberhealthy           deployment-1648718860                                            0/1     Completed                    0                34m
kuberhealthy           deployment-1648719461                                            0/1     Completed                    0                24m
kuberhealthy           deployment-1648720060                                            0/1     Completed                    0                14m
kuberhealthy           deployment-1648720660                                            0/1     Completed                    0                4m18s
kuberhealthy           dns-status-internal-1648720420                                   0/1     Completed                    0                8m18s
kuberhealthy           dns-status-internal-1648720540                                   0/1     Completed                    0                6m18s
kuberhealthy           dns-status-internal-1648720660                                   0/1     Completed                    0                4m18s
kuberhealthy           dns-status-internal-1648720780                                   0/1     Completed                    0                2m18s
kuberhealthy           dns-status-internal-1648720900                                   0/1     Completed                    0                18s
kuberhealthy           pod-restarts-1648719760                                          0/1     Completed                    0                19m
kuberhealthy           pod-restarts-1648720060                                          0/1     Completed                    0                14m
kuberhealthy           pod-restarts-1648720360                                          0/1     Completed                    0                9m18s
kuberhealthy           pod-restarts-1648720660                                          0/1     Completed                    0                4m17s
kuberhealthy           pod-status-1648719760                                            0/1     Completed                    0                19m
kuberhealthy           pod-status-1648720060                                            0/1     Completed                    0                14m
kuberhealthy           pod-status-1648720360                                            0/1     Completed                    0                9m18s
kuberhealthy           pod-status-1648720660                                            0/1     Completed                    0                4m17s
```

**Comment by DirkTheDaring** [comment]
do you need more information?

**Comment by aanm** [comment]
Yes, the sysdump doesn't contain a directory named `cilium-bugtool-cilium-agent-xxxxxx`. it should contain a directory for each node captured.

**Comment by DirkTheDaring** [comment]
The problem caused by flux cd is also tracked here

[Unreachable readiness probes with k3s + Cilium CNI ](https://github.com/fluxcd/flux2/issues/1450
)
Recommendation is to set --network-policy=false on installation which is default true.

This is really ugly and it becomes worse when you start using tools like kuberhealthy + tekton in the cluster. 
Observation: basically all tools which leave "Terminated" pods behind (Finished Tekton jobs, or finished probes of kuberhealthy) seem to cause this when fluxcd has his three network policies activated... so install fluxcd (standard)  and start a lot of tekton jobs....

**Comment by DirkTheDaring** [comment]
so it turns out the root cause lies as always where you are not looking. It seems that also cilium install worked like a charm with kubespray, there is no warning about that you should turn of "nodelocaldns" in the first place - at least not in the install of kubespray "nodelocaldns", which relies *hardcoded* on hostNetwork: true. According to cilium blogs this causes troubles - and i was never able to run the test suite without fails (4/11 tests failed).  So I removed that whole localdns --> all works now.  However it is worth to mention that i tried to turn on nodelocaldns with the documentation of cilium (without hostNetwork true).  But it never worked (guess that it why it is called a beta feature).

**Comment by DirkTheDaring** [comment]
another cause of the problem was that the CiliumIdentiy was filled up with 65536 identies by runs of kuberhealthty (which generated a "unique" CiliumIdenitity on every run, due to different label) . It is extremly easy to run into this trap with a heavily used  cluster ("flannel" was used before). Please make a lmite usage of labels the standard policy. Find out that after 4 weeks the ciliumidentieis where used up was kind of unexpected behavior for people with very limited cilium experience. 
I really ask for reasonable defaults. And letting cilium fill-up CiliumIdentity quickly (Kubherhealty... running every 3 Minutes) is not a a reasonable default. I would expect.

**Comment by aanm** [comment]
@DirkTheDaring There was a bug in the Garbage Collection of the CiliumIdentities in Cilium 1.11.0-1.11.4. It should be fixed in 1.11.5. Let us know if you are still facing issues. Thanks

**Comment by aanm** [comment]
@masterkain can you get a sysdump?

**Comment by masterkain** [comment]
@aanm unfortunately I had to get up and running fast so I switched to another system provided by scaleway

**Comment by kks427** [comment]
I see the same issue in cilium-1.11.6 . After upgrade, It certainly takes few days for failure with these errors. 

level=error msg="Failed to add PolicyMap key" bpfMapKey="{42804 8180 6 0}" containerID= datapathPolicyRevision=291 desiredPolicyRevision=277 endpointID=1538 error="Unable to update element for cilium_policy_01538 map with file descriptor 263: the map is full, please consider resizing it. argument list too long" identity=42947 ipv4= ipv6= k8sPodName=/ port=0 subsys=endpoint
level=error msg="Failed to add PolicyMap key" bpfMapKey="{33331 8180 6 0}" containerID= datapathPolicyRevision=291 desiredPolicyRevision=277 endpointID=1538 error="Unable to update element for cilium_policy_01538 map with file descriptor 263: the map is full, please consider resizing it. argument list too long" identity=42947 ipv4= ipv6= k8sPodName=/ port=0 subsys=endpoint
level=warning msg="Policy map sync fixed errors, consider running with debug verbose = policy to get detailed dumps" containerID= count=65033 datapathPolicyRevision=291 desiredPolicyRevision=277 endpointID=1538 identity=42947 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=warning msg="Key allocation attempt failed" attempt=11 error="no more available IDs in configured space" key="[k8s:app=astro-adapter k8s:branch=NGCP-5741-prototype-3 k8s:io.cilium.k8s.namespace.labels.msi.cie/provisioned=true k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=ngcp-dev k8s:release=astro-adapter-blue k8s:role=ngcp-service]" subsys=allocator
level=warning msg="Error changing endpoint identity" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=441 error="unable to resolve identity: exponential backoff cancelled via context: context canceled" identityLabels="k8s:app=astro-adapter,k8s:branch=NGCP-5741-prototype-3,k8s:io.cilium.k8s.namespace.labels.msi.cie/provisioned=true,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=ngcp-dev,k8s:release=astro-adapter-blue,k8s:role=ngcp-service" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Processing API request with rate limiter" name=endpoint-delete parallelRequests=4 subsys=rate uuid=c72c4fdc-8063-4390-97e9-78e368171c52
level=info msg="API request released by rate limiter" name=endpoint-delete parallelRequests=4 subsys=rate uuid=c72c4fdc-8063-4390-97e9-78e368171c52 waitDurationTotal="72.901µs"
level=info msg="API call has been processed" error="endpoint not found" name=endpoint-delete processingDuration="4.2µs" subsys=rate totalDuration="110.701µs" uuid=c72c4fdc-8063-4390-97e9-78e368171c52 waitDurationTotal="72.901µs"
level=info msg="Removed endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=441 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=warning msg="Creation of endpoint failed" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=441 error="request cancelled while resolving identity" ipv4= ipv6= k8sPodName=/ subsys=daemon
level=info msg="API call has been processed" error="request cancelled while resolving identity" name=endpoint-create processingDuration=1m30.075793241s subsys=rate totalDuration=1m30.07591664s uuid=ab262152-a5b7-4c2a-9abd-b920f33be041 waitDurationTotal="103.299µs"
level=info msg="Processing API request with rate limiter" name=endpoint-delete parallelRequests=4 subsys=rate uuid=258a237a-4b0f-4f76-a15d-1ab86a874e1b
level=info msg="API request released by rate limiter" name=endpoint-delete parallelRequests=4 subsys=rate uuid=258a237a-4b0f-4f76-a15d-1ab86a874e1b waitDurationTotal="83.801µs"
level=info msg="API call has been processed" error="endpoint not found" name=endpoint-delete processingDuration="4.1µs" subsys=rate totalDuration="121.301µs" uuid=258a237a-4b0f-4f76-a15d-1ab86a874e1b waitDurationTotal="83.801µs"
level=info msg="Processing API request with rate limiter" maxWaitDuration=15s name=endpoint-create parallelRequests=5 subsys=rate uuid=68518cea-6b0f-467b-aab9-975d716422d7
level=info msg="API request released by rate limiter" burst=5 limit=0.87/s maxWaitDuration=15s maxWaitDurationLimiter=14.999915599s name=endpoint-create parallelRequests=5 subsys=rate uuid=68518cea-6b0f-467b-aab9-975d716422d7 waitDurationLimiter=0s waitDurationTotal="93.701µs"
level=info msg="Create endpoint request" addressing="&{192.168.41.101 2f953019-7b6a-4420-9247-f209e3bde325  }" containerID=59d0e6d2e0053d1688921a83cb1241558d62d832b6556592c7fcc54a68fea402 datapathConfiguration="<nil>" interface=lxc48c92eee004f k8sPodName=ngcp-dev/astro-adapter-blue-78464468d7-bd49s labels="[]" subsys=daemon sync-build=true
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2619 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=2619 identityLabels="k8s:app=astro-adapter,k8s:branch=NGCP-5741-prototype-3,k8s:io.cilium.k8s.namespace.labels.msi.cie/provisioned=true,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=ngcp-dev,k8s:release=astro-adapter-blue,k8s:role=ngcp-service" ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=warning msg="Key allocation attempt failed" attempt=0 error="no more available IDs in configured space" key="[k8s:app=astro-adapter k8s:branch=NGCP-5741-prototype-3 k8s:io.cilium.k8s.namespace.labels.msi.cie/provisioned=true k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=ngcp-dev k8s:release=astro-adapter-blue k8s:role=ngcp-service]" subsys=allocator
level=warning msg="Key allocation attempt failed" attempt=1 error="no more available IDs in configured space" key="[k8s:app=astro-adapter k8s:branch=NGCP-5741-prototype-3 k8s:io.cilium.k8s.namespace.labels.msi.cie/provisioned=true k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=ngcp-dev k8s:release=astro-adapter-blue k8s:role=ngcp-service]" subsys=allocator
[cilium-bugtool-20220707-124410-UTC-706385540.tar.gz](https://github.com/cilium/cilium/files/9063959/cilium-bugtool-20220707-124410-UTC-706385540.tar.gz)

**Comment by kks427** [comment]
do we have any update on this issue..!?

**Comment by aanm** [comment]
@kks427 there was an issue with the garbage collection of identities. Please upgrade to the last Cilium version and that should be resolved. Thank you!

**Comment by kks427** [comment]
Is this fix available in 1.11.7 or 1.12.0..!! Thanks..

**Comment by aanm** [comment]
both versions have the fix.

**Comment by un000** [comment]
The same bug in 1.11.8, k8s 1.24.2

```
cilium version
Client: 1.11.8 ff1ed93 2022-08-12T17:17:38+02:00 go version go1.17.13 linux/amd64
Daemon: 1.11.8 ff1ed93 2022-08-12T17:17:38+02:00 go version go1.17.13 linux/amd64
```


```2022-09-11T04:57:37+03:00 level=warning msg="Key allocation attempt failed" attempt=9 error="no more available IDs in configured space" key="[k8s:controller-uid=8afe082f-8ac6-4143-ac58-11ced3dbaea3 k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=organization k8s:io.cilium.k8s.namespace.labels.name=organization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=organization k8s:job-name=some-job-onesignal-27714261]" subsys=allocator
2022-09-11T04:57:38+03:00 level=warning msg="Key allocation attempt failed" attempt=7 error="no more available IDs in configured space" key="[k8s:controller-uid=31d08af2-bed9-4e15-8f30-6228a1464a64 k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=organization k8s:io.cilium.k8s.namespace.labels.name=organization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=organization k8s:job-name=some-job-27714311]" subsys=allocator
2022-09-11T04:57:43+03:00 level=warning msg="Key allocation attempt failed" attempt=8 error="no more available IDs in configured space" key="[k8s:controller-uid=31d08af2-bed9-4e15-8f30-6228a1464a64 k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=organization k8s:io.cilium.k8s.namespace.labels.name=organization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=organization k8s:job-name=some-job-27714311]" subsys=allocator
2022-09-11T04:57:49+03:00 level=warning msg="Key allocation attempt failed" attempt=11 error="no more available IDs in configured space" key="[k8s:controller-uid=8dfffaa7-00b3-494b-a6d6-c9e2c0bd72de k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=organization k8s:io.cilium.k8s.namespace.labels.name=organization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=organization k8s:job-name=some-job-27714261]" subsys=allocator
2022-09-11T04:57:49+03:00 level=info msg="Processing API request with rate limiter" maxWaitDuration=15s name=endpoint-create parallelRequests=6 subsys=rate uuid=91e69db6-d1f0-4ebd-96c0-159506ff37a0
2022-09-11T04:57:49+03:00 level=info msg="API request released by rate limiter" burst=6 limit=1.02/s maxWaitDuration=15s maxWaitDurationLimiter=14.999893266s name=endpoint-create parallelRequests=6 subsys=rate uuid=91e69db6-d1f0-4ebd-96c0-159506ff37a0 waitDurationLimiter=0s waitDurationTotal="115.662µs"
2022-09-11T04:57:49+03:00 level=info msg="Create endpoint request" addressing="&{10.233.76.103 98be0702-daae-40ec-879a-9a994317420a  }" containerID=2f0b8f08b92d220e7cbf02f0ece31752e842e876ab839c808e9a77f8b22af31f datapathConfiguration="<nil>" interface=lxce4fdd9ad4b1d k8sPodName=organization/scpclimiter-27714270-f74r7 labels="[]" subsys=daemon sync-build=true
2022-09-11T04:57:49+03:00 level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3261 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2022-09-11T04:57:49+03:00 level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3261 identityLabels="k8s:controller-uid=35038506-30f0-4af5-9d0a-4ec9a932dd10,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=organization,k8s:io.cilium.k8s.namespace.labels.name=organization,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=organization,k8s:job-name=some-job-27714270" ipv4= ipv6= k8sPodName=/ subsys=endpoint
2022-09-11T04:57:49+03:00 level=warning msg="Key allocation attempt failed" attempt=0 error="no more available IDs in configured space" key="[k8s:controller-uid=35038506-30f0-4af5-9d0a-4ec9a932dd10 k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=organization k8s:io.cilium.k8s.namespace.labels.name=organization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=organization k8s:job-name=some-job-27714270]" subsys=allocator
2022-09-11T04:57:50+03:00 level=warning msg="Key allocation attempt failed" attempt=1 error="no more available IDs in configured space" key="[k8s:controller-uid=35038506-30f0-4af5-9d0a-4ec9a932dd10 k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=organization k8s:io.cilium.k8s.namespace.labels.name=organization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=organization k8s:job-name=some-job-27714270]" subsys=allocator
2022-09-11T04:51:55+03:00 level=warning msg="Error changing endpoint identity" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=774 error="unable to resolve identity: exponential backoff cancelled via context: context canceled" identityLabels="k8s:controller-uid=8afe082f-8ac6-4143-ac58-11ced3dbaea3,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=organization,k8s:io.cilium.k8s.namespace.labels.name=organization,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=organization,k8s:job-name=some-job-onesignal-27714261" ipv4= ipv6= k8sPodName=/ subsys=endpoint

```

**Comment by un000** [comment]
v1.11.7 the same bug, k8s 1.24.2
Switched to CRD-store, but the problem remains after some time. 

```
2022-09-11T04:57:37+03:00 level=warning msg="Key allocation attempt failed" attempt=9 error="no more available IDs in configured space" key="[k8s:controller-uid=8afe082f-8ac6-4143-ac58-11ced3dbaea3 k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=organization k8s:io.cilium.k8s.namespace.labels.name=organization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=organization k8s:job-name=some-job-27714261]" subsys=allocator
2022-09-11T04:57:38+03:00 level=warning msg="Key allocation attempt failed" attempt=7 error="no more available IDs in configured space" key="[k8s:controller-uid=31d08af2-bed9-4e15-8f30-6228a1464a64 k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=organization k8s:io.cilium.k8s.namespace.labels.name=organization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=organization k8s:job-name=some-job-27714311]" subsys=allocator
2022-09-11T04:57:43+03:00 level=warning msg="Key allocation attempt failed" attempt=8 error="no more available IDs in configured space" key="[k8s:controller-uid=31d08af2-bed9-4e15-8f30-6228a1464a64 k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=organization k8s:io.cilium.k8s.namespace.labels.name=organization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=organization k8s:job-name=some-job-27714311]" subsys=allocator
2022-09-11T04:57:49+03:00 level=warning msg="Key allocation attempt failed" attempt=11 error="no more available IDs in configured space" key="[k8s:controller-uid=8dfffaa7-00b3-494b-a6d6-c9e2c0bd72de k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=organization k8s:io.cilium.k8s.namespace.labels.name=organization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=organization k8s:job-name=some-job-27714261]" subsys=allocator
2022-09-11T04:57:49+03:00 level=info msg="Processing API request with rate limiter" maxWaitDuration=15s name=endpoint-create parallelRequests=6 subsys=rate uuid=91e69db6-d1f0-4ebd-96c0-159506ff37a0
2022-09-11T04:57:49+03:00 level=info msg="API request released by rate limiter" burst=6 limit=1.02/s maxWaitDuration=15s maxWaitDurationLimiter=14.999893266s name=endpoint-create parallelRequests=6 subsys=rate uuid=91e69db6-d1f0-4ebd-96c0-159506ff37a0 waitDurationLimiter=0s waitDurationTotal="115.662µs"
2022-09-11T04:57:49+03:00 level=info msg="Create endpoint request" addressing="&{10.233.76.103 98be0702-daae-40ec-879a-9a994317420a  }" containerID=2f0b8f08b92d220e7cbf02f0ece31752e842e876ab839c808e9a77f8b22af31f datapathConfiguration="<nil>" interface=lxce4fdd9ad4b1d k8sPodName=organization/scpclimiter-27714270-f74r7 labels="[]" subsys=daemon sync-build=true
2022-09-11T04:57:49+03:00 level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3261 ipv4= ipv6= k8sPodName=/ subsys=endpoint
2022-09-11T04:57:49+03:00 level=info msg="Resolving identity labels (blocking)" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=3261 identityLabels="k8s:controller-uid=35038506-30f0-4af5-9d0a-4ec9a932dd10,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=organization,k8s:io.cilium.k8s.namespace.labels.name=organization,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=organization,k8s:job-name=some-job-27714270" ipv4= ipv6= k8sPodName=/ subsys=endpoint
2022-09-11T04:57:49+03:00 level=warning msg="Key allocation attempt failed" attempt=0 error="no more available IDs in configured space" key="[k8s:controller-uid=35038506-30f0-4af5-9d0a-4ec9a932dd10 k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=organization k8s:io.cilium.k8s.namespace.labels.name=organization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=organization k8s:job-name=some-job-27714270]" subsys=allocator
2022-09-11T04:57:50+03:00 level=warning msg="Key allocation attempt failed" attempt=1 error="no more available IDs in configured space" key="[k8s:controller-uid=35038506-30f0-4af5-9d0a-4ec9a932dd10 k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=organization k8s:io.cilium.k8s.namespace.labels.name=organization k8s:io.cilium.k8s.policy.cluster=default k8s:io.cilium.k8s.policy.serviceaccount=default k8s:io.kubernetes.pod.namespace=organization k8s:job-name=some-job-27714270]" subsys=allocator
2022-09-11T04:51:55+03:00 level=warning msg="Error changing endpoint identity" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=774 error="unable to resolve identity: exponential backoff cancelled via context: context canceled" identityLabels="k8s:controller-uid=8afe082f-8ac6-4143-ac58-11ced3dbaea3,k8s:io.cilium.k8s.namespace.labels.kubernetes.io/metadata.name=organization,k8s:io.cilium.k8s.namespace.labels.name=organization,k8s:io.cilium.k8s.policy.cluster=default,k8s:io.cilium.k8s.policy.serviceaccount=default,k8s:io.kubernetes.pod.namespace=organization,k8s:job-name=some-job-27714261" ipv4= ipv6= k8sPodName=/ subsys=endpoint

```

**Comment by aanm** [comment]
Closing as this was caused by the operator not running which was preventing the garbage collection of identities.
