### ISSUE TITLE
Egress Bandwidth Limit not enforced with wireguard encryption

### ISSUE THREAD

**Issue by wer-anders** [cilium/cilium#22203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

If I disable wireguard encryption, the netperf example from [Bandwidth Manager Cilium Documentation](https://docs.cilium.io/en/v1.12/gettingstarted/bandwidth-manager/) is working.
As soon as I enable wireguard encryption, pod to pod traffic is not limited anymore (I took care that the pods are running on different nodes). Traffic leaving the cluster is still limited.

### Cilium Version

v1.12.3

### Kernel Version

5.10.0-18-amd64 Debian11

### Kubernetes Version

v1.24.6

### Anything else?

I already mentioned this in #16790. 
Encryption: Wireguard [cilium_wg0 (Pubkey: hzrb...)
BandwidthManager: EDT with BPF [CUBIC] [eth0]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by brb** [comment]
Thanks for the issue. This should be fixed in https://github.com/cilium/cilium/pull/19401.

**Comment by wer-anders** [comment]
Can we leave this open until it is fixed (eg with #19401)? I will keep track and can test as soon as a fix is available.

**Comment by brb** [comment]
@wer-anders The PR #19401has been merged. Could you test it?

**Comment by wer-anders** [comment]
Unfortunately no change. The bandwithlimit is still not enforced when wireguard encryption is enabled.

P.S. I pulled the latest master, build the operator and the daemonset image.
My daemonset now states
Client: 1.13.90 67844187a1 2023-01-26T19:16:11+08:00 go version go1.19.5 linux/amd64
Daemon: 1.13.90 67844187a1 2023-01-26T19:16:11+08:00 go version go1.19.5 linux/amd64
--
kubectl exec -it -n kube-system cilium-t7bd9 -n cilium-agent -- cilium bpf bandwidth list
IDENTITY   EGRESS BANDWIDTH (BitsPerSec)
276        10M
--
NAME             READY   STATUS              RESTARTS   AGE   IP       NODE         NOMINATED NODE   READINESS GATES
netperf-client   1/1     Running             0          8s    172.24.50.206   worker-jf3   <none>           <none>
netperf-server   1/1     Running             0          8s    172.24.53.165   worker-jf2   <none>           <none>
--
NETPERF_SERVER_IP=$(kubectl get pod netperf-server -o jsonpath='{.status.podIP}')
kubectl exec netperf-client -- \
    netperf -t TCP_MAERTS -H "${NETPERF_SERVER_IP}"
MIGRATED TCP MAERTS TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 172.24.53.165 (172.24.) port 0 AF_INET
Recv   Send    Send                          
Socket Socket  Message  Elapsed              
Size   Size    Size     Time     Throughput  
bytes  bytes   bytes    secs.    10^6bits/sec  

131072  16384  16384    10.00     347.49

**Comment by brb** [comment]
Can you run `ip rule list` from any of the cilium nodes?

**Comment by wer-anders** [comment]
```
worker-jf2 ~ # ip rule list
0:	from all lookup local
32766:	from all lookup main
32767:	from all lookup default

worker-jf2 ~ # ip link | grep -e cilium 
4: cilium_net@cilium_host: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
5: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
6: cilium_geneve: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
151: cilium_wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN mode DEFAULT group default 

```

**Comment by brb** [comment]
@wer-anders Could you run `cilium status --verbose` from the same node?

**Comment by wer-anders** [comment]
```
kubectl -n kube-system exec -it cilium-mccbz -c cilium-agent -- cilium status verbose
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.25 (v1.25.5) [linux/amd64]
Kubernetes APIs:         ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    Strict   [eth0 10.24.2.81]
Host firewall:           Disabled
CNI Chaining:            none
CNI Config file:         CNI configuration file management disabled
Cilium:                  Ok   1.13.90 (v1.13.90-67844187a1)
NodeMonitor:             Listening for events on 8 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok   
IPAM:                    IPv4: 18/254 allocated from 172.24.53.0/24, 
IPv6 BIG TCP:            Disabled
BandwidthManager:        EDT with BPF [CUBIC] [eth0]
Host Routing:            Legacy
Masquerading:            BPF   [eth0]   172.24.53.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       99/99 healthy
Proxy Status:            No managed proxy redirect
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 4095/4095 (100.00%), Flows/s: 96.12   Metrics: Ok
Encryption:              Wireguard       [cilium_wg0 (Pubkey: bErIHwZ913rfO4FkNQQXgZ7S1rFTDA66g1HAbEvxChI=, Port: 51871, Peers: 5)]
Cluster health:          6/6 reachable   (2023-02-01T16:15:08Z)

```

**Comment by brb** [comment]
@borkmann are you aware of any EDT and WireGuard netdev limitations?

Basically, the EDT code is executed here - https://github.com/cilium/cilium/blob/master/bpf/bpf_host.c#L1186, while the redirection to the WG netdev happens immediately afterwards - https://github.com/cilium/cilium/blob/master/bpf/bpf_host.c#L1206. Or should the EDT run on the WG netdev too (i.e., not only `eth0` which redirects to `cilium_wg0`)?

**Comment by wer-anders** [comment]
I just tested this with the 1.14.3 release and it is still not working. Can you have another look into this?

```
kubectl exec netperf-client -- netperf -t TCP_MAERTS -H "${NETPERF_SERVER_IP}"
MIGRATED TCP MAERTS TEST from 0.0.0.0 (0.0.0.0) port 0 AF_INET to 172.24.56.235 (172.24.) port 0 AF_INET
Recv   Send    Send                          
Socket Socket  Message  Elapsed              
Size   Size    Size     Time     Throughput  
bytes  bytes   bytes    secs.    10^6bits/sec  

131072  16384  16384    10.00      73.9
```

```
kubectl -n kube-system exec ds/cilium -- cilium status 
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.27 (v1.27.4) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    Strict   [eth0 10.24.2.81 (Direct Routing)]
Host firewall:           Disabled
CNI Chaining:            none
Cilium:                  Ok   1.14.3 (v1.14.3-252a99ef)
NodeMonitor:             Listening for events on 8 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok   
IPAM:                    IPv4: 8/254 allocated from 172.24.56.0/24, 
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        EDT with BPF [CUBIC] [eth0]
Host Routing:            BPF
Masquerading:            BPF   [eth0]   172.24.56.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       50/50 healthy
Proxy Status:            No managed proxy redirect
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 4095/4095 (100.00%), Flows/s: 17.59   Metrics: Disabled
Encryption:              Wireguard       [NodeEncryption: Disabled, cilium_wg0 (Pubkey: +QQWNpQ/uh/25MDEe9bRTaRWVOPKkhQtQHYaCsBP5Ws=, Port: 51871, Peers: 8)]
Cluster health:          9/9 reachable   (2023-11-02T15:38:05Z)
```

**Comment by wer-anders** [comment]
Hello,
I just tested this with the Image from https://github.com/cilium/cilium/issues/16790#issuecomment-1908246383 and it is working now even without `--enable-runtime-device-detection`.

```
kubectl -n kube-system exec -it cilium-ppvpn -c cilium-agent -- cilium status
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.28 (v1.28.6) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    Strict   [eth0   10.24.2.78 fe80::5054:ff:fe1d:a277 (Direct Routing)]
Host firewall:           Disabled
SRv6:                    Disabled
CNI Chaining:            none
Cilium:                  Ok   1.16.0-dev (v1.16.0-dev-044330d6)
NodeMonitor:             Listening for events on 4 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok   
IPAM:                    IPv4: 5/254 allocated from 172.24.52.0/24, 
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        EDT with BPF [CUBIC] [eth0]
Host Routing:            BPF
Masquerading:            BPF   [eth0]   172.24.52.0/24 [IPv4: Enabled, IPv6: Disabled]
Controller Status:       39/39 healthy
Proxy Status:            No managed proxy redirect
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 4095/4095 (100.00%), Flows/s: 13.50   Metrics: Ok
Encryption:              Wireguard       [NodeEncryption: Disabled, cilium_wg0 (Pubkey: lBFISD1iu5XZ8WUoA/U/11XtaMILDSfu+v3h6CnuRkE=, Port: 51871, Peers: 8)]
Cluster health:          9/9 reachable   (2024-01-24T18:29:46Z)
Modules Health:          Stopped(0) Degraded(0) OK(11) Unknown(5)
```
