### ISSUE TITLE
CFP: Cilium behavior differs from kube-proxy - doesn't drain long-lived connections when backend is removed from a service.

### ISSUE THREAD

**Issue by yasz24** [cilium/cilium#23761]
## Cilium Feature Proposal
       
**Is your feature request related to a problem?**

Let's say you have a service that points to a given set of backend endpoints, and a long-lived connection is created via the service to one of those backend endpoints. Now, if the label-selector for the service is changed, and the service no longer points to an old backend endpoint, any packet sent through that long-lived connection will be dropped, and re-connected to a new backend.   

**Describe the feature you'd like**

In the scenario described above, we would like for existing connections to not break, and continue serving packets over that connection, as long as the backend pod is running and ready. This is the behavior observed with the kube-proxy/iptables based dataplane.

**(Optional) Describe your proposed solution**

We did some investigation and found that the root cause was that cilium deletes the `backend_entry` from the backend map as soon as a backend is removed from a service, and its overall service `refCount` is also 0.  https://github.com/cilium/cilium/blob/105331bd133131c6f724fc9121fef1fb57c22ca9/pkg/service/service.go#L1592-L1596
https://github.com/cilium/cilium/blob/105331bd133131c6f724fc9121fef1fb57c22ca9/pkg/service/service.go#L1335-L1340

Then, when cilium tries to lookup the deleted backend using `ct_entry->backend_id`, finding none, it selects a new backend from the current pool of backends for that service--causing existing connections to the old backend endpoint to break, even if the pod itself is still `ready`.  
https://github.com/cilium/cilium/blob/105331bd133131c6f724fc9121fef1fb57c22ca9/bpf/lib/lb.h#L1671-L1692

Our proposed minimal fix is for backend entries to not be deleted when a service removes a backend from it's pool, and instead, to retroactively clean-up the backend entries when the associated pod itself gets deleted. In doing so the backend lookup for the long-lived connections will continue to succeed, even after the backend endpoint has been removed from all services that point to it, and existing connections established to those backends will be preserved until the pod is killed or the client closes the connection. This would give us the behavior we expect. 

This solution would probably also render the [`backendRefCount`](https://github.com/cilium/cilium/blob/master/pkg/service/service.go#L241) redundant, which could consequently be gotten rid of it.

Optionally we could follow up by adding a periodic garbage collection flow for the backend entries, which considers if a backend, with `backendRefCount == 0`, has any active connections, and if not it retroactively deletes them.

**Comment by varunmar** [comment]
This feels similar to https://github.com/cilium/cilium/issues/14844, but is different because in this case the backend pods are still alive - they're just no longer part of the service.
This behavior - removing live pods from a service, is often used to orchestrate blue-green deployments and workload upgrades. Without the ability to keep long lived connections alive, this strategy is infeasible when using Cilium.

Another option to consider is whether we should only do this for TCP-only services. The current behavior of picking a new backend from the current set of backends is probably fine for UDP, but is destined to always fail with TCP.

**Comment by youngnick** [comment]
Triaging; this one is definitely for sig-agent.

My relatively-uneducated thoughts though:
- _Technically_, we're talking about Endpoints, not Pods though.
- The blue-green use case makes sense and seems pretty reasonable
- I'm worried that by doing the suggested fix, we might be trading off stability of long-running connections against speed of detecting service changes in the event of pod (actually Endpoint) churn.
- Also, adding this in introduces some extra state in the agent; if the agent restarts in between the time that the pod (Endpoint) is removed from the Service, and the pod (Endpoint) is removed, how would the agent reconstruct what should be happening?

**Comment by aojea** [comment]
The way this works in kube-proxy is because it relies in conntrack, so established connections through services are handled by the conntrack state, the deletion of an endpoints doesn't suppose the deletion of the conntrack entry (UDP has some edge cases, but better not complicate more this issue), so the graceful termination is not broken. 

Is worth mentioning that some users already requested this behavior (dropping connections) on Endpoint changes, but for backwards compatibility is not possible to modify kube-proxy to do this.

With the new TerminatingEndpoints feature the graceful termination is solved though 🤔 , cc: @thockin 

> * Also, adding this in introduces some extra state in the agent; if the agent restarts in between the time that the pod (Endpoint) is removed from the Service, and the pod (Endpoint) is removed, how would the agent reconstruct what should be happening?

the agent has always to reconstruct the status from the Kubernetes Services and Endpoints object, if it depend on conntrack it has nothing to do, just program the dataplane with the current information, the key here is how to handle established connection

**Comment by thockin** [comment]
I think this is a legitimate point for debate.  Lots of discussion in https://github.com/kubernetes/kubernetes/issues/108523

If an endpoint ceases to be part of a Service, but that endpoint still exists - should we break TCP connections or not?  iptables and ipvs do not, becuase we rely on conntrack.  IIRC we tried to break the connection by deleting the conntrack record, but conntrack is "too smart" and will actually re-assemble itself.  So what we do in iptables mode shouldn't be take as spec (yet?).

I think the question comes down to what this pattern is actually used for.  Blue-green seems plausible, but I don't know the details of what people are doing.  I presume it's something like: turn up new workloads with different labels, flip Service selector, turn down old workloads.  Breaking connections there would be bad.  

I have also heard of quarantining errant endpoints by changing the labels on a single pod - in that case breaking connertions seems acceptable or even correct.

What I would like to avoid is making this yet another configuration option.

**Comment by aditighag** [comment]
Hi! 

> This feels similar to #14844, but is different because in this case the backend pods are still alive - they're just no longer part of the service. This behavior - removing live pods from a service, is often used to orchestrate blue-green deployments and workload upgrades. Without the ability to keep long lived connections alive, this strategy is infeasible when using Cilium.

You should get this behavior with socket-lb already (kube-proxy replacement=strict). Socket-lb selects a backend at the socket `connect` time, and as long as the backend is running, the long-lived connections should persist. 

>This behavior - removing live pods from a service, is often used to orchestrate blue-green deployments and workload upgrades. 

As for per per packet LB, I would suggest you to check out the quarantining API - https://isovalent.com/blog/post/cilium-release-112/#quarantining. We support setting other [backend states](https://github.com/cilium/cilium/blob/master/pkg/loadbalancer/loadbalancer.go#L243) such as maintenance, etc. Instead of changing labels, you could take out some of the backends from load balancing new traffic for a service. 

> Without the ability to keep long lived connections alive, this strategy is infeasible when using Cilium.

We have users who use the services API to put backends into the maintenance state.

**Comment by yasz24** [comment]
The problem with using the `backend states` is that a backend could be shared as an endpoint for more than one service at the same time. Since the state is on a backend-level, putting a backend in the `quarantine` state for instance, would remove it from the load-balancing pool for all services that share this backend. 

This isn't the behavior desired in `blue-green` type rollouts, where the intention is to remove the backend exclusively from the service that is being `blue-green` orchestrated -- without affecting the backend endpoints for any other services that share the same backend.

**Comment by thockin** [comment]
I think this should be reopened and evaluated.

**Comment by yasz24** [comment]
hi, can we please re-open this issue? we've had some customers recently ask about this use case.

**Comment by youngnick** [comment]
We can reopen, but there needs to be activity on it or else it will go stale again.

**Comment by jonahmurphy** [comment]
> I'm seeing what looks to be the same issue for LoadBalancer services when a backend pod enters a non ready state, all tcp connections are dropped, when we expect that existing connections should be maintained until either the client or backend terminates them.

@youngnick would this issue cover the case I mentioned above or should I create a separate issue for this ? 

This behaviour surprised us, we would expect to be able to use the readinessProbe prevent new traffic being sent to a backend pod (e.g in the case of an overload, upstream issue), without impacting existing traffic.

**Comment by youngnick** [comment]
Sounds like it to me, yes, although I'll defer to the datapath folks.

**Comment by artemlive** [comment]
We have recently experienced the same problem! It took us a few weeks to get what was going on :)

**Comment by dbason** [comment]
> This behaviour surprised us, we would expect to be able to use the readinessProbe prevent new traffic being sent to a backend pod (e.g in the case of an overload, upstream issue), without impacting existing traffic.

This is the exact situation we are in.  We were trying to use readiness checks to temporarily remove overloaded pods from a service while they complete their processing, however the connection resets completely breaks this pattern.
