### ISSUE TITLE
Verify cilium compatibility with Amazon Linux 2023

### ISSUE THREAD

**Issue by chancez** [cilium/cilium#24397]
https://aws.amazon.com/about-aws/whats-new/2023/03/amazon-linux-2023/

Reviewing the new Amazon Linux docs, there's a few notable things that may impact cilium:
- Defaults to IMDSv2. I believe this PR https://github.com/cilium/cilium/pull/15828 makes it possible to use IMDSv2.
- selinux is enabled by default, given Cilium's privileged situation, I suspect Selinux could cause some issues.
- The kernel seems to be 6.1 in the current release: https://docs.aws.amazon.com/linux/al2023/ug/performance-optimizations.html. They also mention they'll be using LTS Kernels and not the same Kernel Fedora ships with.

**Comment by amitmavgupta** [comment]
On an EKS-A cluster that's running AL 23, Cilium is working fine. (tested this on 1.13.6)

`uname -a
Linux cilium-eksa-c5vrq 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
[root@cilium-eksa-c5vrq /]# uname -r
5.15.49-linuxkit
[root@cilium-eksa-c5vrq /]# cat /etc/amazon-linux-release
Amazon Linux release 2023 (Amazon Linux)
[root@cilium-eksa-c5vrq /]#`

✅ All 42 tests (191 actions) successful, 12 tests skipped, 1 scenarios skipped.

cilium status
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       OK
    \__/       ClusterMesh:        disabled

Deployment        cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
Deployment        hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
DaemonSet         cilium             Desired: 2, Ready: 2/2, Available: 2/2
Deployment        hubble-ui          Desired: 1, Ready: 1/1, Available: 1/1
Containers:       cilium             Running: 2
                  hubble-relay       Running: 1
                  hubble-ui          Running: 1
                  cilium-operator    Running: 2
Cluster Pods:     20/20 managed by Cilium
Image versions    hubble-relay       quay.io/cilium/hubble-relay:v1.13.6@sha256:da96840b638d3e9705cfc48af2bddfe92d17eb4f5a776b075bef9ac50efbb042: 1
                  hubble-ui          quay.io/cilium/hubble-ui:v0.11.0@sha256:bcb369c47cada2d4257d63d3749f7f87c91dde32e010b223597306de95d1ecc8: 1
                  hubble-ui          quay.io/cilium/hubble-ui-backend:v0.11.0@sha256:14c04d11f78da5c363f88592abae8d2ecee3cbe009f443ef11df6ac5f692d839: 1
                  cilium-operator    quay.io/cilium/operator-generic:v1.13.6@sha256:753c1d0549032da83ec45333feec6f4b283331618a1f7fed2f7e2d36efbd4bc9: 2
                  cilium             quay.io/cilium/cilium:v1.13.6@sha256:994b8b3b26d8a1ef74b51a163daa1ac02aceb9b16f794f8120f15a12011739dc: 2

kubectl -n kube-system exec ds/cilium -- cilium status
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.27 (v1.27.4-eks-cedffd4) [linux/arm64]
Kubernetes APIs:         ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    Disabled
Host firewall:           Disabled
CNI Chaining:            none
CNI Config file:         CNI configuration file management disabled
Cilium:                  Ok   1.13.6 (v1.13.6-792ad58f)
NodeMonitor:             Listening for events on 2 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok
IPAM:                    IPv4: 19/254 allocated from 192.168.1.0/24,
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Host Routing:            Legacy
Masquerading:            IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:       99/99 healthy
Proxy Status:            OK, ip 192.168.1.61, 0 redirects active on ports 10000-20000
Global Identity Range:   min 256, max 65535
Hubble:                  Ok   Current/Max Flows: 4095/4095 (100.00%), Flows/s: 30.46   Metrics: Ok
Encryption:              Disabled
Cluster health:          2/2 reachable   (2023-09-06T09:26:29Z)

kubectl -n kube-system exec ds/cilium -- cilium-health status
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
Probe time:   2023-09-06T09:26:29Z
Nodes:
  cilium-eksa-md-0-5fd7d89f88xwdkzb-bj2xj (localhost):
    Host connectivity to 172.18.0.6:
      ICMP to stack:   OK, RTT=1.251375ms
      HTTP to agent:   OK, RTT=811.959µs
    Endpoint connectivity to 192.168.1.230:
      ICMP to stack:   OK, RTT=1.23625ms
      HTTP to agent:   OK, RTT=781µs
  cilium-eksa-c5vrq:
    Host connectivity to 172.18.0.5:
      ICMP to stack:   OK, RTT=1.234333ms
      HTTP to agent:   OK, RTT=1.035667ms
    Endpoint connectivity to 192.168.0.149:
      ICMP to stack:   OK, RTT=1.1565ms
      HTTP to agent:   OK, RTT=3.694834ms

**Comment by sylr** [comment]
On my side I tried and AL2023 nodes whole networking stops working as soon as the cilium agent starts.

PS: @amitmavgupta can you please use code blocks when pasting logs, your post is barely readable. Thank you.

**Comment by amitmavgupta** [comment]
@sylr not sure where I goofed up in the code blocks but I have fixed my previous comment. Sorry about that.

**Comment by Paulius0112** [comment]
Any update on this?

**Comment by ajvn** [comment]
As EKS optimized version of AL2023 got released recently, we gave it a go, however some tweaking is required for it to work with Cilium (v1.14.7).

It seems like EKS optimized version has 2 default routes, on both `ens5` and `ens6` interfaces. After removing `ens6` Cilium pod started fine.
Error you can encounter goes something like this:
```
level=error msg="Start hook failed" error="daemon creation failed: error while initializing daemon: failed while reinitializing datapath: unable to install ip rule for ENI multi-node NodePort: failed to find interface with default route: Found multiple default routes with the same priority: {Ifindex: 2 Dst: 0.0.0.0/0 Src: <x.x.x.x> Gw: <x.x.x.x> Flags: [] Table: 254 Realm: 0} vs {Ifindex: 3 Dst: 0.0.0.0/0 Src: <x.x.x.x> Gw: <x.x.x.x> Flags: [] Table: 254 Realm: 0}" function="cmd.newDaemonPromise.func1 (daemon_main.go:1663)" subsys=hive
```
To delete second route:
```
$ sudo ip route delete default via <x.x.x.x>
```

**Comment by ajvn** [comment]
Here's more complete solution: https://github.com/awslabs/amazon-eks-ami/issues/1678#issuecomment-1983736020

**Comment by kimxogus** [comment]
In my cluster, cilium still fails.
Cilium 1.14.5, 1.14.9, 1.15.3 all fails with the complete solution above :(

- container status
```
  cilium-agent:
    Container ID:  containerd://2f37dc0e35c454a0be2d92a3d7cece9b8b95a4c66d373169f34e306a38bbfdef
    Image:         quay.io/cilium/cilium:v1.14.9@sha256:4ef1eb7a3bc39d0fefe14685e6c0d4e01301c40df2a89bc93ffca9a1ab927301
    Image ID:      quay.io/cilium/cilium@sha256:4ef1eb7a3bc39d0fefe14685e6c0d4e01301c40df2a89bc93ffca9a1ab927301
    Ports:         4244/TCP, 9962/TCP
    Host Ports:    4244/TCP, 9962/TCP
    Command:
      cilium-agent
    Args:
      --config-dir=/tmp/cilium/config-map
    State:       Running
      Started:   Fri, 05 Apr 2024 17:06:21 +0900
    Last State:  Terminated
      Reason:    Error
      Message:   cilium.k8s.policy.uid=df051ebe-4f55-4ba2-9955-1225ed8b43b2] Description:}]" policyAddRequest=e9c966a3-2e57-4f46-bb85-c252fa2c421f subsys=daemon
level=info msg="Policy imported via API, recalculating..." policyAddRequest=e9c966a3-2e57-4f46-bb85-c252fa2c421f policyRevision=3 subsys=daemon
level=info msg="Imported CiliumNetworkPolicy" ciliumNetworkPolicyName=intra-namespace-communication k8sApiVersion=cilium.io/v2 k8sNamespace=kstandup subsys=k8s-watcher
level=info msg="Node updated" clusterName=default nodeName=i-07f0e33e7e37c99ce.ap-northeast-2.compute.internal subsys=nodemanager
level=info msg="Node updated" clusterName=default nodeName=ip-10-134-101-171.ap-northeast-2.compute.internal subsys=nodemanager
level=info msg="Node updated" clusterName=default nodeName=ip-10-134-107-177.ap-northeast-2.compute.internal subsys=nodemanager
level=info msg="Node updated" clusterName=default nodeName=ip-10-134-108-220.ap-northeast-2.compute.internal subsys=nodemanager
level=info msg="Node updated" clusterName=default nodeName=ip-10-134-125-24.ap-northeast-2.compute.internal subsys=nodemanager
level=info msg="Node updated" clusterName=default nodeName=ip-10-134-45-177.ap-northeast-2.compute.internal subsys=nodemanager
level=info msg="Node updated" clusterName=default nodeName=ip-10-134-74-215.ap-northeast-2.compute.internal subsys=nodemanager
level=info msg="Node updated" clusterName=default nodeName=ip-10-134-98-107.ap-northeast-2.compute.internal subsys=nodemanager
level=info msg="Node updated" clusterName=default nodeName=ip-10-134-101-171.ap-northeast-2.compute.internal subsys=nodemanager
level=warning msg="Unable to update CiliumNode resource, will retry" error="Operation cannot be fulfilled on ciliumnodes.cilium.io \"ip-10-134-80-47.
      Exit Code:    2
      Started:      Fri, 05 Apr 2024 17:05:57 +0900
      Finished:     Fri, 05 Apr 2024 17:05:59 +0900
```

- pod events
```
Events:
  Type     Reason          Age                From               Message
  ----     ------          ----               ----               -------
  Normal   Scheduled       70s                default-scheduler  Successfully assigned kube-system/cilium-7wcfd to ip-10-134-80-47.ap-northeast-2.compute.internal
  Normal   Pulled          69s                kubelet            Container image "quay.io/cilium/cilium:v1.14.9@sha256:4ef1eb7a3bc39d0fefe14685e6c0d4e01301c40df2a89bc93ffca9a1ab927301" already present on machine
  Normal   Created         69s                kubelet            Created container config
  Normal   Started         69s                kubelet            Started container config
  Normal   Pulled          69s                kubelet            Container image "quay.io/cilium/cilium:v1.14.9@sha256:4ef1eb7a3bc39d0fefe14685e6c0d4e01301c40df2a89bc93ffca9a1ab927301" already present on machine
  Normal   Created         69s                kubelet            Created container mount-cgroup
  Normal   Started         69s                kubelet            Started container mount-cgroup
  Normal   Pulled          68s                kubelet            Container image "quay.io/cilium/cilium:v1.14.9@sha256:4ef1eb7a3bc39d0fefe14685e6c0d4e01301c40df2a89bc93ffca9a1ab927301" already present on machine
  Normal   Created         68s                kubelet            Created container apply-sysctl-overwrites
  Normal   Started         68s                kubelet            Started container apply-sysctl-overwrites
  Normal   Pulled          66s                kubelet            Container image "quay.io/cilium/cilium:v1.14.9@sha256:4ef1eb7a3bc39d0fefe14685e6c0d4e01301c40df2a89bc93ffca9a1ab927301" already present on machine
  Normal   Created         66s                kubelet            Created container mount-bpf-fs
  Normal   Started         66s                kubelet            Started container mount-bpf-fs
  Normal   Pulled          66s                kubelet            Container image "quay.io/cilium/cilium:v1.14.9@sha256:4ef1eb7a3bc39d0fefe14685e6c0d4e01301c40df2a89bc93ffca9a1ab927301" already present on machine
  Normal   Created         66s                kubelet            Created container clean-cilium-state
  Normal   Started         66s                kubelet            Started container clean-cilium-state
  Normal   Pulled          65s                kubelet            Container image "quay.io/cilium/cilium:v1.14.9@sha256:4ef1eb7a3bc39d0fefe14685e6c0d4e01301c40df2a89bc93ffca9a1ab927301" already present on machine
  Normal   Created         65s                kubelet            Created container install-cni-binaries
  Normal   Started         65s                kubelet            Started container install-cni-binaries
  Normal   Pulled          64s                kubelet            Container image "quay.io/cilium/cilium:v1.14.9@sha256:4ef1eb7a3bc39d0fefe14685e6c0d4e01301c40df2a89bc93ffca9a1ab927301" already present on machine
  Normal   Created         64s                kubelet            Created container cilium-agent
  Normal   Started         63s                kubelet            Started container cilium-agent
  Warning  Unhealthy       62s (x2 over 63s)  kubelet            Readiness probe failed: Get "http://127.0.0.1:9879/healthz": dial tcp 127.0.0.1:9879: connect: connection refused
  Normal   Killing         39s                kubelet            Stopping container cilium-agent
  Normal   SandboxChanged  38s                kubelet            Pod sandbox changed, it will be killed and re-created.
```


Our helm values is
```yaml
eni:
  enabled: true
ipam:
  mode: eni
tunnel: disabled
kubeProxyReplacement: true
bpf:
  masquerade: true
loadBalancer:
  serviceTopology: true

prometheus:
  enabled: true

operator:
  prometheus:
    enabled: true

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            io.cilium/app: operator
cni:
  exclusive: false

envoy:
  enabled: true

ipv4NativeRoutingCIDR: 10.0.0.0/8
```

Our helm values had no issues with ubuntu, amazonlinux 2 host nodes. Is there any issues with our helm values?

**Comment by jaffcheng** [comment]
We have tried cilium on self-managed Amazon Linux 2023 nodes recently and run into network issues similar to the above comments caused by `amazon-ec2-net-utils` v2. It removes custom ip rules periodically as described in issues like https://github.com/amazonlinux/amazon-ec2-net-utils/issues/96. In our case, it even removes `from all lookup local` which breaks loopback connectivity. The systemd-networkd configuration from [cilium docs](https://docs.cilium.io/en/stable/network/concepts/ipam/eni/#node-configuration) is necessary but not sufficient for this case and we solved this by removing `amazon-ec2-net-utils` package entirely and adding a static config file for eth0 like:
```
cat /etc/systemd/network/eth0.network
[Match]
Name=eth0

[Network]
DHCP=yes
```
Not sure if this occurs on a recent version cilium node, but since `amazon-ec2-net-utils` would very likely interfere with cilium node network so I believe it's still worth mentioning here.

**Comment by wgoyer** [comment]
Added some [notes to this issue](https://github.com/awslabs/amazon-eks-ami/issues/1678#issuecomment-2341874286) about a problem we had with cilium and al2023. Pods associated with cilium provisioned ENIs were unable to reach out externally of the cluster.

**Comment by khacminh** [comment]
AL2 will reach EOL on June 30, 2025, making a transition to AL2023 essential. This issue has been open for 1.5 years and should be prioritized to ensure it is addressed promptly.

**Comment by khacminh** [comment]
This PR #36076 is merged.

**Comment by viktor-kurchenko** [comment]
Cilium CLI [PR](https://github.com/cilium/cilium/pull/36076) to support AL2023.

**Comment by joestringer** [comment]
@viktor-kurchenko I think we can close this issue as completed now, is that right or do you think there are additional work items to achieve this?

**Comment by viktor-kurchenko** [comment]
> [@viktor-kurchenko](https://github.com/viktor-kurchenko) I think we can close this issue as completed now, is that right or do you think there are additional work items to achieve this?

I think it can be closed. Thank you!
