### ISSUE TITLE
Ginkgo: provisioning of VMs keeps failing on local setup

### ISSUE THREAD

**Issue by ianvernon** [cilium/cilium#2470]
When I boot the VMs on my local host (Mac laptop), the provisioning scripts fail. For example:
```
Ians-MBP:test ianvernon$ K8S_VERSION=1.6 vagrant up k8s1-1.6
Bringing machine 'k8s1-1.6' up with 'virtualbox' provider...
==> k8s1-1.6: Cloning VM...
==> k8s1-1.6: Matching MAC address for NAT networking...
==> k8s1-1.6: Checking if box 'cilium/ginkgo' is up to date...
==> k8s1-1.6: Setting the name of the VM: test_k8s1-16_1515434988403_38033
==> k8s1-1.6: Clearing any previously set network interfaces...
==> k8s1-1.6: Preparing network interfaces based on configuration...
    k8s1-1.6: Adapter 1: nat
    k8s1-1.6: Adapter 2: intnet
==> k8s1-1.6: Forwarding ports...
    k8s1-1.6: 22 (guest) => 2222 (host) (adapter 1)
==> k8s1-1.6: Running 'pre-boot' VM customizations...
==> k8s1-1.6: Booting VM...
==> k8s1-1.6: Waiting for machine to boot. This may take a few minutes...
    k8s1-1.6: SSH address: 127.0.0.1:2222
    k8s1-1.6: SSH username: vagrant
    k8s1-1.6: SSH auth method: private key
    k8s1-1.6: Warning: Connection reset. Retrying...
    k8s1-1.6: 
    k8s1-1.6: Vagrant insecure key detected. Vagrant will automatically replace
    k8s1-1.6: this with a newly generated keypair for better security.
    k8s1-1.6: 
    k8s1-1.6: Inserting generated public key within guest...
    k8s1-1.6: Removing insecure key from the guest if it's present...
    k8s1-1.6: Key inserted! Disconnecting and reconnecting using new SSH key...
==> k8s1-1.6: Machine booted and ready!
==> k8s1-1.6: Checking for guest additions in VM...
    k8s1-1.6: The guest additions on this VM do not match the installed version of
    k8s1-1.6: VirtualBox! In most cases this is fine, but in rare cases it can
    k8s1-1.6: prevent things such as shared folders from working properly. If you see
    k8s1-1.6: shared folder errors, please make sure the guest additions within the
    k8s1-1.6: virtual machine match the version of VirtualBox you have installed on
    k8s1-1.6: your host and reload your VM.
    k8s1-1.6: 
    k8s1-1.6: Guest Additions Version: 5.2.2
    k8s1-1.6: VirtualBox Version: 5.1
==> k8s1-1.6: Setting hostname...
==> k8s1-1.6: Configuring and enabling network interfaces...
==> k8s1-1.6: Mounting shared folders...
    k8s1-1.6: /src => /Users/ianvernon/go/src/github.com/cilium/cilium
    k8s1-1.6: /vagrant => /Users/ianvernon/go/src/github.com/cilium/cilium/test
==> k8s1-1.6: Running provisioner: shell...
    k8s1-1.6: Running: inline script
==> k8s1-1.6: Running provisioner: file...
==> k8s1-1.6: Running provisioner: shell...
    k8s1-1.6: Running: /var/folders/5f/63bp05l16w33ts7rsybrn_w00000gn/T/vagrant-shell20180108-23237-tot3vg.sh
==> k8s1-1.6: --2018-01-08 18:10:12--  https://packages.cloud.google.com/apt/doc/apt-key.gpg
==> k8s1-1.6: Resolving packages.cloud.google.com (packages.cloud.google.com)... 
==> k8s1-1.6: failed: Name or service not known.
==> k8s1-1.6: wget: unable to resolve host address 'packages.cloud.google.com'
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

### How to reproduce the issue

1. `cd test;  K8S_VERSION=1.6 vagrant up k8s1-1.6` - doesn't matter the K8s version. Provisioning fails sporadically. 

The booting of these VMs needs to work consistently. I suspect an issue with DNS.

**Comment by eloycoto** [comment]
@ianvernon does this happens always to you? Are you be able to reproduce? 

I made a few test on my mac, and it works perfectly. The DNS issue was fixed on the PR #2331, on the other hand, this looks very similar to issue #2188 

So, if the host can ping connect to 8.8.8.8  should work without problems :\

**Comment by ianvernon** [comment]
Assigning to myself as I am able to reproduce this consistently locally. I added retry logic in #2480, as checking whether package.cloud.google.com is resolvable via checking the return code of `host package.cloud.google.com` in a loop actually doesn't solve the problem. A similar issue happens when trying to run `go get <go-bindata link>` on the runtime VM, even though I checked that `github.com` was resolvable:

```
==> runtime: updating /etc/resolv.conf
==> runtime: beginning waiting for DNS to resolve for github.com
==> runtime: checking if "host github.com" resolves
==> runtime: github.com has address 192.30.253.113
==> runtime: github.com has address 192.30.253.112
==> runtime: github.com mail is handled by 1 aspmx.l.google.com.
==> runtime: github.com mail is handled by 10 alt3.aspmx.l.google.com.
==> runtime: github.com mail is handled by 5 alt2.aspmx.l.google.com.
==> runtime: github.com mail is handled by 10 alt4.aspmx.l.google.com.
==> runtime: github.com mail is handled by 5 alt1.aspmx.l.google.com.
==> runtime: DNS resolved successfully
==> runtime: sleeping to let DNS get situated
==> runtime: Adding user `vagrant' to group `docker' ...
==> runtime: Adding user vagrant to group docker
==> runtime: Done.
==> runtime: # cd /go/src/github.com/jteeuwen/go-bindata; git pull --ff-only
==> runtime: fatal: unable to access 'https://github.com/jteeuwen/go-bindata/': Could not resolve host: github.com
==> runtime: package github.com/jteeuwen/go-bindata: exit status 1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Thus, in #2480, I figured retrying is the best we can do.
