### ISSUE TITLE
CI: kubernetes-e2e (ipv4): Services should create endpoints for unready pods

### ISSUE THREAD

**Issue by joestringer** [cilium/cilium#25655]
## CI failure

Example failure: https://github.com/cilium/cilium/actions/runs/5070707417/jobs/9106108631?pr=25653

![image](https://github.com/cilium/cilium/assets/1243336/b3322684-5f0f-4403-95cb-7ff95a50eb05)

```
Run # output_dir
  # output_dir
  mkdir -p _artifacts
  
  # get kubeconfig to pass to the e[2](https://github.com/cilium/cilium/actions/runs/5070707417/jobs/9106108631?pr=25653#step:13:2)e binary
  kind get kubeconfig --name cilium-testing > _artifacts/kubeconfig.conf
  
  # Kubernetes e2e tests use ginkgo and tags to select the tests that should run based on two regex, focus and skip:
  # Focus tests:
  # \[Conformance\]|\[sig-network\]: Conformance tests are defined by the project to guarantee a consistent behaviour and some mandatory features on all clusters
  #                                  sig-network tests are defined by sig-networkto guarantee a consistent behaviour on all the the k8s network implementations
  # Skipped tests:
  # Disruptive|Serial : require to run in serial and perform disruptive operations on clusters (reboots, ...)
  # Federation|PerformanceDNS : unrelated sig-network tests
  # Feature : skip features that are not GA, however, some of them should be enabled, per example [Feature:ProxyTerminatingEndpoints]
  # DualStack : only with dualstack clusters
  # KubeProxy|kube-proxy : kube-proxy specifics
  # LoadBalancer|GCE|ExternalIP : require a cloud provider, some of them are GCE specifics
  # Netpol|NetworkPolicy : network policies, demand significant resources and use to be slow, better to run in a different job
  # Aggregator : Flaky, https://github.com/cilium/cilium/issues/24622.
  # same.port.number.but.different.protocols|HostPort|should.serve.endpoints.on.same.port.and.different.protocols : #9207
  # rejected : Kubernetes expect Services without endpoints associated to REJECT the connection to notify the client, Cilium silently drops the packet
  # externalTrafficPolicy : needs investigation
  
  # Run tests
  export KUBERNETES_CONFORMANCE_TEST='y'
  export E2E_REPORT_DIR=${PWD}/_artifacts
  /usr/local/bin/ginkgo --nodes=25                \
    --focus="\[Conformance\]|\[sig-network\]"     \
    --skip="Feature|Federation|PerformanceDNS|DualStack|Disruptive|Serial|KubeProxy|kube-proxy|ExternalIP|LoadBalancer|GCE|Netpol|NetworkPolicy|Aggregator|rejected|externalTrafficPolicy|HostPort|same.port.number.but.different.protocols|should.serve.endpoints.on.same.port.and.different.protocols"   \
    /usr/local/bin/e2e.test                       \
    --                                            \
    --kubeconfig=${PWD}/_artifacts/kubeconfig.conf     \
    --provider=local                              \
    --dump-logs-on-failure=true                   \
    --report-dir=${E2E_REPORT_DIR}                \
    --disable-log-dump=true
  shell: /usr/bin/bash -e {0}
  env:
    kind_version: v0.19.0
    cluster_name: cilium-testing
    cilium_cli_version: v0.14.[3](https://github.com/cilium/cilium/actions/runs/5070707417/jobs/9106108631?pr=25653#step:13:3)
    cilium_cli_ci_version: 
    k8s_version: v1.27.1
    IP_FAMILY: ipv[4](https://github.com/cilium/cilium/actions/runs/5070707417/jobs/9106108631?pr=25653#step:13:4)
    QUAY_ORGANIZATION: cilium
    QUAY_ORGANIZATION_DEV: cilium
    QUAY_CHARTS_ORGANIZATION_DEV: cilium-charts-dev
Running Suite: Kubernetes e2e suite - /usr/local/bin
```

**Comment by aojea** [comment]
The failed test here is 
```
3-05-24T16:09:01.1798969Z [38;5;9m[1mSummarizing 1 Failure:[0m
2023-05-24T16:09:01.1799557Z   [38;5;9m[FAIL][0m [0m[sig-network] Services [38;5;9m[1m[It] should create endpoints for unready pods[0m
2023-05-24T16:09:01.1808136Z   [38;5;243mtest/e2e/network/service.go:1816[0m
2023-05-24T16:09:01.1808362Z 
2023-05-24T16:09:01.1808776Z [38;5;9m[1mRan 384 of 7207 Specs in 1223.042 seconds[0m
2023-05-24T16:09:01.1813196Z [38;5;9m[1mFAIL![0m -- [38;5;10m[1m383 Passed[0m | [38;5;9m[1m1 Failed[0m | [38;5;11m[1m0 Pending[0m | [38;5;14m[1m6823 Skipped[0m
2023-05-24T16:09:01.1813443Z 
2023-05-24T16:09:01.1813492Z 
```

**Comment by joestringer** [comment]
Maybe it's my browser, but I don't see that output in the actions link above :thinking: . Did you do anything particular to find that output? Does it show up under the step `Run Kubernetes sig-network conformance test`?

**Comment by aojea** [comment]
> Maybe it's my browser, but I don't see that output in the actions link above 🤔 . Did you do anything particular to find that output? Does it show up under the step `Run Kubernetes sig-network conformance test`?

heh, I always go directly to the raw logs

![image](https://github.com/cilium/cilium/assets/6450081/9638ccf8-a43a-468e-8185-224ed9e5780d)

**Comment by aojea** [comment]
The test fails when it tries to dial-into the pod
```
2023-05-24T15:55:41.7740891Z   [1mSTEP:[0m Verifying pods for RC slow-terminating-unready-pod [38;5;243m@ 05/24/23 15:54:51.469[0m
2023-05-24T15:55:41.7745317Z   May 24 15:54:51.502: INFO: Pod name slow-terminating-unready-pod: Found 1 pods out of 1
2023-05-24T15:55:41.7746462Z   [1mSTEP:[0m ensuring each pod is running [38;5;243m@ 05/24/23 15:54:51.502[0m
2023-05-24T15:55:41.7751360Z   [1mSTEP:[0m trying to dial each unique pod [38;5;243m@ 05/24/23 15:55:14.283[0m
2023-05-24T15:55:41.7757181Z   May 24 15:55:14.545: INFO: Failed inside E2E framework:
2023-05-24T15:55:41.7760960Z       k8s.io/kubernetes/test/e2e/framework/pod.WaitForPodsResponding({0x7f0504379858, 0xc002fa5950}, {0x72b3810?, 0xc00424a000}, {0xc0013d3670, 0xd}, {0x6b12fdc, 0x1c}, 0x0, 0xd18c2e2800, ...)
2023-05-24T15:55:41.7761492Z       	test/e2e/framework/pod/wait.go:625 +0x3ef
2023-05-24T15:55:41.7765092Z       k8s.io/kubernetes/test/e2e/framework/pod.podRunningMaybeResponding({0x7f0504379858, 0xc002fa5950}, {0x72b3810, 0xc00424a000}, {0xc0013d3670, 0xd}, {0x6b12fdc, 0x1c}, 0x0?, 0x1, ...)
2023-05-24T15:55:41.7765751Z       	test/e2e/framework/pod/resource.go:117 +0x11d
2023-05-24T15:55:41.7766578Z       k8s.io/kubernetes/test/e2e/framework/pod.VerifyPods(...)
2023-05-24T15:55:41.7767005Z       	test/e2e/framework/pod/resource.go:99
2023-05-24T15:55:41.7767519Z       k8s.io/kubernetes/test/e2e/network.glob..func27.22({0x7f0504379858, 0xc002fa5950})
2023-05-24T15:55:41.7767947Z       	test/e2e/network/service.go:1816 +0xbfb
2023-05-24T15:55:41.7768697Z   [1mSTEP:[0m stopping RC slow-terminating-unready-pod in namespace services-7833 [38;5;243m@ 05/24/23 15:55:14.546[0m
2023-05-24T15:55:41.7773463Z   [1mSTEP:[0m deleting service tolerate-unready in namespace services-7833 [38;5;243m@ 05/24/23 15:55:15.054[0m
```


Sent https://github.com/kubernetes/kubernetes/pull/118256

**Comment by gandro** [comment]
Also observed in https://github.com/cilium/cilium/pull/26894 https://github.com/cilium/cilium/actions/runs/5678805330/job/15389731243?pr=26894

Downloaded logs:
```
2023-07-27T09:39:09.0683558Z   [38;5;9m[FAILED] checking pod responses: Told to stop trying after 0.037s.
2023-07-27T09:39:09.0686969Z   Unexpected final error while getting []pod.response: Controller slow-terminating-unready-pod: failed to Get from replica pod slow-terminating-unready-pod-6njf8:
2023-07-27T09:39:09.0687901Z       <*errors.StatusError | 0xc001d8e140>: 
2023-07-27T09:39:09.0688528Z       the server is currently unable to handle the request (get pods slow-terminating-unready-pod-6njf8)
2023-07-27T09:39:09.0698548Z       {
2023-07-27T09:39:09.0710383Z           ErrStatus: 
2023-07-27T09:39:09.0710703Z               code: 503
2023-07-27T09:39:09.0715637Z               details:
2023-07-27T09:39:09.0718928Z                 causes:
2023-07-27T09:39:09.0723803Z                 - message: unknown
2023-07-27T09:39:09.0724460Z                   reason: UnexpectedServerResponse
2023-07-27T09:39:09.0727719Z                 kind: pods
2023-07-27T09:39:09.0728270Z                 name: slow-terminating-unready-pod-6njf8
2023-07-27T09:39:09.0728896Z               message: the server is currently unable to handle the request (get pods slow-terminating-unready-pod-6njf8)
2023-07-27T09:39:09.0732416Z               metadata: {}
2023-07-27T09:39:09.0734677Z               reason: ServiceUnavailable
2023-07-27T09:39:09.0737047Z               status: Failure,
2023-07-27T09:39:09.0739957Z       }
2023-07-27T09:39:09.0743075Z   Pod status:
2023-07-27T09:39:09.0743379Z       <v1.PodStatus>: 
2023-07-27T09:39:09.0743685Z           phase: Pending
2023-07-27T09:39:09.0748115Z           qosClass: BestEffort[0m
2023-07-27T09:39:09.0748975Z   [38;5;9mIn [1m[It][0m[38;5;9m at: [1mtest/e2e/network/service.go:1816[0m [38;5;243m@ 07/27/23 09:38:59.68[0m
2023-07-27T09:39:09.0755575Z [38;5;243m------------------------------[0m
2023-07-27T09:44:01.4836719Z [38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;14mS[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m[38;5;10m•[0m
2023-07-27T09:44:01.4870670Z 
2023-07-27T09:44:01.4889312Z [38;5;9m[1mSummarizing 1 Failure:[0m
2023-07-27T09:44:01.4890269Z   [38;5;9m[FAIL][0m [0m[sig-network] Services [38;5;9m[1m[It] should create endpoints for unready pods[0m
2023-07-27T09:44:01.4890769Z   [38;5;243mtest/e2e/network/service.go:1816[0m
```

**Comment by aojea** [comment]
this will be fixed by https://github.com/cilium/cilium/pull/26310

**Comment by aojea** [comment]
this should have been fixed now with the new version of kubernetes

/close

**Comment by margamanterola** [comment]
Uhm, sadly it doesn't seem to be fixed. Or at least not in 1.14.
Hit it in https://github.com/cilium/cilium/actions/runs/6124686393/job/16628681819?pr=28021

**Comment by margamanterola** [comment]
@aojea Was your fix shipped with k8s 1.27.3? That's what we are supposedly using in Cilium v1.14
https://github.com/cilium/cilium/blob/v1.14/.github/workflows/conformance-k8s-kind.yaml#L32

But we are still seeing this error :(

```
2023-09-08T20:41:47.8739896Z   STEP: trying to dial each unique pod 09/08/23 20:41:38.025
2023-09-08T20:41:47.8741936Z   Sep  8 20:41:38.332: INFO: Failed inside E2E framework:
2023-09-08T20:41:47.8744553Z       k8s.io/kubernetes/test/e2e/framework/pod.WaitForPodsResponding({0x7ff4503f1458, 0xc002939920}, {0x72b8af0?, 0xc001346680}, {0xc0026dc6f0, 0xd}, {0x6b1917f, 0x1c}, 0x0, 0xd18c2e2800, ...)
2023-09-08T20:41:47.8745074Z       	test/e2e/framework/pod/wait.go:625 +0x3ef
2023-09-08T20:41:47.8747551Z       k8s.io/kubernetes/test/e2e/framework/pod.podRunningMaybeResponding({0x7ff4503f1458, 0xc002939920}, {0x72b8af0, 0xc001346680}, {0xc0026dc6f0, 0xd}, {0x6b1917f, 0x1c}, 0x0?, 0x1, ...)
2023-09-08T20:41:47.8748054Z       	test/e2e/framework/pod/resource.go:117 +0x11d
2023-09-08T20:41:47.8750402Z       k8s.io/kubernetes/test/e2e/framework/pod.VerifyPods(...)
2023-09-08T20:41:47.8750793Z       	test/e2e/framework/pod/resource.go:99
2023-09-08T20:41:47.8753358Z       k8s.io/kubernetes/test/e2e/network.glob..func27.22({0x7ff4503f1458, 0xc002939920})
2023-09-08T20:41:47.8753720Z       	test/e2e/network/service.go:1816 +0xbfb
```

**Comment by aojea** [comment]
it is the same bug but in another function :/

I'll send a patch to fix it

**Comment by aojea** [comment]
tracking it here https://github.com/kubernetes/kubernetes/issues/120539

**Comment by margamanterola** [comment]
Thank you Antonio!

**Comment by aojea** [comment]
> Thank you Antonio!

@margamanterola very subtle bug https://github.com/kubernetes/kubernetes/pull/120559 thanks for raising it

**Comment by christarazi** [comment]
We will need to wait until the backport is merged, https://github.com/kubernetes/kubernetes/pull/120572.

**Comment by tommyp1ckles** [comment]
Think I hit it here: https://github.com/cilium/cilium/actions/runs/6788773208/job/18454485954?pr=28912

Looks like people are still hitting this following the last fix?

**Comment by tommyp1ckles** [comment]
Think we need to bump k8s/e2e to 1.28.3: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md#failing-test

I can make a PR

**Comment by aojea** [comment]
> I can make a PR

yes, please bump all kind jobs to 1.28.3

**Comment by tommyp1ckles** [comment]
Sorry, forgot to update. The dependency bot should have [bumped ](https://github.com/cilium/cilium/pull/29057) the version in all the necessary places.

**Comment by tommyp1ckles** [comment]
This should fix any remaining kind conformance test failures, closing for now.
