### ISSUE TITLE
kube-dns does not respond or takes more than 5 sec to respond on Ginkgo CI multinode setup

### ISSUE THREAD

**Issue by manalibhutiyani** [cilium/cilium#2750]
I have been trying to do the Kafka GSG setup on gingko and I see that kube-dns intermittently stops responding to queries by Kafka for zookeeper service. It sometimes takes more than 5 seconds to respond back.

We ran tcpdump on kube-dns and checking for udp port 53:

Output of no response:
Tcpdump on kube-dns pod veth device:
```
23:38:45.036012 IP (tos 0x0, ttl 63, id 35325, offset 0, flags [DF], proto UDP (17), length 76)
    10.10.0.18.58139 > 10.10.0.51.53: 35568+ A? zook.default.svc.cluster.local. (48)
23:38:45.036204 IP (tos 0x0, ttl 63, id 35326, offset 0, flags [DF], proto UDP (17), length 76)
    10.10.0.18.58139 > 10.10.0.51.53: 35872+ AAAA? zook.default.svc.cluster.local. (48)


23:38:47.536330 IP (tos 0x0, ttl 63, id 35422, offset 0, flags [DF], proto UDP (17), length 76)
    10.10.0.18.58139 > 10.10.0.51.53: 35568+ A? zook.default.svc.cluster.local. (48)
23:38:47.536444 IP (tos 0x0, ttl 63, id 35423, offset 0, flags [DF], proto UDP (17), length 76)
    10.10.0.18.58139 > 10.10.0.51.53: 35872+ AAAA? zook.default.svc.cluster.local. (48)



23:38:53.769163 IP (tos 0x0, ttl 64, id 59993, offset 0, flags [DF], proto UDP (17), length 92)
    10.10.0.51.53 > 10.10.0.18.58139: 35568 1/0/0 zook.default.svc.cluster.local. A 10.106.185.214 (64)
23:38:53.769408 IP (tos 0x0, ttl 64, id 59994, offset 0, flags [DF], proto UDP (17), length 92)
    10.10.0.51.53 > 10.10.0.18.58139: 35568 1/0/0 zook.default.svc.cluster.local. A 10.106.185.214 (64)
23:38:53.769630 IP (tos 0x0, ttl 64, id 59995, offset 0, flags [DF], proto UDP (17), length 130)
    10.10.0.51.53 > 10.10.0.18.58139: 35872* 0/1/0 (102)
```

Trying to do a nslookup intermittently worked:

```
bash-4.3# 
bash-4.3# nslookup zook
nslookup: can't resolve '(null)': Name does not resolve
Name:      zook
Address 1: 10.106.185.214 zook.default.svc.cluster.local

bash-4.3# nslookup zook
nslookup: can't resolve '(null)': Name does not resolve
nslookup: can't resolve 'zook': Try again

bash-4.3# nslookup zook
nslookup: can't resolve '(null)': Name does not resolve
nslookup: can't resolve 'zook': Try again

```

Times it worked:
```
23:42:13.994427 IP (tos 0x0, ttl 63, id 37286, offset 0, flags [DF], proto UDP (17), length 76)
    10.10.0.18.52080 > 10.10.0.51.53: 42350+ A? zook.default.svc.cluster.local. (48)
23:42:13.994461 IP (tos 0x0, ttl 63, id 37287, offset 0, flags [DF], proto UDP (17), length 76)
    10.10.0.18.52080 > 10.10.0.51.53: 42611+ AAAA? zook.default.svc.cluster.local. (48)
23:42:14.035526 IP (tos 0x0, ttl 64, id 9796, offset 0, flags [DF], proto UDP (17), length 76)
    10.10.0.51.53 > 10.10.0.18.52080: 42611 0/0/0 (48)
23:42:14.036335 IP (tos 0x0, ttl 64, id 9797, offset 0, flags [DF], proto UDP (17), length 92)
    10.10.0.51.53 > 10.10.0.18.52080: 42350* 1/0/0 zook.default.svc.cluster.local. A 10.106.185.214 (64)
23:42:14.036843 IP (tos 0x0, ttl 63, id 37296, offset 0, flags [DF], proto UDP (17), length 73)
    10.10.0.18.44160 > 10.10.0.51.53: 27909+ PTR? 214.185.106.10.in-addr.arpa. (45)
23:42:14.038448 IP (tos 0x0, ttl 64, id 9798, offset 0, flags [DF], proto UDP (17), length 117)
    10.10.0.51.53 > 10.10.0.18.44160: 27909 1/0/0 214.185.106.10.in-addr.arpa. PTR zook.default.svc.cluster.local. (89)
```

This is causing Kafka GSG setup to not work, as Kafka crashed because of lack of response or slower response from kube-dns to resolve zookeeper service.

Also, please not that there is not a lot of traffic to kube-dns, neither there is any external traffic to kube-dns, so I am not sure if it should even go through dnsmsq. 

```
Every 2.0s: kubectl get pods --all-namespaces -o=wide                                                                                                                                                           k8s1: Thu Feb  8 00:06:34 2018

NAMESPACE     NAME                                   READY     STATUS             RESTARTS   AGE       IP              NODE
default       empire-backup-555df558b9-v689m         1/1       Running            0          1h        10.10.0.18      k8s1
default       empire-hq-798cc44ff5-22c88             1/1       Running            0          1h        10.10.0.137     k8s1
default       empire-outpost-8888-59d899b56c-t9q5r   1/1       Running            0          1h        10.10.0.246     k8s1
default       empire-outpost-9999-76d5fbdc47-9pqr8   1/1       Running            0          1h        10.10.0.74      k8s1
default       kafka-broker-59d549bc55-ljs8w          0/1       CrashLoopBackOff   7          16m       10.10.0.128     k8s1
default       zookeeper-5cc9cf57c5-5qqks             1/1       Running            0          1h        10.10.0.134     k8s1
kube-system   cilium-9vhsd                           1/1       Running            0          1h        192.168.36.11   k8s1
kube-system   cilium-xrm4r                           1/1       Running            0          1h        192.168.36.12   k8s2
kube-system   etcd-k8s1                              1/1       Running            0          2h        192.168.36.11   k8s1
kube-system   kube-apiserver-k8s1                    1/1       Running            0          2h        192.168.36.11   k8s1
kube-system   kube-controller-manager-k8s1           1/1       Running            0          2h        192.168.36.11   k8s1
kube-system   kube-dns-6545987ff8-r5g24              3/3       Running            5          20m       10.10.0.117     k8s1
kube-system   kube-proxy-l46tw                       1/1       Running            0          2h        192.168.36.11   k8s1
kube-system   kube-proxy-xrffr                       1/1       Running            0          1h        192.168.36.12   k8s2
kube-system   kube-scheduler-k8s1                    1/1       Running            0          2h        192.168.36.11   k8s1
```

```
vagrant@k8s1:~$ 
vagrant@k8s1:~$ kubectl get services --all-namespaces
NAMESPACE     NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
default       kafka-service   ClusterIP   10.102.173.56    <none>        9092/TCP        1h
default       kubernetes      ClusterIP   10.96.0.1        <none>        443/TCP         2h
default       zook            ClusterIP   10.106.185.214   <none>        2181/TCP        1h
kube-system   kube-dns        ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP   2h
vagrant@k8s1:~$ 

```

For the failed lookups, the reason is that the DNS response from kube-dns is sent too late. kube-dns does respond, but too late i.e about 5-6 seconds, and by that time kafka broker gives up and crashes.

This is blocking Kafka CI testing issue #2602

**Comment by ianvernon** [comment]
Does this happen as well in the bash-script based multinode K8s setup that we have?

**Comment by joestringer** [comment]
From the tcpdump output, it appears that when the setup gets into this state, there is a several second delay between the request going into the kube-dns pod and the response coming out. From earlier inspection with @manalibhutiyani , the kube-dns pod has three containers:

* dnsmasq, listening on port 53
* kube-dns, listening on port 10053
* sidecar, which appears to be responsible for metrics

Upon inspecting the logs of the dnsmasq container, there are problematic logs `Maximum number of concurrent DNS queries reached (max: 150)`. 

Sidecar appears to have some problems with reporting metrics, and in the log message it complains every ~7s or so about problems accessing 127.0.0.1:53.

If we wish to understand further on this issue, perhaps we can look at increasing the log level for the dnsmasq process - there appears to be a `log-queries` logging option which should be more verbose about the requests coming in (and hopefully the responses going back out). There's always the option to `strace` the binary too.

Another direction which I understand @eloycoto may have been investigating is to attempt to replace kube-dns with another DNS server and see if that makes a difference.

**Comment by manalibhutiyani** [comment]
I see related similar issues:
https://github.com/gardener/gardener/issues/57
https://github.com/kubernetes/kubernetes/issues/56903
https://github.com/kubernetes/dns/issues/96
https://github.com/kubernetes/kubernetes/issues/45976

**Comment by eloycoto** [comment]
Same as #2732

**Comment by eloycoto** [comment]
Hi!

I think that I tracked down the issue. It's not a cilium issue, or connectivity issue, it's more related with the Alpine Linux.

Alpine Linux looks like that has a lot of problems with DNS, and here a few issues:

- https://github.com/gliderlabs/docker-alpine/issues/313
- https://forums.docker.com/t/resolved-service-name-resolution-broken-on-alpine-and-docker-1-11-1-cs1/19307/21

In the other hand, Alpine Linux has the following caveats:
https://github.com/gliderlabs/docker-alpine/blob/master/docs/caveats.md

The problem maybe is fixed with ndots setup in `/etc/resolv`, but I think that we should move to another image, I was thinking on `spotify/kafkaproxy` that is based on Debian. The kubernetes manifest will be like this:

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        zgroup: kafkaTestApp
    spec:
      containers:
      - name: kafka
        image: spotify/kafka
        ports:
        - containerPort: 9092
        env:
        - name: ADVERTISED_HOST
          value: kafka-service
        - name: ADVERTISED_PORT
          value: "9092"
        - name: ZK_CONNECT
          value: "zook:2181"
        - name: GROUP_ID
          value: "1"
        - name: TOPICS
          value: "empire-announce:1:1,deathstar-plans:1:1"
```

With this setup I  don't hit the issue:

Pods:
```
vagrant@k8s1:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                   READY     STATUS    RESTARTS   AGE
default       app1-75dc49777c-2dt2b                  1/1       Running   0          1h
default       app1-75dc49777c-xsgwd                  1/1       Running   0          1h
default       app2-bd6974df4-74b7k                   1/1       Running   0          1h
default       app3-7d5d8d5c68-6pq9x                  1/1       Running   0          1h
default       empire-backup-d97b7555f-m9z4q          1/1       Running   0          39m
default       empire-hq-59777c798f-hmtfh             1/1       Running   0          39m
default       empire-outpost-8888-5988f967fc-qjhnj   1/1       Running   0          39m
default       empire-outpost-9999-67f4b8ff45-wm2z9   1/1       Running   0          39m
default       kafka-proxy-5cc57566ff-r62wf           1/1       Running   0          39m
default       zookeeper-578bbf7549-n9f5m             1/1       Running   0          39m
kube-system   cilium-kbg58                           1/1       Running   0          1h
kube-system   cilium-wznrp                           1/1       Running   0          1h
kube-system   etcd-k8s1                              1/1       Running   0          2h
kube-system   kube-apiserver-k8s1                    1/1       Running   0          2h
kube-system   kube-controller-manager-k8s1           1/1       Running   0          2h
kube-system   kube-dns-6f99658fdb-kc55x              3/3       Running   11         1h
kube-system   kube-proxy-flsn2                       1/1       Running   0          2h
kube-system   kube-proxy-ghc9p                       1/1       Running   0          2h
kube-system   kube-scheduler-k8s1                    1/1       Running   0          2h
```

Script:
```
#!/bin/bash

FAILED=0
CORRECT=0
COUNT=0
START=$(date +%s)
DURATION=0
while true; do
        echo -ne "FAILED=${FAILED} CORRECT=${CORRECT} COUNT=${COUNT} DURATION=$DURATION\r"
        kubectl exec $1 -- nslookup zook >>/dev/null
        retVal=$?
        if [ ! $? -eq 0 ]; then
            let "FAILED++"
        else
            let "CORRECT++"
        fi
        let "COUNT++"
        now=$(date +%s)
        DURATION=$(($now - $START))
        sleep 0.2

done
```

Output:
```
vagrant@k8s1:~$ /src/test_kafka.sh kafka-proxy-5cc57566ff-r62wf
FAILED=0 CORRECT=124 COUNT=124 DURATION=88
```

@manalibhutiyani  could you check with this image please? Or one image based on no alpine linux? 

Regards

**Comment by manalibhutiyani** [comment]
@eloycoto : I changed the image to `spotify/kafka` and although Kafka broker is not crashing, I am unable to communicate between producer and consumer.
Note that Spotify/kafka already has zookeeper and Kafka in the same image, and we do not need to start another zookeeper service for it.

```
Every 2.0s: kubectl get pods --all-namespaces -o=wide                                                                                                                                                           k8s1: Thu Feb  8 19:11:01 2018

NAMESPACE     NAME                                   READY     STATUS    RESTARTS   AGE       IP              NODE
default       empire-backup-555df558b9-z5clv         1/1       Running   0          16m       10.10.0.137     k8s1
default       empire-hq-798cc44ff5-hl9fb             1/1       Running   0          16m       10.10.0.246     k8s1
default       empire-outpost-8888-59d899b56c-b8bhp   1/1       Running   0          16m       10.10.0.134     k8s1
default       empire-outpost-9999-76d5fbdc47-kjfh7   1/1       Running   0          16m       10.10.0.18      k8s1
default       kafka-broker-769b975794-zmcq5          1/1       Running   0          16m       10.10.0.187     k8s1
kube-system   cilium-6dpvq                           1/1       Running   0          17m       192.168.36.12   k8s2
kube-system   cilium-vh48r                           1/1       Running   0          17m       192.168.36.11   k8s1
kube-system   etcd-k8s1                              1/1       Running   0          23m       192.168.36.11   k8s1
kube-system   kube-apiserver-k8s1                    1/1       Running   0          22m       192.168.36.11   k8s1
kube-system   kube-controller-manager-k8s1           1/1       Running   0          23m       192.168.36.11   k8s1
kube-system   kube-dns-6545987ff8-grp79              3/3       Running   1          23m       10.10.0.51      k8s1
kube-system   kube-proxy-dx6vw                       1/1       Running   0          18m       192.168.36.12   k8s2
kube-system   kube-proxy-tfpgz                       1/1       Running   0          23m       192.168.36.11   k8s1
kube-system   kube-scheduler-k8s1                    1/1       Running   0          22m       192.168.36.11   k8s1


```

```
vagrant@k8s1:~$ OUTPOST_8888_POD=$(kubectl get pods -l outpostid=8888 -o jsonpath='{.items[0].metadata.name}') && kubectl exec -it $OUTPOST_8888_POD -- sh -c "PS1=\"outpost-8888 $\" /bin/bash"
outpost-8888 $ ./kafka-consume.sh --topic empire-announce
[2018-02-08 19:01:06,025] WARN Error while fetching metadata with correlation id 3 : {empire-announce=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
^C^C
```

```
Last login: Thu Feb  8 18:51:06 2018 from 10.0.2.2
vagrant@k8s1:~$ HQ_POD=$(kubectl get pods -l app=empire-hq -o jsonpath='{.items[0].metadata.name}') && kubectl exec -it $HQ_POD -- sh -c "PS1=\"empire-hq $\" /bin/bash"
pic empire-announceppy 40th Birthday to General Tagge" | ./kafka-produce.sh --to 
>>[2018-02-08 19:01:57,215] ERROR Error when sending message to topic empire-announce with key: null, value: 36 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for empire-announce-0: 34244 ms has passed since batch creation plus linger time
empire-hq $
```


kube-dns errors I still see:
```Last login: Thu Feb  8 19:05:15 2018 from 10.0.2.2
vagrant@k8s1:~$ kubectl logs -n kube-system kube-dns-6545987ff8-grp79 dnsmsq
Error from server (BadRequest): container dnsmsq is not valid for pod kube-dns-6545987ff8-grp79
vagrant@k8s1:~$ kubectl logs -n kube-system kube-dns-6545987ff8-grp79       
Error from server (BadRequest): a container name must be specified for pod kube-dns-6545987ff8-grp79, choose one of: [kubedns dnsmasq sidecar]
vagrant@k8s1:~$ kubectl logs -n kube-system kube-dns-6545987ff8-grp79 dnsmasq
I0208 19:02:22.874125       1 main.go:76] opts: {{/usr/sbin/dnsmasq [-k --cache-size=1000 --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053] true} /etc/k8s/dns/dnsmasq-nanny 10000000000}
I0208 19:02:22.874864       1 nanny.go:86] Starting dnsmasq [-k --cache-size=1000 --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053]
I0208 19:02:22.944789       1 nanny.go:111] 
W0208 19:02:22.944809       1 nanny.go:112] Got EOF from stdout
I0208 19:02:22.945613       1 nanny.go:108] dnsmasq[10]: started, version 2.78 cachesize 1000
I0208 19:02:22.945692       1 nanny.go:108] dnsmasq[10]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
I0208 19:02:22.945985       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain ip6.arpa 
I0208 19:02:22.946025       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa 
I0208 19:02:22.946051       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain cluster.local 
I0208 19:02:22.947243       1 nanny.go:108] dnsmasq[10]: reading /etc/resolv.conf
I0208 19:02:22.947288       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain ip6.arpa 
I0208 19:02:22.947314       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain in-addr.arpa 
I0208 19:02:22.947338       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.1#10053 for domain cluster.local 
I0208 19:02:22.947361       1 nanny.go:108] dnsmasq[10]: using nameserver 127.0.0.53#53
I0208 19:02:22.947386       1 nanny.go:108] dnsmasq[10]: read /etc/hosts - 7 addresses
I0208 19:04:33.947520       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:04:43.950883       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:04:53.975656       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:05:03.990933       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:05:14.003448       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:05:24.015389       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:05:34.021701       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:05:44.029027       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:05:54.040870       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:06:04.053695       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:06:14.068655       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:06:24.095951       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:06:34.115255       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:06:44.130717       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:06:54.146781       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:07:04.172833       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:07:14.184597       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
I0208 19:07:24.191840       1 nanny.go:108] dnsmasq[10]: Maximum number of concurrent DNS queries reached (max: 150)
vagrant@k8s1:~$ kubectl logs -n kube-system kube-dns-6545987ff8-grp79 sidecar
I0208 18:54:32.078329       1 main.go:51] Version v1.14.6
I0208 18:54:32.078435       1 server.go:45] Starting server (options {DnsMasqPort:53 DnsMasqAddr:127.0.0.1 DnsMasqPollIntervalMs:5000 Probes:[{Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33} {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}] PrometheusAddr:0.0.0.0 PrometheusPort:10054 PrometheusPath:/metrics PrometheusNamespace:kubedns})
I0208 18:54:32.078468       1 dnsprobe.go:75] Starting dnsProbe {Label:kubedns Server:127.0.0.1:10053 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}
I0208 18:54:32.079775       1 dnsprobe.go:75] Starting dnsProbe {Label:dnsmasq Server:127.0.0.1:53 Name:kubernetes.default.svc.cluster.local. Interval:5s Type:33}
W0208 19:01:09.302724       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:55791->127.0.0.1:53: i/o timeout
W0208 19:01:18.211860       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:37165->127.0.0.1:53: i/o timeout
W0208 19:01:25.397055       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:33321->127.0.0.1:53: i/o timeout
W0208 19:01:32.477236       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:48058->127.0.0.1:53: i/o timeout
W0208 19:01:39.677749       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:34998->127.0.0.1:53: i/o timeout
W0208 19:01:50.736533       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:39156->127.0.0.1:53: i/o timeout
W0208 19:01:58.158215       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:44941->127.0.0.1:53: i/o timeout
W0208 19:02:05.449571       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:43499->127.0.0.1:53: i/o timeout
W0208 19:02:12.463881       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:53667->127.0.0.1:53: i/o timeout
W0208 19:02:20.274861       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:55576->127.0.0.1:53: i/o timeout
W0208 19:04:37.367610       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:36947->127.0.0.1:53: i/o timeout
W0208 19:04:50.953408       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:53417->127.0.0.1:53: i/o timeout
W0208 19:04:57.961765       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:36385->127.0.0.1:53: i/o timeout
W0208 19:05:05.997144       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:34214->127.0.0.1:53: i/o timeout
W0208 19:05:13.002788       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:43683->127.0.0.1:53: i/o timeout
W0208 19:05:20.004687       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:58220->127.0.0.1:53: i/o timeout
W0208 19:05:27.008971       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:39593->127.0.0.1:53: i/o timeout
W0208 19:05:34.014477       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:55868->127.0.0.1:53: i/o timeout
W0208 19:05:41.016444       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:50818->127.0.0.1:53: i/o timeout
W0208 19:05:48.023252       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:48258->127.0.0.1:53: i/o timeout
W0208 19:06:01.042430       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:50489->127.0.0.1:53: i/o timeout
W0208 19:06:08.043947       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:42811->127.0.0.1:53: i/o timeout
W0208 19:06:21.074008       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:57376->127.0.0.1:53: i/o timeout
W0208 19:06:28.088486       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:51803->127.0.0.1:53: i/o timeout
W0208 19:06:36.121858       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:46556->127.0.0.1:53: i/o timeout
W0208 19:06:43.148988       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:36439->127.0.0.1:53: i/o timeout
W0208 19:06:50.156634       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:37161->127.0.0.1:53: i/o timeout
W0208 19:06:57.187029       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:44175->127.0.0.1:53: i/o timeout
W0208 19:07:06.181003       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:36739->127.0.0.1:53: i/o timeout
W0208 19:07:13.202833       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:56296->127.0.0.1:53: i/o timeout
W0208 19:07:20.205018       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:42640->127.0.0.1:53: i/o timeout
W0208 19:07:27.206940       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:37890->127.0.0.1:53: i/o timeout
W0208 19:07:36.205344       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:59567->127.0.0.1:53: i/o timeout
W0208 19:07:43.212662       1 server.go:64] Error getting metrics from dnsmasq: read udp 127.0.0.1:44074->127.0.0.1:53: i/o timeout```

**Comment by manalibhutiyani** [comment]
@eloycoto 

I am still getting the same connectivity issue:

```
[2018-02-08 20:38:05,951] WARN Client session timed out, have not heard from server in 30004ms for sessionid 0x0 (org.apache.zookeeper.ClientCnxn)
Exception in thread "main" org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server 'kafka-service:2181' with timeout of 30000 ms
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1233)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:157)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:131)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:103)
	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:85)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:58)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
empire-hq $nslookup kafka-service
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'kafka-service': Try again
empire-hq $nslookup kafka-service
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'kafka-service': Try again
empire-hq $nslookup kafka-service
nslookup: can't resolve '(null)': Name does not resolve

Name:      kafka-service
Address 1: 10.111.177.18 kafka-service.default.svc.cluster.local
empire-hq $
```

I am trying with the Spotify/kafka image you recommended me to use:

The Kafka is not crashing because in this image zookeeper and Kafka are in the same container image. 
But the communication with external pods like producer / consumer still needs to go via kube-dns and is not permitted.

```
Every 2.0s: kubectl get pods --all-namespaces -o=wide                                                                                                                                                           k8s1: Thu Feb  8 20:41:14 2018

NAMESPACE     NAME                                   READY     STATUS    RESTARTS   AGE       IP              NODE
default       empire-backup-555df558b9-9r65h         1/1       Running   0          11m       10.10.0.137     k8s1
default       empire-hq-798cc44ff5-qrsdj             1/1       Running   0          11m       10.10.0.18      k8s1
default       empire-outpost-8888-59d899b56c-wjrbx   1/1       Running   0          11m       10.10.0.246     k8s1
default       empire-outpost-9999-76d5fbdc47-h9nxn   1/1       Running   0          11m       10.10.0.134     k8s1
default       kafka-broker-bdff5659d-wx5kv           1/1       Running   0          11m       10.10.0.187     k8s1
kube-system   cilium-pr6c7                           1/1       Running   0          13m       192.168.36.12   k8s2
kube-system   cilium-x8nch                           1/1       Running   0          13m       192.168.36.11   k8s1
kube-system   etcd-k8s1                              1/1       Running   0          19m       192.168.36.11   k8s1
kube-system   kube-apiserver-k8s1                    1/1       Running   0          18m       192.168.36.11   k8s1
kube-system   kube-controller-manager-k8s1           1/1       Running   0          19m       192.168.36.11   k8s1
kube-system   kube-dns-6545987ff8-zmqc8              3/3       Running   1          19m       10.10.0.51      k8s1
kube-system   kube-proxy-228qp                       1/1       Running   0          13m       192.168.36.12   k8s2
kube-system   kube-proxy-s9lv6                       1/1       Running   0          19m       192.168.36.11   k8s1
kube-system   kube-scheduler-k8s1                    1/1       Running   0          19m       192.168.36.11   k8s1
```



```
vagrant@k8s1:~$ kubectl get services --all-namespaces
NAMESPACE     NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
default       kafka-service   ClusterIP   10.111.177.18   <none>        9092/TCP        15m
default       kubernetes      ClusterIP   10.96.0.1       <none>        443/TCP         22m
kube-system   kube-dns        ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP   22m
vagrant@k8s1:~$ 
```

**Comment by manalibhutiyani** [comment]
My yaml file looks like this:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
        zgroup: kafkaTestApp
    spec:
      containers:
      - name: kafka
        image: spotify/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-service
        - name: ZK_CHROOT
          value: kafka-service
        - name: GROUP_ID
          value: "1"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_CREATE_TOPICS
          value: "empire-announce:1:1,deathstar-plans:1:1"
        - name: AUTO_CREATE_TOPICS
          value: "true"
      nodeSelector:
        "kubernetes.io/hostname": k8s1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: empire-hq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: empire-hq
        zgroup: kafkaTestApp
    spec:
      containers:
      - name: empire-hq
        image: cilium/kafkaclient
      nodeSelector:
        "kubernetes.io/hostname": k8s1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: empire-outpost-8888
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: empire-outpost
        outpostid: "8888"
        zgroup: kafkaTestApp
    spec:
      containers:
      - name: empire-outpost-8888
        image: cilium/kafkaclient
      nodeSelector:
        "kubernetes.io/hostname": k8s1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: empire-outpost-9999
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: empire-outpost
        outpostid: "9999"
        zgroup: kafkaTestApp
    spec:
      containers:
      - name: empire-outpost-9999
        image: cilium/kafkaclient
      nodeSelector:
        "kubernetes.io/hostname": k8s1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: empire-backup
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: empire-backup
        zgroup: kafkaTestApp
    spec:
      containers:
      - name: empire-backup
        image: cilium/kafkaclient
      nodeSelector:
        "kubernetes.io/hostname": k8s1
```

Kakfa logs (which show that zookeeper is in the same container)


```vagrant@k8s1:~$ kubectl logs kafka-broker-769b975794-zmcq5
/usr/lib/python2.7/dist-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2018-02-08 18:55:12,263 CRIT Supervisor running as root (no user in config file)
2018-02-08 18:55:12,264 WARN Included extra file "/etc/supervisor/conf.d/kafka.conf" during parsing
2018-02-08 18:55:12,264 WARN Included extra file "/etc/supervisor/conf.d/zookeeper.conf" during parsing
2018-02-08 18:55:12,270 INFO RPC interface 'supervisor' initialized
2018-02-08 18:55:12,271 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-02-08 18:55:12,271 INFO supervisord started with pid 1
2018-02-08 18:55:13,275 INFO spawned: 'zookeeper' with pid 7
2018-02-08 18:55:13,276 INFO spawned: 'kafka' with pid 8
2018-02-08 18:55:14,315 INFO success: zookeeper entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-02-08 18:55:14,316 INFO success: kafka entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
vagrant@k8s1:~$ kubectl logs -f kafka-broker-769b975794-zmcq5
/usr/lib/python2.7/dist-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2018-02-08 18:55:12,263 CRIT Supervisor running as root (no user in config file)
2018-02-08 18:55:12,264 WARN Included extra file "/etc/supervisor/conf.d/kafka.conf" during parsing
2018-02-08 18:55:12,264 WARN Included extra file "/etc/supervisor/conf.d/zookeeper.conf" during parsing
2018-02-08 18:55:12,270 INFO RPC interface 'supervisor' initialized
2018-02-08 18:55:12,271 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-02-08 18:55:12,271 INFO supervisord started with pid 1
2018-02-08 18:55:13,275 INFO spawned: 'zookeeper' with pid 7
2018-02-08 18:55:13,276 INFO spawned: 'kafka' with pid 8
2018-02-08 18:55:14,315 INFO success: zookeeper entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-02-08 18:55:14,316 INFO success: kafka entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

```

**Comment by manalibhutiyani** [comment]
@eloycoto As you can see, its still dns that's the issue:


As you can see, `nslookup` intermittently works , or takes a lot of time to respond, due to which the producer times out. 
Changing the image is not going to help since inherently the problem is still there.

It was earlier seen in Kafka broker and now is see in producer /consumer clients...


```
nslookup: can't resolve 'kafka-service': Try again
empire-hq $nslookup kafka-service
nslookup: can't resolve '(null)': Name does not resolve

Name:      kafka-service
Address 1: 10.111.177.18 kafka-service.default.svc.cluster.local
empire-hq $cd 
empire-hq $ls
empire-hq $cd /
empire-hq $ls
bin  core  dev	etc  home  kafka  kafka-consume.sh  kafka-produce.sh  lib  lib64  linuxrc  media  mnt  opt  proc  root	run  sbin  srv	sys  tmp  usr  var
empire-hq $echo "Happy 40th Birthday to General Tagge" | ./kafka-produce.sh --topic empire-announce
>>[2018-02-08 20:58:19,321] ERROR Error when sending message to topic empire-announce with key: null, value: 36 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for empire-announce-0: 19097 ms has passed since batch creation plus linger time
empire-hq $nslookup kafka-service
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'kafka-service': Try again
empire-hq $
```

**Comment by ianvernon** [comment]
Can this be closed since https://github.com/cilium/packer-ci-build/pull/18 was merged?
