### ISSUE TITLE
Ingress: incompatible with cert-manager ACME HTTP-01

### ISSUE THREAD

**Issue by VxDlH** [cilium/cilium#28852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

With cilium 1.14.3, set the default ingress class to shared. Create a basic ClusterIssuer for the Let's Encrypt ACME HTTP01 challenge. Create an Ingress with the appropriate annotation and spec.tls setup properly.
Cilium Install
```
export CILIUM_VERSION="v1.14.3"
helm upgrade --install \
    cilium \
    cilium/cilium \
    --version ${CILIUM_VERSION} \
    --namespace kube-system \
    --set ipam.mode=kubernetes \
    --set kubeProxyReplacement=true \
    --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
    --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
    --set bpf.autoMount.enabled=true \
    --set cgroup.autoMount.enabled=false \
    --set cgroup.hostRoot=/sys/fs/cgroup \
    --set k8sServiceHost=localhost \
    --set k8sServicePort=7445 \
    --set bpf.masquerade=true \
    --set bandwidthManager.enabled=true \
    --set bandwidthManager.bbr=true \
    --set prometheus.enabled=true \
    --set operator.prometheus.enabled=true \
    --set hubble.relay.enabled=true \
    --set hubble.ui.enabled=true \
    --set hubble.enabled=true \
    --set hubble.metrics.enableOpenMetrics=true \
    --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction}" \
    --set ingressController.enabled=true \
    --set ingressController.default=true \
    --set ingressController.loadbalancerMode=shared \
    --set ingressController.service.allocateLoadBalancerNodePorts="true" \
    --set ingressController.service.loadBalancerIP="10.0.0.153" \
    --set l2announcements.enabled=true \
    --set l2podAnnouncements.enabled=true \
    --set l2podAnnouncements.interface=eth0 \
    --set k8sClientRateLimit.qps=${QPS} \
    --set k8sClientRateLimit.burst=${BURST} \
    --set envoy.enabled=true \
    --set envoy.prometheus.enabled=true \
    --set routingMode=native \
    --set ipv4NativeRoutingCIDR=10.0.0.0/8 \
    --set policyEnforcementMode=default \
    --set debug.enabled=false \
    --set autoDirectNodeRoutes=true \
    --set hostFirewall.enabled=true \
    --set loadBalancer.algorithm=maglev \
    --set maglev.tableSize=65521 \
    --set maglev.hashSeed=${SEED} \
    --set loadBalancer.mode=dsr \
    --set loadBalancer.dsrDispatch=opt \
    --values <(cat <<EOF
ingressController:
  service:
    labels:
      cilium.loadbalancer.ips.service/name: ingress-gateway-pool
EOF
)

```

Cert-manager install
```
export CERT_MANAGER_VERSION="v1.13.1"
helm upgrade --install cert-manager jetstack/cert-manager \
    --namespace cert-manager \
    --create-namespace \
    --set installCRDs=true \
    --version $CERT_MANAGER_VERSION  \
    --set "extraArgs={--feature-gates=ExperimentalGatewayAPISupport=true,--feature-gates=AdditionalCertificateOutputFormats=true}" \
    --set webhook.extraArgs={--feature-gates="AdditionalCertificateOutputFormats=true"}
```
ZeroSSL Cluster Issuer
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cilium-zerossl
spec:
  acme:
    # ZeroSSL ACME server
    server: https://acme.zerossl.com/v2/DV90
    email: ${CLUSTER_ISSUER_EMAIL}

    privateKeySecretRef:
      name: zerossl-private-key

    externalAccountBinding:
      keyID: ${ZERO_SSL_EAB_KEY_ID}
      keySecretRef:
        name: zerossl-eab-secret
        key: secret

    # ACME HTTP01 Ingress solver
    solvers:
    - http01:
        ingress:
          ingressClassName: cilium
```
LB Pool and Announcement Policy (No BGP)
```
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: ingress-gateway-pool
spec:
  disabled: false
  cidrs:
    - cidr: 10.0.0.152/30
  serviceSelector:
    matchLabels:
      cilium.loadbalancer.ips.service/name: ingress-gateway-pool
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: ingress-gateway-pool-announcement-policy
spec:
  loadBalancerIPs: true
  interfaces:
  - eth0
  serviceSelector:
    matchLabels:
      cilium.loadbalancer.ips.service/name: ingress-gateway-pool
```

Ingress Service
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${INGRESS_NAME}
  namespace: ${NAMESPACE}
  annotations:
    cert-manager.io/cluster-issuer: cilium-zerossl
spec:
  ingressClassName: cilium
  rules:
  - host: ${SERVICE_HOST}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ${SERVICE_NAME}
              port:
                number: 3001
  tls:
  - hosts:
    - ${SERVICE_HOST}
    secretName: cilium-zerossl-${INGRESS_NAME}-tls
```
Observe as cert manager spins in a loop and creates hundreds of ingresses.

![image](https://github.com/cilium/cilium/assets/5277569/86657372-30ca-4249-894a-e80bfffb60fa)

### Cilium Version

cilium-cli: v0.15.11 compiled with go1.21.3 on linux/amd64
cilium image (default): v1.14.2
cilium image (stable): v1.14.3
cilium image (running): 1.14.3

### Kernel Version

Linux: 6.1.58

### Kubernetes Version

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vincedihub** [comment]
A partial solution 

We have update the ingress with this annotation : `acme.cert-manager.io/http01-edit-in-place: "true"` (https://cert-manager.io/docs/usage/ingress/#supported-annotations)

Now, we don't have many well-know like before.  
Cert-manager add a well-know in the original Ingress request

```yaml
....
     http:
        paths:
        - backend:
            service:
              name: cm-acme-http-solver-69fj5
              port:
                number: 8089
          path: /.well-known/acme-challenge/j_fnZrscaPRqlNTcLh3KmaaE1JPK_tekuM1ZtrLgav0
          pathType: ImplementationSpecific
        - backend:
            service:
              name: myservice
              port:
                number: 3001
          path: /
          pathType: Prefix
```

There's a small change in the `.well-known` url, which goes from HTTP to HTTPS. This is not a problem, as cert-manager has anticipated this by generating a temporary certificate (https://cert-manager.io/docs/usage/certificate/#temporary-certificates-whilst-issuing)

![image](https://github.com/cilium/cilium/assets/5277569/418550a8-4593-4c57-9dcf-fc78b65faa83)


But we have discovered another problem: Cilium does not correctly manage two types of pathType in the same ingress. `pathType: ImplementationSpecific` and `pathType: Prefix`.

We did a `curl` test on the well-know, and noticed the redirection (see `location` on screenshot). This redirection belongs to application's `pathType: Prefix`. We found that `pathType: Prefix` took precedence over `pathType: ImplementationSpecific`which poses a problem.
![image](https://github.com/cilium/cilium/assets/5277569/10c0e425-b4c4-438d-a5f9-9865658cf715)

One solution is to deploy ingress with a path other than "/" for the application

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: my-app-namespace

  annotations:
    cert-manager.io/cluster-issuer: zerossl-production
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: cilium
  tls:
  - hosts:
    - app.mydomain.com
    secretName: my-app-tls
  rules:
  - host: app.mydomain.com
    http:
      paths:
        - path: /totot
          pathType: Prefix
          backend:
            service:
              name: my-app-svc
              port:
                number: 9600
```

Then wait for cert-manager to generate the certificate, to finally put the right path `/` back into ingress.

This is a temporary solution, as we'll have the problem again the next time the certificate is renewed.

**Comment by youngnick** [comment]
I think this is a duplicate of #22340?

**Comment by youngnick** [comment]
Actually, no, sorry.

Does cert-manager set the ingressClassName as directed in the config correctly? All of those ingress classes that get created, do they have an ingressClass name set? And do they have an ownerReference? If they don't have an ownerreference, then this will hit the same issue as #22340 if something strips the owner reference from the Ingress, then cert-manager has no way to know that it owns the Ingress, and so will create a new one, which will have the same problem, and so on. However, it looks like #28452 will fix that exact problem. That fix did not make 1.14.3, so could you test with `main`?

**Comment by vincedihub** [comment]
I try with **latest/main** version

```
helm upgrade --install \
    cilium \
    cilium/cilium \
    --version ${CNI_CILIUM_VERSION} \
    --namespace kube-system \
    --set ipam.mode=kubernetes \
    --set kubeProxyReplacement=true \
    --set securityContext.capabilities.ciliumAgent="{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}" \
    --set securityContext.capabilities.cleanCiliumState="{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}" \
    --set bpf.autoMount.enabled=true \
    --set cgroup.autoMount.enabled=false \
    --set cgroup.hostRoot=/sys/fs/cgroup \
    --set k8sServiceHost=localhost \
    --set k8sServicePort=7445 \
    --set bpf.masquerade=true \
    --set bandwidthManager.enabled=true \
    --set bandwidthManager.bbr=true \
    --set prometheus.enabled=true \
    --set operator.prometheus.enabled=true \
    --set hubble.relay.enabled=true \
    --set hubble.ui.enabled=true \
    --set hubble.enabled=true \
    --set hubble.metrics.enableOpenMetrics=true \
    --set hubble.metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,httpV2:exemplars=true;labelsContext=source_ip\,source_namespace\,source_workload\,destination_ip\,destination_namespace\,destination_workload\,traffic_direction}" \
    --set ingressController.enabled=true \
    --set ingressController.default=true \
    --set ingressController.loadbalancerMode=shared \
    --set ingressController.service.allocateLoadBalancerNodePorts="true" \
    --set ingressController.service.loadBalancerIP="10.0.0.153" \
    --set l2announcements.enabled=true \
    --set l2podAnnouncements.enabled=true \
    --set l2podAnnouncements.interface=eth0 \
    --set k8sClientRateLimit.qps=${QPS} \
    --set k8sClientRateLimit.burst=${BURST} \
    --set envoy.enabled=true \
    --set envoy.prometheus.enabled=true \
    --set routingMode=native \
    --set ipv4NativeRoutingCIDR=10.0.0.0/8 \
    --set policyEnforcementMode=default \
    --set debug.enabled=false \
    --set autoDirectNodeRoutes=true \
    --set hostFirewall.enabled=true \
    --set loadBalancer.algorithm=maglev \
    --set maglev.tableSize=65521 \
    --set maglev.hashSeed=${SEED} \
    --set loadBalancer.mode=dsr \
    --set loadBalancer.dsrDispatch=opt \
    --set image.tag="latest" \
    --set image.pullPolicy="Always" \
    --set operator.image.tag="latest" \
    --set operator.image.pullPolicy="Always" \
    --values <(cat <<EOF
ingressController:
  service:
    labels:
      cilium.loadbalancer.ips.service/name: ingress-gateway-pool
EOF
)
```


I run `cilium status --wait`

```
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             OK
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    OK
 \__/¯¯\__/    Hubble Relay:       OK
    \__/       ClusterMesh:        disabled

DaemonSet              cilium-envoy       Desired: 5, Ready: 5/5, Available: 5/5
DaemonSet              cilium             Desired: 5, Ready: 5/5, Available: 5/5
Deployment             hubble-ui          Desired: 1, Ready: 1/1, Available: 1/1
Deployment             hubble-relay       Desired: 1, Ready: 1/1, Available: 1/1
Deployment             cilium-operator    Desired: 2, Ready: 2/2, Available: 2/2
Containers:            cilium             Running: 5
                       cilium-envoy       Running: 5
                       hubble-ui          Running: 1
                       hubble-relay       Running: 1
                       cilium-operator    Running: 2
Cluster Pods:          34/34 managed by Cilium
Helm chart version:    1.14.3
Image versions         hubble-ui          quay.io/cilium/hubble-ui:v0.12.1@sha256:9e5f81ee747866480ea1ac4630eb6975ff9227f9782b7c93919c081c33f38267: 1
                       hubble-ui          quay.io/cilium/hubble-ui-backend:v0.12.1@sha256:1f86f3400827a0451e6332262467f894eeb7caf0eb8779bd951e2caa9d027cbe: 1
                       hubble-relay       quay.io/cilium/hubble-relay:v1.14.3@sha256:3f5c425faca4f8a38e29d4f86db2aadd8f33c9f05debd78a2bb2a24dd9e565d8: 1
                       cilium-operator    quay.io/cilium/operator-generic:latest@sha256:c9613277b72103ed36e9c0d16b9a17cafd507461d59340e432e3e9c23468b5e2: 2
                       cilium             quay.io/cilium/cilium:latest@sha256:e5ca22526e01469f8d10c14e2339a82a13ad70d9a359b879024715540eef4ace: 5
                       cilium-envoy       quay.io/cilium/cilium-envoy:v1.25.10-f71a313bd0daee41470af31ce6ea20c750fe35dd@sha256:bfa1e919ed02afc66e9ff36c1fd9148237fc8b8560a0b44d89acf144b0ffb08c: 5
```

I deploy the same ingress

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${INGRESS_NAME}
  namespace: ${NAMESPACE}
  annotations:
    cert-manager.io/cluster-issuer: cilium-zerossl
spec:
  ingressClassName: cilium
  rules:
  - host: ${SERVICE_HOST}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ${SERVICE_NAME}
              port:
                number: 3001
  tls:
  - hosts:
    - ${SERVICE_HOST}
    secretName: cilium-zerossl-${INGRESS_NAME}-tls
```


I got the same issue. 

`k get ing cm-acme-http-solver-mb6n7 -o yaml`

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0,::/0
  creationTimestamp: "2023-10-30T13:23:45Z"
  generation: 1
  labels:
    acme.cert-manager.io/http-domain: "420545623"
    acme.cert-manager.io/http-token: "1202196135"
    acme.cert-manager.io/http01-solver: "true"
  name: cm-acme-http-solver-mb6n7
  namespace: ---REMOVED---
  resourceVersion: "9727346"
  uid: fe0b437f-e362-4c74-9e66-0b16c0a901a4
spec:
  ingressClassName: cilium
  rules:
  - host: ---REMOVED---
    http:
      paths:
      - backend:
          service:
            name: cm-acme-http-solver-n9jg5
            port:
              number: 8089
        path: /.well-known/acme-challenge/dMOEaTxtsk_Gzq6UB_b90jPPslBV11VW9Lq7y0qoIhc
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 10.0.0.153
```

**Comment by vincedihub** [comment]
Will I have the same problem with the GatewayAPI and Cert-Manager combination? 

Is there any way to correct the problem between pathType: ImplementationSpecific and pathType: Prefix in the same ingress?

**Comment by vincedihub** [comment]
> I think this is a duplicate of #22340?

I created a new one because the one mentioned was marked as closed and I had no feedback.

**Comment by youngnick** [comment]
> However, I can't find any trace of ownerReference. Or do I need to verify the presence of this ownerReference property?

Yes, without the ownerReference, then cert-manager doesn't know that the Ingress belongs to it, so it creates a new one, and so on.

This does seem similar to the problem in #22340, but it seemed like that was fixed.

**Comment by squeed** [comment]
@youngnick can I assign this to you? And then you can kick it as you like?

**Comment by vincedihub** [comment]
Is there any way to correct the problem between pathType: ImplementationSpecific and pathType: Prefix in the same ingress?

**Comment by cornfeedhobo** [comment]
I'm hitting this as well. I can be reached over slack if you need faster replies.

**Comment by jackmaninov** [comment]
> Is there any way to correct the problem between `pathType: ImplementationSpecific` and `pathType: Prefix` in the same ingress?

I've been hitting this conflict between the two pathTypes as well on v1.15.0-pre.2, both in a single ingress and in separate ones (with a default TLS secret set). Finding this report helped me work around the issue. I have almost the same cilium config but without the L2 announcements, maglev and DSR.

**Comment by cornfeedhobo** [comment]
> Cilium does not correctly manage two types of pathType in the same ingress. pathType: ImplementationSpecific and pathType: Prefix.

@vincedihub I'm seeing this on ingresses that have only one path. I think the issue is rooted in a regression since `ImplementationSpecific` was patched last time.

@youngnick Could this get some attention? It's a hard blocker. Either this is a regression or a new but similar bug.

**Comment by youngnick** [comment]
I think there are two issues being discussed here:
- When cert-manager creates an Ingress with an ownerRef, Cilium is updating the Ingress and stripping the ownerRef again, it seems.
- Overlapping Ingresses with different PathTypes do not behave as expected. Is that right @vincedihub? Could you give a little more detail on this problem?

**Comment by cornfeedhobo** [comment]
@youngnick Sorry to muddy the waters, but I think there could be one more problem in the mix. I think `ImplementationSpecific` is not being handled correctly at all. There are two PRs to the rancher helm chart to make the pathType configurable, citing cilium as the reason.

**Comment by youngnick** [comment]
Okay, thanks for that @cornfeedhobo.

**Comment by vincedihub** [comment]
> * Overlapping Ingresses with different PathTypes do not behave as expected. Is that right @vincedihub? Could you give a little more detail on this problem?

@youngnick  I had already put information on the following ticket: 
 https://github.com/cilium/cilium/issues/22340#issuecomment-1751156864
I can be more detailed, but you'll have to tell me exactly what you need.

**Comment by vincedihub** [comment]
> * When cert-manager creates an Ingress with an ownerRef, Cilium is updating the Ingress and stripping the ownerRef again, it seems.

I've described the problem I'm having, but I'm not technical enough to say what the exact cause is. If you need me to do some tests, don't hesitate.

**Comment by youngnick** [comment]
I think the problem that @vincedihub is also that `ImplementationSpecific` paths are not sorted correctly - if there is a `Prefix` match for `/` and an `ImplementationSpecific` match for any path (including `/.wellknown/...`), then the `Prefix` path match will take precedence.

So, that's a separate problem that also breaks cert-manager Ingresses - but I think it's distinct to the other problem, which is almost certainly related to `ownerReference`s not being handled properly.

A fix has been merged for the `ownerReference` problem (in #28452), but that's only available in 1.15 prereleases at the moment. I'll check in about marking that for backport.

That means that if we fix the `ImplementationSpecific` issue, then we should be good here, I think?

**Comment by cornfeedhobo** [comment]
> That means that if we fix the ImplementationSpecific issue, then we should be good here, I think?

I think/hope that sounds correct. I'm working on some test clusters, so I'm willing to test 1.15 once the `ImplementationSpecific` issue is addressed.

**Comment by cornfeedhobo** [comment]
@youngnick I did some follow up testing and it looks like `ImplementationSpecific` breaks even on ingresses with only one path.

**Comment by youngnick** [comment]
@cornfeedhobo Do the routes just not work at all? And are they Ingress objects that themselves only have a single match, but are additional routes for another Ingress (that is, the cert-manager case of adding `./well-known` to an existing Ingress with a new Ingress object?)

I ask because in that case, the matching Ingress objects are merged into a single model internally inside the Cilium operator, so a Prefix match for "/" (for example) on the a particular domain name would still beat the more specific ImplementationSpecific rule on another ingress with the same domain name.

#29381 should fix that as well.

**Comment by cornfeedhobo** [comment]
> Do the routes just not work at all?

Only `/` works. For example, rancher is able to reply with the 302 to `/dashboard`, but then `/dashboard` times out.

> And are they Ingress objects that themselves only have a single match, but are additional routes for another Ingress (that is, the cert-manager case of adding ./well-known to an existing Ingress with a new Ingress object?)

I think you have a point here. It's two ingress objects, each with one path, but they are for the same hostname, so cilium is probably merging them internally, as you are suggesting.

> #29381 should fix that as well.

Great! Thank you for prioritizing this bug :)

**Comment by youngnick** [comment]
@cornfeedhobo, with the merge of #29381, we should be good on both fronts. Could you drop an update here with the results?

**Comment by jackmaninov** [comment]
Updating to 1.15.0-pre.3 seems to have resolved this for me.

**Comment by cornfeedhobo** [comment]
haha you caught me just as I've moved to playing with the gateway. Give me a day and I should be able to confirm.

**Comment by cornfeedhobo** [comment]
Preliminary testing has the `ImplementationSpecific` routing solved, but cert-manager still seems to be losing track of the created solver ingress resource.

**Comment by cornfeedhobo** [comment]
@youngnick Trying again today, and I was wrong. This *does **not*** appear to be fixed. Again, I'm using the rancher chart as the test bed and it creates an ingress for itself, which 404s after redirecting from `/`. I think this needs further investigation.

**Comment by youngnick** [comment]
@cornfeedhobo sorry about the delay here - this is with  1.15.0-pre.3? Could you post the Ingresses?

The reason why we need to treat these differently is that in Gateway API, they're very different - regex path matching is not supported there yet, and we use the same data model to handle both Ingress and Gateway API.

**Comment by cornfeedhobo** [comment]
@youngnick no worries. I know how it goes.

> this is with 1.15.0-pre.3?

Yes. These are my relevant helm settings:

```yaml
image:
  tag: "v1.15.0-pre.3"
operator:
  image:
    tag: "v1.15.0-pre.3"
```

> Could you post the Ingresses?

Here is [a gist](https://gist.github.com/cornfeedhobo/f7a6729f8c3527e043ddcf9e5b1c2846) of the rancher ingress and the 3 cert-manager ingress shims. `1.15.0-pre.3` made it so it doesn't create shims indefinitely, but that seems to be a byproduct of the HTTP01 challenge being satisfied, not because cert-manager is properly tracking the created ingresses now.

**Comment by cornfeedhobo** [comment]
@youngnick after a number of missteps for testing, I can confirm you've fixed the issue. Thank you!

**Comment by youngnick** [comment]
Unfortunately, if cert-manager is creating ImplementationSpecific Ingress objects, then the fix needs to be there. We have folks relying on our meaning of ImplementationSpecific, so we can't change what it means, sorry.

This is really a holdover from Ingress v1beta1, which did not have the path type setting, so everything was implementation specific.

**Comment by youngnick** [comment]
Just wanted to update here that, with the merge of cert-manager/cert-manager#7767, cert-manager/cert-manager#6805 is now also closed, meaning that the next release of cert-manager will include the fix to always use `Exact` for Ingress HTTP01 challenges. This will ensure this interaction is fixed for good!

**Comment by sspreitzer** [comment]
`cert-manager` has released version `1.18.0`, which now should allow cert-manager and cilium ingress to work. Please leave a comment, so I know that this is working for cilium now. Thank you

**Comment by sinner-** [comment]
Hey @youngnick 

I can see that cert-manager is using `Exact` now but it still seems to me that there's some incompatibility here that we are running into.

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: <redacted>
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
      - http01:
          ingress:
            ingressClassName: cilium
            ingressTemplate:
              metadata:
                annotations:
                  ingress.cilium.io/force-https: disabled
```

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websocket-echo-ingress-a
  namespace: test
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - example.com
      secretName: examplecom-tls
  rules:
    - host: 'example.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: websocket-echo
                port:
                  number: 80
``` 

When using `ingressController.loadbalancerMode=shared` 

```
# kubectl -n test get ingress 
NAME                        CLASS    HOSTS                           ADDRESS      PORTS     AGE
cm-acme-http-solver-j845j   cilium   example.com   10.35.35.35   80        3s
websocket-echo-ingress-a    cilium   example.com   10.35.35.35   80, 443   4s
```

```
# kubectl -n test get ingress cm-acme-http-solver-j845j -o yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.cilium.io/force-https: disabled
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0,::/0
  creationTimestamp: "2025-08-04T08:10:32Z"
  generateName: cm-acme-http-solver-
  generation: 1
  labels:
    acme.cert-manager.io/http-domain: "..."
    acme.cert-manager.io/http-token: "..."
    acme.cert-manager.io/http01-solver: "true"
  name: cm-acme-http-solver-j845j
  namespace: test
  ownerReferences:
  - apiVersion: acme.cert-manager.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Challenge
    name: examplecom-tls-1-...-...
    uid: ...
  resourceVersion: "2367177"
  uid: ...
spec:
  ingressClassName: cilium
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: cm-acme-http-solver-h77gx
            port:
              number: 8089
        path: /.well-known/acme-challenge/...
        pathType: Exact
status:
  loadBalancer:
    ingress:
    - ip: 10.35.35.35
```

Then all the challenges fail 
```
# kubectl logs -n cert-manager deploy/cert-manager
...
E0804 08:11:33.100047       1 sync.go:176] "propagation check failed" err="failed to perform self check GET request 'http://example.com/.well-known/acme-challenge/...': Get \"https://example.com/.well-known/acme-challenge/...\": EOF" logger="cert-manager.controller" resource_name="examplecom-tls-1-...-..." resource_namespace="test" resource_kind="Challenge" resource_version="v1" dnsName="example.com" type="HTTP-01"
```

Hitting the URL manually with `curl` shows that it's getting:
```
$ curl -v 'http://example.com/.well-known/acme-challenge/...'
* Host example.com:80 was resolved.
* IPv6: (none)
* IPv4: 1.1.1.1
*   Trying 1.1.1.1:80...
* Connected to example.com (1.1.1.1) port 80
> GET /.well-known/acme-challenge/... HTTP/1.1
> Host: example.com
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 301 Moved Permanently
< location: https://example.com/.well-known/acme-challenge/...
< date: Mon, 04 Aug 2025 07:06:21 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host example.com left intact
```

It looks like the challenge requests always go to the `websocket-echo-ingress-a` Ingress and never hit the `cm-acme-http-solver-j845j` Ingress :( I think I'm able to confirm this because if I change the `Path` to `/foobar` then all the challenge requests 404 instead.

If I annotate the Ingress with 
```
ingress.cilium.io/force-https: disabled
acme.cert-manager.io/http01-edit-in-place: "true"
```

then I can get it working, but the Ingress is now accessible over HTTP which is not acceptable for our use case.

If I only use 
```
acme.cert-manager.io/http01-edit-in-place: "true"
```
then I still get hit with the 301 :(

**Comment by SR4ven** [comment]
Having just run into this problem, I can confirm that it is partially fixed.

Without the annotation `acme.cert-manager.io/http01-edit-in-place: "true"` cert-manager will create a second ingress with the same hostname but a different Exact path. This does not work. Requests to the acme challenge path are answered with a redirect to https and end up on the wrong backend service. It seems that cilium doesn't support two Ingresses for one hostname at all.

With the in-place-edit annotation, things look slightly better. The problem here is again the redirect from http to https. By default cilium will enforce https if the ingress specifies a tls spec. So now the acme challenge is reachable from inside an outside of the cluster with https and a self signed temporary certificate from certmanager.
However, certmanager either strictly relies on http to be available or the routing in the cilium ingress is broken, because in the cert-manager logs `"propagation check failed" err="wrong status code '404', expected '200'"` appears, which indicates, that requests to the acme challange are again hitting the wrong backend service. Again, accessing the acme-challenge URL from a browser over https works fine.
The only option I found to fix this is setting `ingress.cilium.io/force-https: disabled` on the ingress, effectively disabling https redirects completely. This is not an option for production.

I thought that maybe cert-manager can temporarily disable https redirecty by editing the ClusterIssuer as follows:
```yaml
    solvers:
      - http01:
          ingress:
            ingressClassName: cilium
            ingressTemplate:
              metadata:
                annotations:
                  ingress.cilium.io/force-https: disabled
```
Sadly, that doesn't work. It seems that the ingressTemplate is only for Ingresses created by cert-manager and is ignored for in place edits.

**Comment by sinner-** [comment]
hey @SR4ven,

we are using `acme.cert-manager.io/http01-edit-in-place: "true"` annotation alongside `ingress.cilium.io/loadbalancer-mode: shared` with a `solvers` of:

```
    solvers:
      - http01:
          ingress:
            ingressClassName: cilium
            ingressTemplate:
              metadata:
                annotations:
                  ingress.cilium.io/force-https: disabled
```

and it's working fine for us Cilium 1.18.1, cert-manager v1.18.2.

In our Helm values for cilium we don't explicitly set `ingressController.enforceHttps` so it should be defaulting to the documented default of `true`.

**Comment by SR4ven** [comment]
Thanks for sharing this insight @sinner- !
Seems like we use a very similar setup. We are on cilium 1.18.4 and cert manager 1.19.1.

So you are saying that cert manager sets the force-https: disable annotation temporarily on the ingress and removes it again after the acme challenge is completed?
If so I need to check why it doesn't work for me.

**Comment by sinner-** [comment]
hey @SR4ven,

It actually seems like you are right. 

The `ingress.cilium.io/force-https: disabled` annotation does **not** get applied!

But it's still working for us.

Weird, because I feel like I distinctly remember adding `ingress.cilium.io/force-https: disabled` to make it work?

Starting with this manifest:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example
  labels:
    app: example
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
    ingress.cilium.io/loadbalancer-mode: shared
    lbipam.cilium.io/ip-pool: public-vip
    external-dns.alpha.kubernetes.io/hostname: certtest.redacted.com
    external-dns.alpha.kubernetes.io/target: <redacted>
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - certtest.redacted.com
      secretName: certtest
  rules:
    - host: certtest.redacted.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: example
                port:
                  number: 80
```

the applied configuration, moments later, I can see cert-manager has "edited in place" to add the `/.well-known` route:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: certtest.redacted.com
    external-dns.alpha.kubernetes.io/target: <redacted>
    ingress.cilium.io/loadbalancer-mode: shared
    kubectl.kubernetes.io/last-applied-configuration: |
      ...
    lbipam.cilium.io/ip-pool: public-vip
  creationTimestamp: "2026-02-26T00:35:12Z"
  generation: 2 # you can see gen is 2 after cert-manager has updated the original
  labels:
    app: example
  name: example
  namespace: ...
  resourceVersion: "..."
  uid: ...
spec:
  ingressClassName: cilium
  rules:
  - host: certtest.redacted.com
    http:
      paths:
      - backend:
          service:
            name: cm-acme-http-solver-pr6xr
            port:
              number: 8089
        path: /.well-known/acme-challenge/redacted
        pathType: Exact
      - backend:
          service:
            name: example
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - certtest.redacted.com
    secretName: certtest
status:
  loadBalancer:
    ingress:
    - ip: redacted
```

In the `cert-manager` logs I can see it trying to do the propagation check, then it succeeds:

```
I0226 00:36:36.772260       1 pod.go:59] "found one existing HTTP01 solver pod" logger="cert-manager.controller.http01.selfCheck.http01.ensurePod" resource_name="certtest-1-2494297661-2136709523" resource_namespace="example" resource_kind="Challenge" resource_version="v1" dnsName="certtest.redacted.com" type="HTTP-01" related_resource_name="cm-acme-http-solver-g5qtm" related_resource_namespace="example" related_resource_kind="" related_resource_version=""
I0226 00:36:36.772366       1 service.go:45] "found one existing HTTP01 solver Service for challenge resource" logger="cert-manager.controller.http01.selfCheck.http01.ensureService" resource_name="certtest-1-2494297661-2136709523" resource_namespace="example" resource_kind="Challenge" resource_version="v1" dnsName="certtest.redacted.com" type="HTTP-01" related_resource_name="cm-acme-http-solver-pr6xr" related_resource_namespace="example" related_resource_kind="" related_resource_version=""
```

and then cert-manager updates the Ingress in place again:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: certtest.redacted.com
    external-dns.alpha.kubernetes.io/target: <redacted>
    ingress.cilium.io/loadbalancer-mode: shared
    kubectl.kubernetes.io/last-applied-configuration: |
      ...
  creationTimestamp: "2026-02-26T00:35:12Z"
  generation: 3 # now this is generation 3 f
  labels:
    app: example
  name: example
  namespace: example
  resourceVersion: "210258007"
  uid: ...
spec:
  ingressClassName: cilium
  rules:
  - host: certtest.redacted.com
    http:
      paths:
      - backend:
          service:
            name: example
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - certtest.redacted.com
    secretName: certtest
status:
  loadBalancer:
    ingress:
    - ip: ...
```

At no point is the `ingress.cilium.io/force-https: disabled` annotation in place and yet it works fine.

Like I said we don't disable the default value https upgrades so I must assume it's set to the default of true.

**Comment by SR4ven** [comment]
Thanks for providing this detailed information @sinner- ! Much appreciated.

Good to know that the force-https annotation also doesn't get applied for you. That at least rules out one point.

I'm still trying to find out what's wrong with our system.
When I send a curl request to http://donain/.well-known/... while the acme challenge is active, I get redirected to https with a 301 code.
@sinner- could you be so kind to check if you see the same behavior on your side?

Else I really don't know where else to look.

Edit: We too don't set ingressController.enforceHttps explicitly and rely on the default.

**Comment by sinner-** [comment]
hey @SR4ven sorry for the long delay in getting back to you.

I can confirm that when I `curl` I am getting the 301 to HTTPS,

```
% curl http://certtest.redacted.com/.well-known/acme-challenge/<redacted>-v
* Host rest.alert.acceptance.au1.dev.beehiveaki.com:80 was resolved.
* IPv6: (none)
* IPv4: IP.IP.IP.IP
*   Trying IP.IP.IP.IP:80...
* Connected to certtest.redacted.com (IP.IP.IP.IP) port 80
> GET /.well-known/acme-challenge/<redacted> HTTP/1.1
> Host: certtest.redacted.com
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 301 Moved Permanently
< location: https://certtest.redacted.com/.well-known/acme-challenge/<redacted>
< date: Wed, 25 Mar 2026 04:33:58 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host certtest.redacted.com left intact
```

but it's working fine for cert-manager, I am not sure but I think the ACME server is supposed to respect redirects? Maybe it doesn't care that the cert at that moment isn't signed, just that the challenge is valid?

According to: https://letsencrypt.org/docs/challenge-types/

```
Our implementation of the HTTP-01 challenge follows redirects, up to 10 redirects deep. It only accepts redirects to “http:” or “https:”, and only to ports 80 or 443. When redirected to an HTTPS URL, it does not validate certificates (since this challenge is intended to bootstrap valid certificates, it may encounter self-signed or expired certificates along the way).
```

so it shouldn't be a problem to get 301'd to HTTPS and as long as it's essentially valid TLS, it doesn't matter if it's self signed or expired or whatever at that moment.

I did just notice going back to your original comment

```
"propagation check failed" err="wrong status code '404', expected '200'"
```

you are getting a 404 here, it's not caused by the redirection, I don't think? I guess your edit-in-place `acme.cert-manager.io/http01-edit-in-place: "true"` annotation isn't right or something?

Are you able to do `curl -L http://.../.well-known/...` or `curl https://.../.well-known/...` and not get the 404?
