### ISSUE TITLE
The Cilium Slack is restricted to specific email domains

### ISSUE THREAD

**Issue by royolsen** [cilium/cilium#32207]
Slack appears to be restricted to specific email domains again, I tried both of these:

- https://cilium.slack.com/
- https://cilium.herokuapp.com/

**Comment by royolsen** [comment]
I guess perhaps another token refresh is in order, is this still your thing @thebsdbox ?

**Comment by thebsdbox** [comment]
This still is my thing 😢 (It's now fixed) 😆

**Comment by hbina** [comment]
This still doesn't work. Is there another place that I can use to get some help on XDP?

**Comment by hacktivist123** [comment]
Hello @hbina can you use this link? https://cilium.slack.com

It should work now!

**Comment by hbina** [comment]
Nope, still can't.
![Uploading nope still cant.png…]()

**Comment by hacktivist123** [comment]
how about with this link?

https://cilium.slack.com/signup#/domain-signup

**Comment by hbina** [comment]
BTW, this is what I saw.

![nope still cant](https://github.com/cilium/cilium/assets/6733660/ac75cdb3-b3a3-42d0-be8c-315cfa40a7b2)

**Comment by thebsdbox** [comment]
The slack.com domain we have no control over, can you try slack.cilium.io

**Comment by hbina** [comment]
Ok this link works slack.cilium.io

Thanks so much.

**Comment by ukclivecox** [comment]
For me slack.cilium.io redirects to https://cilium.slack.com/join/signup and gives the same error

**Comment by hacktivist123** [comment]
Let me take a look

**Comment by ukclivecox** [comment]
Same error for me signing up via Google

**Comment by hacktivist123** [comment]
Please use slack.cilium.io again, clear your cache

**Comment by ukclivecox** [comment]
great. works now. Thanks!

**Comment by astrosmash** [comment]
I have the same error. Either linuxfoundation or meetingtomorrow emails accepted.

**Comment by EmilyShepherd** [comment]
This is still occurring

**Comment by nogweii** [comment]
Going to that link results in a redirect to Slack that requires the mentioned domains. There isn't any invite that I can see. @hacktivist123 could you check in on it again?
