### ISSUE TITLE
Сilium L7 LB loses traffic when rolling update

### ISSUE THREAD

**Issue by miheych** [cilium/cilium#34991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

equal or higher than v1.16.0 and lower than v1.17.0

### What happened?

When L7 balancing is enabled via the service.cilium.io/lb-l7=enabled annotation, traffic from cilium-envoy to the pod does not stop when it enters the terminating status. Because of this, it is not possible to use L7 balancing in graceful update scenarios.

### How can we reproduce the issue?

1. Install cilium with support proxy load-balancing feature. kubeProxyReplacement: true
```
helm upgrade cilium ./cilium \
    --namespace kube-system \
    --reuse-values \
    --set loadBalancer.l7.backend=envoy
```
2. Deploy pods with http(or grpc) client and server(>= 2 pods), and service with annotation `service.cilium.io/lb-l7=enabled`
3. For server pods, enable pre stop hook:
``` 
           preStop:
              exec:
                command: ["/bin/sh","-c","/bin/sleep 10; kill -3 1"]
```
4. Perform rollout restart for server deployment
5. Send traffic to service while pods are in terminating state.
6. Capture incoming requests from cilium-envoy to pods that are already in the terminating state

### Cilium Version

1.16.1

### Kernel Version

Ubuntu 22.04.4 LTS  5.15.0-113

### Kubernetes Version

1.29.5

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gadiener** [comment]
We have the same issue using the envoy ingress, traffic is sent to terminating pods resulting in 503

**Comment by gadiener** [comment]
It seems Cilim is using the `serving` attribute from the [EndpointSlices](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/) to decide whenever to remove or not the endpoint from the Loadbalancer. That means that the pod will receive traffic also during termination if the readiness probe is successful.

**Comment by miheych** [comment]
It looks like you are right. I tried setting the Helm value enableK8sEndpointSlice to false and the traffic switching during rollout restart changed. Now envoy switches traffic almost immediately after containers of the previous revision go into terminating status

**Comment by gadiener** [comment]
@miheych I cannot see that option available in helm https://artifacthub.io/packages/helm/cilium/cilium/1.16.2?modal=values. Where did you find it?

**Comment by aetimmes** [comment]
https://github.com/cilium/cilium/blob/v1.16/install/kubernetes/cilium/values.yaml#L712

**Comment by miheych** [comment]
It looks like the really working option to change to this option is to apply it through extraConfig:
```yaml
extraConfig:
  enable-k8s-endpoint-slice: "false"
```
I started with it, but then I saw the enableK8sEndpointSlice option. However, judging by the code https://github.com/cilium/cilium/blob/v1.16.3/install/kubernetes/cilium/templates/cilium-configmap.yaml#L1083 it does not work if you set the value to false.

**Comment by aetimmes** [comment]
Alternately, it looks like this functionality might be controlled by the `enableK8sTerminatingEndpoint` functionality [here](https://github.com/cilium/cilium/blob/8274d7fdbfe2d259d7562a589b3e53af771ac89a/pkg/k8s/endpoints.go#L346), which defaults to `true`.

**Comment by gadiener** [comment]
Thanks @miheych and @aetimmes that is exactly what is needed, I wonder why (and when) that was set a `true` by default

**Comment by gadiener** [comment]
I see that when setting `enableK8sTerminatingEndpoint: false` the `cilium status` command reports `Graceful Termination: Disabled`. Based on my understanding and reviewing the [code](https://github.com/cilium/cilium/blob/8274d7fdbfe2d259d7562a589b3e53af771ac89a/pkg/k8s/endpoints.go#L346), graceful termination still functions, but the endpoint is immediately removed once the pod begins terminating, rather than waiting for the serving attribute to become `false`.

Doesn't it seem confusing to label `Graceful Termination` as disabled in this context? What do we mean by `Graceful Termination` in this scenario?

My expectation would be that graceful termination would not happen at all as it's "disabled" leading to downtime but that is not the case, or am I wrong?

**Comment by yesterdays-vigilante** [comment]
Thanks @aetimmes for the suggestion of turning off `enableK8sTerminatingEndpoint`.

@gadiener, the [helm doc](https://docs.cilium.io/en/stable/helm-reference/) makes it sound like the flag in fact does the opposite thing ("Configure whether to enable auto detect of terminating state for endpoints in order to support graceful termination"). Routing traffic to terminating pods seems like a strange default to me - is it possible the setting is being interpreted the wrong way around in the code?

**Comment by gadiener** [comment]
Yes I see the same behaviour

**Comment by yesterdays-vigilante** [comment]
This workaround has been [deprecated in 1.18 ](https://github.com/cilium/cilium/pull/37351), so it's obviously not a long-term solution. I'm not really sure where to go with this now - It's definitely still happening in the latest 1.16 release (1.16.6), and seems like a fairly serious bug that perhaps affects only a small-ish number of setups (envoy ingress and gateways). The [docs on graceful termination](https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#graceful-termination) certainly read like `Terminating` pods shouldn't receive new connections. Hmm.

**Comment by tobernguyen** [comment]
I'm curious if this issue only affects v1.16 or all versions from v1.13 to the latest

**Comment by yesterdays-vigilante** [comment]
I don't have a setup where I can easily test pre-16 versions (or 17.x yet), but it's definitely still happening in 16.6.

**Comment by tobernguyen** [comment]
> I don't have a setup where I can easily test pre-16 versions (or 17.x yet), but it's definitely still happening in 16.6.

I tried to reproduce the issue with Cilium version 1.16.7, but I couldn't. I haven't been on version 16.6, though.

**Comment by tobernguyen** [comment]
> I don't have a setup where I can easily test pre-16 versions (or 17.x yet), but it's definitely still happening in 16.6.

I tested this today against my current Cilium version, 1.16.7, and confirmed it's still happening.

**Comment by grantbeattie** [comment]
Still seems to be an issue in 1.17.2 also.

**Comment by grantbeattie** [comment]
And 1.17.4.

**Comment by adrianmace** [comment]
So to re-cap in hopes to gain some visibility here from Cilium.

- `EndpointSlice` resources will contain a list of endpoints and their conditions.
- When a particular endpoint (`Pod`) is terminating but its `readinessProbe` is still passing, the `conditions.serving` will remain `true`.
- The intention is to allow load balancers the ability to serve web traffic using terminating pods as long as those pods' are still in a state where they can respond.
- It appears to be only impacting those who are using Cilium's Gateway API implementation.

## Expected Behaviour

Cilium (per the code snippet linked below) intends on using these terminating pods **only as a fallback** if there are no otherwise healthy pods.

https://github.com/cilium/cilium/blob/69aab28cf10174430372aa6fbd7c1e555b267993/pkg/service/service.go#L2219-L2223

## Actual Behaviour

Cilium is continuing to route traffic to all pods, regardless of if they're terminating or not, as long as they meet the `serving` requirement.

@youngnick what are the chances we can get some more eyes on this? It's been a bug for 9 months now.

**Comment by gadiener** [comment]
Hey @adrianmace we see the same behaviour you describe also with the Kuberentes Ingress, it does not seems to be limited to the Cilium's Gateway API implementation.

**Comment by adrianmace** [comment]
> Hey [@adrianmace](https://github.com/adrianmace) we see the same behaviour you describe also with the Kuberentes Ingress, it does not seems to be limited to the Cilium's Gateway API implementation.

Good point, thanks for correcting me.

We are currently considering moving away from Cilium as a L7 proxy (leaning towards Envoy Gateway) where I'm told this is not an issue.

**Comment by gadiener** [comment]
At the moment we disabled the feature with the `enableK8sTerminatingEndpoint: false` but that is blocking us from upgrading to the latest Cilium version. Would be great to have that issue fixed

**Comment by youngnick** [comment]
@adrianmace thanks for that summary. It does seem likely that we are not accounting correctly for the state of the endpoints when we send them to Envoy. (It's Envoy that's sending the traffic, so that's the important place to ensure is being updated correctly).

I'll make sure someone has a look to see what we can do.

**Comment by adrianmace** [comment]
Reading some of the earlier comments with fresh eyes in the morning [I think the bug could be here](https://github.com/cilium/cilium/blob/69aab28cf10174430372aa6fbd7c1e555b267993/pkg/k8s/endpoints.go#L346)?

This is inside a for-loop, so each endpoint is being processed individually. Terminating/Serving endpoints will always included in the response as long as the `EnableK8sTerminatingEndpoint` is enabled.

What should be happening is that those serving endpoints are returned only when there are no ready ones.

Just musing, feel free to ignore me!

**Comment by joamaki** [comment]
The implementation for synchronizing backends to Envoy was rewritten for v1.18, which did fix this issue, but it wasn't in line with how kube-proxy or Cilium's KPR dealt with them as it was completely skipping terminating backends. I've now fixed this in https://github.com/cilium/cilium/pull/40279 to match with KPR behavior and only synchronize terminating backends if no other backends are available. 

Could I get a review on the test case https://github.com/cilium/cilium/pull/40279/files#diff-b83e3a107f0309955b0e2f77a187b9d260dc0f713afe42dd64f414e050d58883? Is this the behavior we should be expecting? Is there anything I'm not testing that I should be testing?

**Comment by gadiener** [comment]
Thanks for the PR @joamaki!

The behaviour looks correct to me, do you plan to also backport the fix in 1.17?

**Comment by joamaki** [comment]
> Thanks for the PR [@joamaki](https://github.com/joamaki)!
> 
> The behaviour looks correct to me, do you plan to also backport the fix in 1.17?

This fix isn't backportable since the implementation got rewritten. I'm heading on vacation tomorrow so won't have time myself to look into doing a v1.17/v1.16 fix for this right now.

**Comment by jrajahalme** [comment]
#40279 only resolved an adjacent issue for v1.18, the issue described here still exists in v1.17 and v1.16 (as per @joamaki comment above.

**Comment by gadiener** [comment]
Not stale
