### ISSUE TITLE
DNS disruption when using node-local-dns with local redirect policy

### ISSUE THREAD

**Issue by ryan-vance-cresta** [cilium/cilium#43454]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

equal or higher than v1.18.4 and lower than v1.19.0

### What happened?

I am following [the official example](https://docs.cilium.io/en/stable/network/kubernetes/local-redirect-policy/) for using a local redirect policy to have node-local-dns functionality. While validating dns under different scenarios, I observe dns request connection errors during any disruption to node-local-dns (daemonset rollout, manual pod termination with grace period, etc.).

I have tried many different ways to introduce safety into the node-local-dns pod termination and rollout strategy, such as custom readiness probes, rollout strategy that surges over, etc. However, I always observe momentary dns request errors from a test workload on a node where node-local-dns is being disrupted.

It does not seem like local redirect policy is gracefully handling disruptions to backend pods.

### How can we reproduce the issue?

1. Install cilium helm chart 1.18.5 with values:
  ```
  eni:
    enabled: true
  ipam:
    mode: eni
  routingMode: native
  kubeProxyReplacement: true
  ipv4NativeRoutingCIDR: 10.0.0.0/8
  k8sServiceHost: <your-eks-api-endpoint-without-https-and-port>
  k8sServicePort: "443"
  localRedirectPolicies:
    enabled: true
  hubble:
    enabled: true
    relay:
      enabled: true
    ui:
      enabled: true
  ```
2. Install node local dns following the official example
3. Run a test workload to make consistent dns requests, such as netshoot
  ```
  while true; do nslookup cilium.com; sleep 0.5; done
  ```
4. On the same node as the test workload, cause a normal disruption to node-local-dns
  - Terminate pod directly, or
  - trigger rollout of daemonset
5. Observe dns request errors from test workload

### Cilium Version

1.18.4 and 1.18.5

### Kernel Version

Linux {IP}.ec2.internal 6.12.55-74.119.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Nov  4 23:51:53 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux

### Kubernetes Version

EKS v1.33.5-eks-3025e55

### Regression

n/a

### Sysdump

Specific sydump files can be shared if necessary, I would need to review before upload.

### Relevant log output

```shell
n/a
```

### Anything else?

In my testing I observe backend pods being updated correctly in `cilium service list`.

Even when I see 2 node-local-dns pods active, then try to gracefully shutdown the old pod, I still see dns request errors.

### Cilium Users Document

- [ ] Are you a user of Cilium? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by joamaki** [comment]
Could this be fixed by https://github.com/cilium/cilium/pull/43095? Fix will be in the next v1.18 release.

**Comment by ryan-vance-cresta** [comment]
This was one of the issues I found while searching, and it was not clear if it was in 1.18.5 or not. If it will be included in the next release, I can test when it is available.  Would you know when that might be?

Also, I don't think this would fix the official example as it does not configure any readiness probe for node-local-dns.

**Comment by mattrawles** [comment]
Hi , I originally reported this under issue https://github.com/cilium/cilium/issues/43080 and it was fixed in issue https://github.com/cilium/cilium/pull/43095 , that is listed in the release notes for 1.18.6 but the issue remains in 1.18.6 (its gone from 1.19.pre-4.| @aditighag @joamaki 

Looking at the backport PR https://github.com/cilium/cilium/pull/43425 that has a message 

Dropped https://github.com/cilium/cilium/pull/43095 : multiple issue, set.go in pkg/labels do not exist in v1.18, same for types.Match

So this doesn't look like its made it to 1.18.6!

**Comment by ryan-vance-cresta** [comment]
I've tested this with the official v1.19.0 release. It appears to be working correctly now. I do not observe any dns request failures from a test workload, when node-local-dns is disrupted on the node. `cilium service list` is also updating as I expect.

This is a snippet of the readiness probe I'm using for node-local-dns, so it is safely removed from local redirect by Cilium before pod termination:
```yaml
...
lifecycle:
  preStop:
    exec:
      command:
      - sh
      - -c
      - |
        # Create shutdown marker to fail readiness probe
        # Image is slimmed down, this is what's available to create file
        echo "" > /tmp/shutdown
        # Wait for readiness probe to fail and pod to be removed from local redirect policy, before termination
        sleep 10
...
readinessProbe:
  exec:
    command:
    - sh
    - -c
    - test ! -f /tmp/shutdown
  initialDelaySeconds: 5
  periodSeconds: 2
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 2
...
```

To re-iterate a previous comment, I'm still not sure if the example in the official documentation for local redirect policy is safe, as it does not configure a readiness probe on node-local-dns.

**Comment by alphabet5** [comment]
Upgrading rke2 to `v1.33.7+rke2r3` fixed the issue for me. (I was still seeing issues with cilium v1.19.0) 
https://github.com/rancher/rke2/issues/9448
