### ISSUE TITLE
CI: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers

### ISSUE THREAD

**Issue by tgraf** [cilium/cilium#4475]
**Only affects k8s 1.11**

Non-release-k8s-versions / k8s-1.11.K8sValidatedKafkaPolicyTest KafkaPolicies 

Stacktrace
```
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/ginkgo-ext/scopes.go:373
Failed to produce to empire-hq on topic empire-announce
Expected
    <*errors.errorString | 0xc42004b050>: {
        s: "ExecKafkaPodCmd: command 'kubectl exec -n default empire-hq-6c49cd55fc-mcr6s sh -- -c \"echo 'Happy 40th Birthday to General Tagge' | ./kafka-produce.sh --topic empire-announce\"' failed '' || '[2018-06-07 16:10:06,986] WARN Removing server kafka-service:9092 from bootstrap.servers as DNS resolution failed for kafka-service (org.apache.kafka.clients.ClientUtils)\norg.apache.kafka.common.KafkaException: Failed to construct kafka producer\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:416)\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:288)\n\tat kafka.producer.NewShinyProducer.<init>(BaseProducer.scala:40)\n\tat kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:48)\n\tat kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)\nCaused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers\n\tat org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:64)\n\tat org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:373)\n\t... 4 more\ncommand terminated with exit code 1\n'",
    }
to be nil
/home/jenkins/workspace/Cilium-PR-Ginkgo-Tests-K8s/src/github.com/cilium/cilium/test/k8sT/KafkaPolicies.go:108
```

**Comment by raybejjani** [comment]
@tgraf Did https://github.com/cilium/cilium/pull/4470 fix this?
I'd like to see if I can eliminate https://github.com/cilium/cilium/issues/3878 from this case.

**Comment by tgraf** [comment]
> Did #4470 fix this?

No

**Comment by raybejjani** [comment]
Fixed by #4479

**Comment by tgraf** [comment]
> Fixed by #4479

@raybejjani Are we sure about this? It seemed odd but was it really the cause?

**Comment by raybejjani** [comment]
That's what @eloycoto told me. It was marked as always failing, so it would be easy to verify.

My mental model is that whatever is causing https://github.com/cilium/cilium/issues/3878 would have manifested here, but only with the kubedns pod. I have no proof, however.

Once I finally get a working test machine (it takes about half the day to get vagrant images...) I can try to spam this one test.

**Comment by tgraf** [comment]
We can just watch the PR-GInkgo-Tests-K8s succes. It had two green
builds and then two failed. Some PRs are likely still not rebased.

**Comment by raybejjani** [comment]
Cool. I'll check on that specifically as I do my rounds

**Comment by tgraf** [comment]
Still seeing this:
https://jenkins.cilium.io/job/Cilium-PR-Ginkgo-Tests-K8s/328/execution/node/76/log/?consoleFull

**Comment by tgraf** [comment]
@eloycoto We should consider disabling this test for k8s PR tests. It renders the entire k8s PR tests useless as we hit this in every single build.

**Comment by raybejjani** [comment]
Nope, not fixed https://jenkins.cilium.io/view/PR/job/Cilium-PR-Ginkgo-Tests-K8s/328/consoleFull

**Comment by manalibhutiyani** [comment]
Will be fixed by #4488
