### ISSUE TITLE
In IPv6 cluster routes to POD networks are not created

### ISSUE THREAD

**Issue by aspsk** [cilium/cilium#6382]
## Bug report

**General Information**

- Cilium version: 1.3.90
- Kernel version: 4.15.0-32-generic (OS: Ubuntu 18.04.1 LTS)
- Orchestration system version in use: Kubernetes v1.12.3

- Links to relevant artifacts (`*.yaml` renamed to `*.txt` as github doesn't support `yaml` uploads):
  * [cilium-etcd-operator.txt](https://github.com/cilium/cilium/files/2646060/cilium-etcd-operator.txt)
  * [cilium.txt](https://github.com/cilium/cilium/files/2646061/cilium.txt)

- The system dump: [cilium-sysdump-20181204-204148.zip](https://github.com/cilium/cilium/files/2646054/cilium-sysdump-20181204-204148.zip)

**Issue**

In an IPv6 cluster cilium pod doesn't start properly on a worker node with the following message:
```
level=fatal msg="timed out while waiting for etcd session. Ensure that etcd is running on [https://cilium-etcd-client.kube-system.svc:2379]" subsys=kvstore
```
The URL above resolves to a POD IPv6 address which belongs to master node (`fdbb::/112` net), but no route to this network exist on the worker:
```
# ip -6 route | grep fdbb
fdbb::3:0:1 dev cilium_host metric 1024 pref medium
fdbb::3:0:0/112 via fdbb::3:0:1 dev cilium_host src 2600:3c03::f03c:91ff:fe75:77b7 metric 1024 pref medium
```

**How to reproduce the issue**

Master node is initialized like this:
```
echo 1 > /proc/sys/net/ipv6/conf/all/forwarding

echo "KUBELET_EXTRA_ARGS=--node-ip=${NODE_PUBLIC_IP}" > /etc/default/kubelet
kubeadm init --service-cidr=fdaa::/112 --pod-network-cidr=fdbb::/80 --apiserver-advertise-address=${NODE_PUBLIC_IP} --apiserver-cert-extra-sans=${NODE_PUBLIC_IPv4}
mkdir -p $HOME/.kube && cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && chown root $HOME/.kube/config
export PATH=$${PATH}:/opt/bin
kubectl taint nodes --all node-role.kubernetes.io/master

mount bpffs /sys/fs/bpf -t bpf

kubectl apply -f cilium-etcd-operator.yaml
kubectl apply -f cilium.yaml
```

Worker node is initialized like this:
```
echo "KUBELET_EXTRA_ARGS=--node-ip=${NODE_PUBLIC_IP}" > /etc/default/kubelet
mount bpffs /sys/fs/bpf -t bpf
echo 1 > /proc/sys/net/ipv6/conf/all/forwarding

kubeadm join <master credentials>
```

After node joins, the cilium pod on it is constantly restarting and no routes created to the master POD network:
```
# kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                               READY   STATUS    RESTARTS   AGE   IP               NODE                        NOMINATED NODE  
kube-system   cilium-etcd-c6z69dv4pg                             1/1     Running   0          55m   fdbb::5d3d       cilium-ipv6-cpc-master-1    <none>
kube-system   cilium-etcd-dl8bvjqhgf                             1/1     Running   0          56m   fdbb::7569       cilium-ipv6-cpc-master-1    <none>
kube-system   cilium-etcd-krknx2x6k2                             1/1     Running   0          55m   fdbb::8a9        cilium-ipv6-cpc-master-1    <none>
kube-system   cilium-etcd-operator-6fb57fc649-grbft              1/1     Running   0          56m   ${MASTER_IPv6}   cilium-ipv6-cpc-master-1    <none>
kube-system   cilium-pn8pc                                       1/1     Running   11         48m   ${WORKER_IPv6}   cilium-ipv6-worker-node-1   <none>
kube-system   cilium-x257v                                       1/1     Running   0          53m   ${MASTER_IPv6}   cilium-ipv6-cpc-master-1    <none>
kube-system   coredns-576cbf47c7-f48k5                           1/1     Running   0          58m   fdbb::6289       cilium-ipv6-cpc-master-1    <none>
kube-system   coredns-576cbf47c7-s4nlh                           1/1     Running   0          58m   fdbb::ede5       cilium-ipv6-cpc-master-1    <none>
kube-system   etcd-cilium-ipv6-cpc-master-1                      1/1     Running   0          57m   ${MASTER_IPv6}   cilium-ipv6-cpc-master-1    <none>
kube-system   etcd-operator-547c5c7f84-9dm7j                     1/1     Running   0          56m   fdbb::67b5       cilium-ipv6-cpc-master-1    <none>
kube-system   kube-apiserver-cilium-ipv6-cpc-master-1            1/1     Running   0          57m   ${MASTER_IPv6}   cilium-ipv6-cpc-master-1    <none>
kube-system   kube-controller-manager-cilium-ipv6-cpc-master-1   1/1     Running   0          57m   ${MASTER_IPv6}   cilium-ipv6-cpc-master-1    <none>
kube-system   kube-proxy-rvwx9                                   1/1     Running   0          48m   ${WORKER_IPv6}   cilium-ipv6-worker-node-1   <none>
kube-system   kube-proxy-vqmhx                                   1/1     Running   0          58m   ${MASTER_IPv6}   cilium-ipv6-cpc-master-1    <none>
kube-system   kube-scheduler-cilium-ipv6-cpc-master-1            1/1     Running   0          57m   ${MASTER_IPv6}   cilium-ipv6-cpc-master-1    <none>
```

**Comment by aspsk** [comment]
Not sure if it is related or not, but when I am attaching a new node, I can see the following in logs for a cilium pod running on the master node:
```
2018-12-04T21:51:24.015672992Z level=debug msg="Empty IPv4 CIDR annotation in node" k8sNodeID=be42da1d-f80e-11e8-b83e-f23c9175d92b nodeName=cilium-ipv6-worker-node-1 subsys=k8s
2018-12-04T21:51:24.015720595Z level=debug msg="Empty IPv6 CIDR annotation in node" k8sNodeID=be42da1d-f80e-11e8-b83e-f23c9175d92b nodeName=cilium-ipv6-worker-node-1 subsys=k8s
2018-12-04T21:51:24.015736525Z level=debug msg="Empty IPv4 health endpoint annotation in node" k8sNodeID=be42da1d-f80e-11e8-b83e-f23c9175d92b nodeName=cilium-ipv6-worker-node-1 subsys=k8s
2018-12-04T21:51:24.01574893Z level=debug msg="Empty IPv6 health endpoint annotation in node" k8sNodeID=be42da1d-f80e-11e8-b83e-f23c9175d92b nodeName=cilium-ipv6-worker-node-1 subsys=k8s
2018-12-04T21:51:24.015761514Z level=warning msg="Unable to add ipcache entry of Kubernetes node" error="HostIP is not an IPv4 address: <nil>" subsys=daemon
```

**Comment by joestringer** [comment]
@aspsk Thanks, that looks really relevant.

**Comment by joestringer** [comment]
@tgraf was this addressed by your rework of the routing logic?

**Comment by tgraf** [comment]
@joestringer Yes, good catch

**Comment by joestringer** [comment]
@aspsk  Closing per the above, please re-open or file a new issue if you observe this issue with the upcoming v1.4.0 release or later.

**Comment by aspsk** [comment]
@joestringer thanks! Will test it soon

**Comment by aspsk** [comment]
@joestringer Still not able to configure an IPv6 cluster (with IPv4 disabled).

Experiment 1. Creating a cluster on two nodes. The first node is master, the second node is
worker. The master is initialized as follows:
```
# export IPv6=<master-ipv6-address>
# export IPv4=<master-ipv4-address>
# echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
# echo "KUBELET_EXTRA_ARGS=--node-ip=${IPv6}" > /etc/default/kubelet
# mount | grep bpf
bpffs on /sys/fs/bpf type bpf (rw,relatime)
kubeadm init --service-cidr=fdaa::/112 --pod-network-cidr=fdbb::/80 --apiserver-advertise-address=${IPv6} --apiserver-cert-extra-sans=${IPv4}
...
```
The worker is initialized as follows:
```
# export IPv6=<worker-ipv6-address>
# echo 1 > /proc/sys/net/ipv6/conf/all/forwarding
# echo "KUBELET_EXTRA_ARGS=--node-ip=${IPv6}" > /etc/default/kubelet
# kubeadm join ...
```

After that I am applying the cilium YAML configuration. The configuration is the default https://raw.githubusercontent.com/cilium/cilium/v1.4/examples/kubernetes/1.13/cilium.yaml with the following changes applied:
```
# diff -uN cilium.yaml cilium-my.yaml
--- cilium.yaml 2019-02-15 20:14:46.955613013 +0000
+++ cilium-my.yaml      2019-02-15 20:11:34.990661464 +0000
@@ -28,11 +28,11 @@

   # Enable IPv4 addressing. If enabled, all endpoints are allocated an IPv4
   # address.
-  enable-ipv4: "true"
+  enable-ipv4: "false"

   # Enable IPv6 addressing. If enabled, all endpoints are allocated an IPv6
   # address.
-  enable-ipv6: "false"
+  enable-ipv6: "true"

   # If a serious issue occurs during Cilium startup, this
   # invasive option may be set to true to remove all persistent
```
Apply cilium config:
```
# kubectl apply -f cilium-my.yaml
...
```

Then cilium fails to start:
```
# kubectl -n kube-system get pods -l k8s-app=cilium
NAME           READY   STATUS             RESTARTS   AGE
cilium-9nq98   0/1     CrashLoopBackOff   4          3m21s
cilium-td4nh   0/1     CrashLoopBackOff   4          3m21s
```
The reason is the following:
```
level=fatal msg="postinit failed" error="External IPv4 node address could not be derived, please configure via --ipv4-node" subsys=daemon
```

**Comment by aspsk** [comment]
Experiment 2. Creating a one-node cluster.

Cleanup/re-init the master host as follows:
```
# iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
# rm -r /var/run/cilium/
# umount /sys/fs/bpf
# mount -a
# mount | grep bpf
bpffs on /sys/fs/bpf type bpf (rw,relatime)
# kubeadm init --service-cidr=fdaa::/112 --pod-network-cidr=fdbb::/80 --apiserver-advertise-address=${IPv6} --apiserver-cert-extra-sans=${IPv4}
```

Untaint the master node so that I can schedule pods on it:
```
# kubectl taint nodes --all node-role.kubernetes.io/master-
```

Apply cilium:
```
# kubectl apply -f cilium-my.yaml
...
```

It fails with the same error as above. Now I am specifying the `--ipv4-node` parameter and restarting the cilium:
```
# kubectl apply -f cilium-my.yaml
```
After this change it is able to start.

However, this is not very useful, as it is only one node. If I am adding a second node, then the cilium pod is not able to start on it. (It runs with the same `ipv4-node` parameter as master which is obviously wrong). For reference, the error message is the following:
```
level=fatal msg="Unable to initialize local node" error="Time out while retrieving initial list of objects from kvstore" subsys=daemon
```

**Comment by aspsk** [comment]
@joestringer ah, and I can't re-open it, as it was closed by a maintainer

**Comment by ianvernon** [comment]
@aspsk sorry about that, reopened it for you.

**Comment by aspsk** [comment]
thanks @ianvernon Tell me if I need to create another ticket instead, something like "Can't create a pure IPv6 cluster"

**Comment by joestringer** [comment]
@aspsk yeah, I think that's better handled as a separate issue.

Regarding this issue, it would be good if you can keep ipv4 and ipv6 enabled then validate whether the cluster routes show up in the way that you intended. If so, we can close this issue again. Otherwise we'll need to take another look.

**Comment by aspsk** [comment]
@joestringer I've tested that IPv6 routes are created when IPv4 and IPv6 are both enabled, so sorry for bothering you.

Summary: my case didn't work because I was trying to avoid using IPv4, and it failed because on the moment cilium doesn't support encapsulation over IPv6.

**Comment by joestringer** [comment]
@aspsk no worries, thanks for validating the fix. By all means feel welcome to file another issue on specific ipv4/ipv6 configurations you're looking for and we can provide feedback on those.

Closing; fixed.

**Comment by loverto** [comment]
1.4.1 

```log
level=info msg="New endpoint" containerID= datapathPolicyRevision=0 desiredPolicyRevision=0 endpointID=349 identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="No request received to manage networking for container" containerID=3d0025b61f maxRetry=20 subsys=workload-watcher willRetry=false
level=info msg="No request received to manage networking for container" containerID=4ab5ad78c2 maxRetry=20 subsys=workload-watcher willRetry=false
level=info msg="No request received to manage networking for container" containerID=2568daeaa1 maxRetry=20 subsys=workload-watcher willRetry=false
level=info msg="Serving cilium health at http://[::]:4240" subsys=health-server
level=info msg="No request received to manage networking for container" containerID=8cafc0dd0f maxRetry=20 subsys=workload-watcher willRetry=false
level=info msg="Recompiled endpoint BPF program" BPFCompilationTime=6.450801672s containerID= datapathPolicyRevision=0 desiredPolicyRevision=1 endpointID=349 error="&lt;nil&gt;" identity=4 ipv4= ipv6= k8sPodName=/ subsys=endpoint
level=info msg="Completed endpoint regeneration" bpfCompilation=6.450801672s buildDuration=6.463902673s containerID= datapathPolicyRevision=1 desiredPolicyRevision=1 endpointID=349 identity=4 ipv4= ipv6= k8sPodName=/ mapSync="699.489µs" policyCalculation="114.098µs" prepareBuild=2.202168ms proxyConfiguration="20.099µs" proxyPolicyCalculation=5.583815ms proxyWaitForAck="3.8µs" reason="health daemon bootstrap" subsys=endpoint waitingForCTClean="122.198µs" waitingForLock="4.9µs"
level=info msg="Serving cilium health at unix:///var/run/cilium/health.sock" subsys=health-server
level=info msg="Conntrack garbage collection statistics" completed=true duration=5.177222ms family=ipv4 maxEntries=1000000 numDeleted=5 numKeyFallbacks=0 numLookups=10 numLookupsFailed=0 protocol=TCP startTime="2019-02-28 09:17:29.765171451 +0000 UTC m=+78.141194864" subsys=map-ct
level=info msg="Conntrack garbage collection statistics" completed=true duration=6.193806ms family=ipv4 maxEntries=262144 numDeleted=0 numKeyFallbacks=0 numLookups=10 numLookupsFailed=0 protocol=non-TCP startTime="2019-02-28 09:17:29.770647268 +0000 UTC m=+78.146670681" subsys=map-ct
level=info msg="Conntrack garbage collection statistics" completed=true duration=4.375634ms family=ipv6 maxEntries=1000000 numDeleted=1 numKeyFallbacks=0 numLookups=2 numLookupsFailed=0 protocol=TCP startTime="2019-02-28 09:17:29.777155669 +0000 UTC m=+78.153179082" subsys=map-ct
level=info msg="Conntrack garbage collection statistics" completed=true duration=1.283081ms family=ipv6 maxEntries=262144 numDeleted=0 numKeyFallbacks=0 numLookups=2 numLookupsFailed=0 protocol=non-TCP startTime="2019-02-28 09:17:29.781824598 +0000 UTC m=+78.157848111" subsys=map-ct
level=info msg="Conntrack garbage collection statistics" completed=true duration=7.664884ms family=ipv4 maxEntries=1000000 numDeleted=5 numKeyFallbacks=0 numLookups=10 numLookupsFailed=0 protocol=TCP startTime="2019-02-28 09:18:29.78362613 +0000 UTC m=+138.159649543" subsys=map-ct
level=info msg="Conntrack garbage collection statistics" completed=true duration=1.818472ms family=ipv4 maxEntries=262144 numDeleted=5 numKeyFallbacks=0 numLookups=10 numLookupsFailed=0 protocol=non-TCP startTime="2019-02-28 09:18:29.79157891 +0000 UTC m=+138.167602323" subsys=map-ct
level=info msg="Conntrack garbage collection statistics" completed=true duration=11.038232ms family=ipv6 maxEntries=1000000 numDeleted=2 numKeyFallbacks=0 numLookups=3 numLookupsFailed=0 protocol=TCP startTime="2019-02-28 09:18:29.79355098 +0000 UTC m=+138.169574293" subsys=map-ct
level=info msg="Conntrack garbage collection statistics" completed=true duration=1.405179ms family=ipv6 maxEntries=262144 numDeleted=1 numKeyFallbacks=0 numLookups=2 numLookupsFailed=0 protocol=non-TCP startTime="2019-02-28 09:18:29.804909907 +0000 UTC m=+138.180933320" subsys=map-ct
level=fatal msg="Unable to initialize local node" error="Time out while retrieving initial list of objects from kvstore" subsys=daemon
```

**Comment by joestringer** [comment]
@loverto I've opened a new issue for this as it's a different issue from the one originally reported in the description above: https://github.com/cilium/cilium/issues/7248 

Please take a look and if you can, provide additional info. Alternatively we may be able to help out on Slack: http://docs.cilium.io/en/latest/troubleshooting/#slack-assistance .
