### ISSUE TITLE
Error loading BPF object with --sockops-enable feature

### ISSUE THREAD

**Issue by amshinde** [cilium/cilium#7052]
## Bug report

Installed cilium using :
```
kubectl apply -f https://raw.githubusercontent.com/cilium/cilium/HEAD/examples/kubernetes/1.13/cilium-crio.yaml
```
And then edited the cilium daemonset to add `--sockops-enable` and `--debug` and then added the necessary headers to the cilium image (by bind-mounting from the host to get over this issue:
https://github.com/cilium/cilium/issues/6967)

Cilium logs show this:
```
$ kubectl logs cilium-bdxnd -n kube-system
...
level=info msg="Sockmsg Disabled." subsys=sockops
level=debug msg="Registered BPF map" path=/sys/fs/bpf/tc/globals/cilium_ep_to_policy subsys=bpf
level=debug msg="Launching compiler" args="[-emit-llvm -O2 -target bpf -D__NR_CPUS__=8 -Wno-address-of-packed-member -Wno-unknown-warning-option  -I/var/run/cilium/state/globals -I/var/run/cilium/state -I
/var/lib/cilium/bpf/include -c /var/lib/cilium/bpf/sockops/bpf_sockops.c -o -]" subsys=datapath-loader target=clang
level=debug msg="Load BPF Object:" args="[-m prog load /var/run/cilium/state/bpf_sockops.o /sys/fs/bpf/bpf_sockops map name cilium_ep_to_policy pinned /sys/fs/bpf/tc/globals/cilium_ep_to_policy map name c
ilium_ipcache pinned /sys/fs/bpf/tc/globals/cilium_ipcache map name cilium_lb4_reverse_nat pinned /sys/fs/bpf/tc/globals/cilium_lb4_reverse_nat map name cilium_lb4_services pinned /sys/fs/bpf/tc/globals/c
ilium_lb4_services map name cilium_lxc pinned /sys/fs/bpf/tc/globals/cilium_lxc map name cilium_proxy4 pinned /sys/fs/bpf/tc/globals/cilium_proxy4]" bpftool=bpftool subsys=sockops
level=error msg="Failed to load /var/run/cilium/state/bpf_sockops.o: exit status 255" subsys=sockops
```

Running the above command manually inside the agent: 
```
$ kubectl exec -it  cilium-bdxnd -n kube-system bash
bpftool -m prog load /var/run/cilium/state/bpf_sockops.o /sys/fs/bpf/bpf_sockops map name cilium_ep_to_policy pinned /sys/fs/bpf/tc/globals/cilium_ep_to_policy map name cilium_ipcache pinned /sys/fs/bpf/tc/globals/cilium_ipcache map name cilium_lb4_reverse_nat pinned /sys/fs/bpf/tc/globals/cilium_lb4_reverse_nat map name cilium_lb4_services pinned /sys/fs/bpf/tc/globals/cilium_lb4_services map name cilium_lxc pinned /sys/fs/bpf/tc/globals/cilium_lxc map name cilium_proxy4 pinned /sys/fs/bpf/tc/globals/cilium_proxy4
libbpf: maps section in /var/run/cilium/state/bpf_sockops.o: "CALLS_MAP" has unrecognized, non-zero options
libbpf: maps section in /var/run/cilium/state/bpf_sockops.o: "CALLS_MAP" has unrecognized, non-zero options
libbpf: maps section in /var/run/cilium/state/bpf_sockops.o: "cilium_ep_to_policy" has unrecognized, non-zero options
libbpf: maps section in /var/run/cilium/state/bpf_sockops.o: "cilium_events" has unrecognized, non-zero options
libbpf: maps section in /var/run/cilium/state/bpf_sockops.o: "cilium_ipcache" has unrecognized, non-zero options
libbpf: maps section in /var/run/cilium/state/bpf_sockops.o: "cilium_lb4_reverse_nat" has unrecognized, non-zero options
libbpf: maps section in /var/run/cilium/state/bpf_sockops.o: "cilium_lb4_rr_seq" has unrecognized, non-zero options
libbpf: maps section in /var/run/cilium/state/bpf_sockops.o: "cilium_lb4_services" has unrecognized, non-zero options
libbpf: maps section in /var/run/cilium/state/bpf_sockops.o: "cilium_lxc" has unrecognized, non-zero options
libbpf: maps section in /var/run/cilium/state/bpf_sockops.o: "cilium_metrics" has unrecognized, non-zero options
libbpf: maps section in /var/run/cilium/state/bpf_sockops.o: "cilium_policy" has unrecognized, non-zero options
libbpf: maps section in /var/run/cilium/state/bpf_sockops.o: "cilium_policy" has unrecognized, non-zero options
libbpf: maps section in /var/run/cilium/state/bpf_sockops.o: "cilium_proxy4" has unrecognized, non-zero options
libbpf: maps section in /var/run/cilium/state/bpf_sockops.o: "cilium_sock_ops" has unrecognized, non-zero options
libbpf: incorrect bpf_call opcode
Error: failed to open object file
```

I am using kernel 4.19.19 with stream_parser enabled in the config.
Tried on an Ubuntu ppa kernel : https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.19.19/
Also tried this with a ClearLinux 4.19.19 kernel. Kernel Config can be found here:
https://github.com/clearlinux-pkgs/linux-lts/blob/4b4eecba8782130793355b5b9db71e1a0d705329/config

**General Information**

- Cilium version (run `cilium version`)
```
cilium version
Client: 1.4.90 6a8cb1f 2019-01-23T20:34:56-08:00 go version go1.11 linux/amd64
Daemon: 1.4.90 6a8cb1f 2019-01-23T20:34:56-08:00 go version go1.11 linux/amd64
```
- Kernel version (run `uname -a`)
```
uname -r
4.19.19-415.lts
```

- Orchestration system version in use (e.g. `kubectl version`, Mesos, ...)
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"archive", BuildDate:"2019-02-03T06:32:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ianvernon** [comment]
cc: @jrfastab

**Comment by amshinde** [comment]
I looked into this error a bit, and found this: https://do-db2.lkml.org/lkml/2018/4/25/411
Looks like the `incorrect bpf_call opcode`  may be due to the llvm version not supporting bpf function calls.
The docs here https://lwn.net/Articles/741773/ mention that llvm 6.0 is required for bpf function calls.
I havent looked at the code closely, but I suspect the sockmap feature uses function calls.
@jrfastab Let me know.
I see that the cilium image packaged has an older version of llvm

```
kubectl exec -it cilium-zcm85 -n kube-system bash
root@clr-03:~# clang --version
clang version 3.8.1 (tags/RELEASE_381/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/clang+llvm/bin
root@clr-03:~# llc --version
LLVM (http://llvm.org/):
  LLVM version 3.8.1
  Optimized build.
  Default target: x86_64-unknown-linux-gnu
  Host CPU: broadwell
```

(I tried to test this idea out by adding a step to install the bionic llvm 6.0 package in the Dockerfile provided and deleting the 3.8 version under /usr/local/clang+llvm, but this led to bpf features not being detected properly.)

@jrfastab Let me know what you think?

**Comment by amshinde** [comment]
cc @mcastelino

**Comment by jrfastab** [comment]
Resolved and we now have a ginkgo test covering this.

**Comment by joestringer** [comment]
Per @jrfastab , this was addressed in v1.5.

**Comment by joestringer** [comment]
Fresh user reports of this kind of issue with Cilium 1.5.0, reopening.

**Comment by deesee04** [comment]
following up from slack and attaching the relevant pod log.

[podlog.txt](https://github.com/cilium/cilium/files/3129260/podlog.txt)

**Comment by mrostecki** [comment]
I can't reproduce this usue both on Cilium 1.6.3 and 1.5.9. I'm closing this issue.

**Comment by deesee04** [comment]
apologies for not following up, but this is still present and has been in every version including the latest, 1.6.5.

it happens on a fresh cluster, using the installation manifests referenced in the documentation (in this case, for an EKS cluster)

i've attached the latest pod logs, though the error is the same as it was when i reported it in april.

cilium 1.6.5
eks version platform version 1.14.7
coreos stable 2303.3.0

[podlog.txt](https://github.com/cilium/cilium/files/3986407/podlog.txt)

**Comment by jrfastab** [comment]
@deesee04 looks like kernel is missing some necessary configuration/support. Do you happen to have a config for one of these nodes? Usually it can be found in either /proc/config.gz or /boot/config*.

I can also get an EKS cluster up as well but if the config is handy on your side that makes it easier.

**Comment by deesee04** [comment]
@jrfastab 

i've attached `/proc/config.gz` from one of the coreos nodes.

[config.gz](https://github.com/cilium/cilium/files/3986717/config.gz)

**Comment by jrfastab** [comment]
thanks @deesee04 missing stream parser so the error is correct although we could probably do a bit better indicating where the error is coming from. We will need a bit of probing though to nail down exactly what failed.

```
 # CONFIG_BPF_STREAM_PARSER is not set
```

For coreos lets see if we can get stream parser enabled.
